SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.CANTIDAD_PASAJERO_ADULTO
,UAT.CANTIDAD_PASAJERO_ADULTO
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.CANTIDAD_PASAJERO_ADULTO!=UAT.CANTIDAD_PASAJERO_ADULTO THEN 1 ELSE 0 END )=1
