SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.CANTIDAD_PASAJERO_NINO
,UAT.CANTIDAD_PASAJERO_NINO
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.CANTIDAD_PASAJERO_NINO!=UAT.CANTIDAD_PASAJERO_NINO THEN 1 ELSE 0 END )=1
