SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.CESION_RUC
,UAT.CESION_RUC
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.CESION_RUC))!=TRIM(UPPER(UAT.CESION_RUC)) THEN 1 ELSE 0 END )=1
