SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.COMPANIA_IC
,UAT.COMPANIA_IC
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.COMPANIA_IC))!=TRIM(UPPER(UAT.COMPANIA_IC)) THEN 1 ELSE 0 END )=1
