SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.COMPANIA
,UAT.COMPANIA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.COMPANIA))!=TRIM(UPPER(UAT.COMPANIA)) THEN 1 ELSE 0 END )=1
