SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.FLAG_CESIONADA
,UAT.FLAG_CESIONADA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.FLAG_CESIONADA))!=TRIM(UPPER(UAT.FLAG_CESIONADA)) THEN 1 ELSE 0 END )=1
