SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.FLAG_COBERTURA_IA
,UAT.FLAG_COBERTURA_IA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.FLAG_COBERTURA_IA!=UAT.FLAG_COBERTURA_IA THEN 1 ELSE 0 END )=1
