SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.FRECUENCIA_PAGO
,UAT.FRECUENCIA_PAGO
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.FRECUENCIA_PAGO))!=TRIM(UPPER(UAT.FRECUENCIA_PAGO)) THEN 1 ELSE 0 END )=1
