SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.HASH_DIFF
,UAT.HASH_DIFF
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.HASH_DIFF))!=TRIM(UPPER(UAT.HASH_DIFF)) THEN 1 ELSE 0 END )=1
