SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.MEDIO_COMUNICACION
,UAT.MEDIO_COMUNICACION
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.MEDIO_COMUNICACION))!=TRIM(UPPER(UAT.MEDIO_COMUNICACION)) THEN 1 ELSE 0 END )=1
