SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.TIPO_RENTA
,UAT.TIPO_RENTA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.TIPO_RENTA))!=TRIM(UPPER(UAT.TIPO_RENTA)) THEN 1 ELSE 0 END )=1
