SELECT 
'ENDOSAR' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,OBJETODELENDOSOINPUT
,OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,PRODUCTDESGINDINPUT
,PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,TIPOENDOSODESGINDINPUT
,TIPOENDOSODESGINDVALUE
,TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSAR
UNION ALL 
SELECT 
'ENDOSARACC' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,ENDOSOSIMPLEACCINPUT
,ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,INICIOVIGENCIAENDACCINPUT
,INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,TIPOVIGENCIAENDACCINPUT
,TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARACC
UNION ALL 
SELECT 
'ENDOSARAPLAZADO' AS ESTADO 
,APLAZARENDOSOINPUT
,APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,FECHAFINAPLAZOENDOSOINPUT
,FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,MESESAPLAZOPROPINPUT
,MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARAPLAZADO
UNION ALL 
SELECT 
'ENDOSARDESISTIDO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,DESISTIRENDOSOINPUT
,DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,MOTIVODESISTIRENDOSOINPUT
,MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARDESISTIDO
UNION ALL 
SELECT 
'ENDOSARFLEX' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,ENDOSOSCOMPLEJOSOPFLEXINPUT
,ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,ENDOSOSSIMPLESSACFLEXINPUT
,ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,PLANVIDAINPUT
,PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARFLEX
UNION ALL 
SELECT 
'ENDOSARINSPECCIONVEH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARINSPECCIONVEH
UNION ALL 
SELECT 
'ENDOSARND' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,TIPOENDOSONDINPUT
,TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARND
UNION ALL 
SELECT 
'ENDOSARPROPRAPIDA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPRAPIDA
UNION ALL 
SELECT 
'ENDOSARPROPUESTA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,TIPOENDOSOPROPUESTAINPUT
,TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPUESTA
UNION ALL 
SELECT 
'ENDOSARRECHAZADO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,MOTIVORECHAZARENDOSOINPUT
,MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,RECHAZARENDOSOINPUT
,RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARRECHAZADO
UNION ALL 
SELECT 
'ENDOSARRH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,TIPOENDOSORHINPUT
,TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARRH
UNION ALL 
SELECT 
'ENDOSARSALPROSURA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSSALPROSURAINPUT
,ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARSALPROSURA
UNION ALL 
SELECT 
'ENDOSARSURA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,ENDOSOSCOMPLEJOSOPSURAINPUT
,ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,ENDOSOSSIMPLESSACSURAINPUT
,ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARSURA
UNION ALL 
SELECT 
'ENDOSARVCASH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,ENDOSOSSIMPLESSACVCASHINPUT
,ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVCASH
UNION ALL 
SELECT 
'ENDOSARVEH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,ENDOSOSVEHINPUT
,ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVEH
UNION ALL 
SELECT 
'ENDOSARVF' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,ENDOSOSCOMPLEJOSOPVFINPUT
,ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,ENDOSOSSIMPLESSACVFINPUT
,ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVF
UNION ALL 
SELECT 
'ENDOSARVIDA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,FECHAFINDIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVIDA
UNION ALL 
SELECT 
'ENDOSARVLC' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,ENDOSOSSIMPLESSACVLCINPUT
,ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVLC
UNION ALL 
SELECT 
'ENDOSARVP' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,ENDOSOSCOMACCINPUT
,ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,ENDOSOSSIMPLEACCINPUT
,ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVP
UNION ALL 
SELECT 
'ENDOSOCAMBIOFONDOFLEX' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSOCAMBIOFONDOFLEX
UNION ALL 
SELECT 
'EXCLUIRCOBENDOSO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.EXCLUIRCOBENDOSO
UNION ALL 
