SELECT 
'DERIVARCOMERCIAL' AS ESTADO 
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,MOTIVODERIVARPROPINPUT
,MOTIVODERIVARPROPVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,PK
,STATIC
,STATUS
FROM INTERSEGURO.DERIVARCOMERCIAL
UNION ALL 
SELECT 
'RECIBIRDOCUMENTO' AS ESTADO 
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS MOTIVODERIVARPROPINPUT
,NULL AS MOTIVODERIVARPROPVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PK
,STATIC
,STATUS
FROM INTERSEGURO.RECIBIRDOCUMENTO
UNION ALL 
