SELECT SUM(CASE WHEN TRIM(UPPER(PROD.DESCRIPTION)) IS NULL AND TRIM(UPPER(UAT.DESCRIPTION))="" THEN 1 ELSE 0 END) AS DIFF_DESCRIPTION
,SUM(CASE WHEN TRIM(UPPER(PROD.EVENT)) IS NULL AND TRIM(UPPER(UAT.EVENT))="" THEN 1 ELSE 0 END) AS DIFF_EVENT
FROM iter-data-storage-pv-uat.acsele_data.COVERAGEDCO_raw UAT 
INNER JOIN interseguro-data.acsele_data.COVERAGEDCO_raw PROD 
ON UAT.OPERATIONPK = PROD.OPERATIONPK 
AND UAT.AGREGATEDOBJECTID = PROD.AGREGATEDOBJECTID