SELECT SUM(CASE WHEN TRIM(UPPER(PROD.EDADINPUT)) IS NULL AND TRIM(UPPER(UAT.EDADINPUT))="" THEN 1 ELSE 0 END) AS DIFF_EDADINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADVALUE)) IS NULL AND TRIM(UPPER(UAT.EDADVALUE))="" THEN 1 ELSE 0 END) AS DIFF_EDADVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECSOBREPRIMAINPUT)) IS NULL AND TRIM(UPPER(UAT.OARECSOBREPRIMAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OARECSOBREPRIMAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECSOBREPRIMAVALUE)) IS NULL AND TRIM(UPPER(UAT.OARECSOBREPRIMAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OARECSOBREPRIMAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOSOBREPRIMAVALUE)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOSOBREPRIMAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOSOBREPRIMAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECEXTRAPRIMAINPUT)) IS NULL AND TRIM(UPPER(UAT.OARECEXTRAPRIMAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OARECEXTRAPRIMAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECEXTRAPRIMAVALUE)) IS NULL AND TRIM(UPPER(UAT.OARECEXTRAPRIMAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OARECEXTRAPRIMAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOEXTRAPRIMAVALUE)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOEXTRAPRIMAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOEXTRAPRIMAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECSOBREPRIMACONYINPUT)) IS NULL AND TRIM(UPPER(UAT.OARECSOBREPRIMACONYINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OARECSOBREPRIMACONYINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECSOBREPRIMACONYVALUE)) IS NULL AND TRIM(UPPER(UAT.OARECSOBREPRIMACONYVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OARECSOBREPRIMACONYVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOSOBREPRIMACONVALUE)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOSOBREPRIMACONVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOSOBREPRIMACONVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECEXTRAPRIMACONYINPUT)) IS NULL AND TRIM(UPPER(UAT.OARECEXTRAPRIMACONYINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OARECEXTRAPRIMACONYINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OARECEXTRAPRIMACONYVALUE)) IS NULL AND TRIM(UPPER(UAT.OARECEXTRAPRIMACONYVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OARECEXTRAPRIMACONYVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOEXTRAPRIMACONVALUE)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOEXTRAPRIMACONVALUE))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOEXTRAPRIMACONVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOEXTRAPRIMACONINPUT)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOEXTRAPRIMACONINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOEXTRAPRIMACONINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOSOBREPRIMACONINPUT)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOSOBREPRIMACONINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOSOBREPRIMACONINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOEXTRAPRIMAINPUT)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOEXTRAPRIMAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOEXTRAPRIMAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.OAMOTIVOSOBREPRIMAINPUT)) IS NULL AND TRIM(UPPER(UAT.OAMOTIVOSOBREPRIMAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_OAMOTIVOSOBREPRIMAINPUT
FROM iter-data-storage-pv-uat.acsele_data.OADESGVEHICULAR_raw UAT 
INNER JOIN interseguro-data.acsele_data.OADESGVEHICULAR_raw PROD 
ON UAT.PK = PROD.PK