SELECT SUM(CASE WHEN TRIM(UPPER(PROD.PK)) IS NULL AND TRIM(UPPER(UAT.PK))="" THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN TRIM(UPPER(PROD.STATIC)) IS NULL AND TRIM(UPPER(UAT.STATIC))="" THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS)) IS NULL AND TRIM(UPPER(UAT.STATUS))="" THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADINPUT)) IS NULL AND TRIM(UPPER(UAT.EDADINPUT))="" THEN 1 ELSE 0 END) AS DIFF_EDADINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADVALUE)) IS NULL AND TRIM(UPPER(UAT.EDADVALUE))="" THEN 1 ELSE 0 END) AS DIFF_EDADVALUE
FROM iter-data-storage-pv-uat.acsele_data.OAPROTECCIONFAMILIAR_raw UAT 
INNER JOIN interseguro-data.acsele_data.OAPROTECCIONFAMILIAR_raw PROD 
ON UAT.PK = PROD.PK