SELECT SUM(CASE WHEN TRIM(UPPER(PROD.TIPOCLIENTEINPUT)) IS NULL AND TRIM(UPPER(UAT.TIPOCLIENTEINPUT))="" THEN 1 ELSE 0 END) AS DIFF_TIPOCLIENTEINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPOCLIENTEVALUE)) IS NULL AND TRIM(UPPER(UAT.TIPOCLIENTEVALUE))="" THEN 1 ELSE 0 END) AS DIFF_TIPOCLIENTEVALUE
FROM iter-data-storage-pv-uat.acsele_data.OASCTR_raw UAT 
INNER JOIN interseguro-data.acsele_data.OASCTR_raw PROD 
ON UAT.PK = PROD.PK