SELECT SUM(CASE WHEN TRIM(UPPER(PROD.AMOUNT)) IS NULL AND TRIM(UPPER(UAT.AMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_AMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.BALANCE)) IS NULL AND TRIM(UPPER(UAT.BALANCE))="" THEN 1 ELSE 0 END) AS DIFF_BALANCE
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS)) IS NULL AND TRIM(UPPER(UAT.STATUS))="" THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.OPM_SUBSTATUS)) IS NULL AND TRIM(UPPER(UAT.OPM_SUBSTATUS))="" THEN 1 ELSE 0 END) AS DIFF_OPM_SUBSTATUS
FROM iter-data-storage-pv-uat.acsele_data.OPENITEM_raw UAT 
INNER JOIN interseguro-data.acsele_data.OPENITEM_raw PROD 
ON UAT.OPENITEMID = PROD.OPENITEMID