SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NOMBREASEGURADOINPUT)) IS NULL AND TRIM(UPPER(UAT.NOMBREASEGURADOINPUT))="" THEN 1 ELSE 0 END) AS DIFF_NOMBREASEGURADOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBREASEGURADOVALUE)) IS NULL AND TRIM(UPPER(UAT.NOMBREASEGURADOVALUE))="" THEN 1 ELSE 0 END) AS DIFF_NOMBREASEGURADOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTINPUT)) IS NULL AND TRIM(UPPER(UAT.FECHANACIMIENTOASISTINPUT))="" THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTVALUE)) IS NULL AND TRIM(UPPER(UAT.FECHANACIMIENTOASISTVALUE))="" THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAINPUT)) IS NULL AND TRIM(UPPER(UAT.FECHAVENTAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAVALUE)) IS NULL AND TRIM(UPPER(UAT.FECHAVENTAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAACTIVACIONTCINPUT)) IS NULL AND TRIM(UPPER(UAT.FECHAACTIVACIONTCINPUT))="" THEN 1 ELSE 0 END) AS DIFF_FECHAACTIVACIONTCINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAACTIVACIONTCVALUE)) IS NULL AND TRIM(UPPER(UAT.FECHAACTIVACIONTCVALUE))="" THEN 1 ELSE 0 END) AS DIFF_FECHAACTIVACIONTCVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CODINTERMEDIARIOINPUT)) IS NULL AND TRIM(UPPER(UAT.CODINTERMEDIARIOINPUT))="" THEN 1 ELSE 0 END) AS DIFF_CODINTERMEDIARIOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CODINTERMEDIARIOVALUE)) IS NULL AND TRIM(UPPER(UAT.CODINTERMEDIARIOVALUE))="" THEN 1 ELSE 0 END) AS DIFF_CODINTERMEDIARIOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITINPUT)) IS NULL AND TRIM(UPPER(UAT.PROVEEDORDIGITINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITVALUE)) IS NULL AND TRIM(UPPER(UAT.PROVEEDORDIGITVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANCLONACIONOFRAUDEDINPUT)) IS NULL AND TRIM(UPPER(UAT.PLANCLONACIONOFRAUDEDINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PLANCLONACIONOFRAUDEDINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANCLONACIONOFRAUDEDVALUE)) IS NULL AND TRIM(UPPER(UAT.PLANCLONACIONOFRAUDEDVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PLANCLONACIONOFRAUDEDVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.MTOSINIESTROCLONACIONINPUT)) IS NULL AND TRIM(UPPER(UAT.MTOSINIESTROCLONACIONINPUT))="" THEN 1 ELSE 0 END) AS DIFF_MTOSINIESTROCLONACIONINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.MTOSINIESTROCLONACIONVALUE)) IS NULL AND TRIM(UPPER(UAT.MTOSINIESTROCLONACIONVALUE))="" THEN 1 ELSE 0 END) AS DIFF_MTOSINIESTROCLONACIONVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGINPUT)) IS NULL AND TRIM(UPPER(UAT.NIVELAGRUPREASEGINPUT))="" THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGVALUE)) IS NULL AND TRIM(UPPER(UAT.NIVELAGRUPREASEGVALUE))="" THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASININPUT)) IS NULL AND TRIM(UPPER(UAT.SIMBOLOMONEDASININPUT))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASININPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASINVALUE)) IS NULL AND TRIM(UPPER(UAT.SIMBOLOMONEDASINVALUE))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASINVALUE
FROM iter-data-storage-pv-uat.acsele_data.POLCLONACIONOFRAUDED_raw UAT 
INNER JOIN interseguro-data.acsele_data.POLCLONACIONOFRAUDED_raw PROD 
ON UAT.PK = PROD.PK