SELECT SUM(CASE WHEN TRIM(UPPER(PROD.COVI_INVOICE)) IS NULL AND TRIM(UPPER(UAT.COVI_INVOICE))="" THEN 1 ELSE 0 END) AS DIFF_COVI_INVOICE
FROM iter-data-storage-pv-uat.acsele_data.STCL_COVERAGEINVOICE_raw UAT 
INNER JOIN interseguro-data.acsele_data.STCL_COVERAGEINVOICE_raw PROD 
ON UAT.COVI_INVOICE = PROD.COVI_INVOICE