SELECT SUM(CASE WHEN TRIM(UPPER(PROD.FMP_DESCPROPERTY)) IS NULL AND TRIM(UPPER(UAT.FMP_DESCPROPERTY))="" THEN 1 ELSE 0 END) AS DIFF_FMP_DESCPROPERTY
,SUM(CASE WHEN TRIM(UPPER(PROD.FMP_CONCEPT)) IS NULL AND TRIM(UPPER(UAT.FMP_CONCEPT))="" THEN 1 ELSE 0 END) AS DIFF_FMP_CONCEPT
,SUM(CASE WHEN TRIM(UPPER(PROD.FMP_AMOUNT)) IS NULL AND TRIM(UPPER(UAT.FMP_AMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_FMP_AMOUNT
FROM iter-data-storage-pv-uat.acsele_data.STLI_FUNDMOVEMENTPOLICY_raw UAT 
INNER JOIN interseguro-data.acsele_data.STLI_FUNDMOVEMENTPOLICY_raw PROD 
ON UAT.FMP_ID = PROD.FMP_ID