SELECT SUM(CASE WHEN TRIM(UPPER(PROD.PAYMENTMODETEMPLATENAME)) IS NULL AND TRIM(UPPER(UAT.PAYMENTMODETEMPLATENAME))="" THEN 1 ELSE 0 END) AS DIFF_PAYMENTMODETEMPLATENAME
,SUM(CASE WHEN TRIM(UPPER(PROD.FIRSTPAYMENTMODETEMPLATE)) IS NULL AND TRIM(UPPER(UAT.FIRSTPAYMENTMODETEMPLATE))="" THEN 1 ELSE 0 END) AS DIFF_FIRSTPAYMENTMODETEMPLATE
FROM iter-data-storage-pv-uat.acsele_data.STPO_POLICYPARTICIPATIONDCO_raw UAT 
INNER JOIN interseguro-data.acsele_data.STPO_POLICYPARTICIPATIONDCO_raw PROD 
ON UAT.AGREGATEDOBJECTID = PROD.AGREGATEDOBJECTID 
AND UAT.OPERATIONPK = PROD.OPERATIONPK