SELECT SUM(CASE WHEN TRIM(UPPER(PROD.WQUO_RESTRICTIVEDATE)) IS NULL AND TRIM(UPPER(UAT.WQUO_RESTRICTIVEDATE))="" THEN 1 ELSE 0 END) AS DIFF_WQUO_RESTRICTIVEDATE
,SUM(CASE WHEN TRIM(UPPER(PROD.EVENT_NAME)) IS NULL AND TRIM(UPPER(UAT.EVENT_NAME))="" THEN 1 ELSE 0 END) AS DIFF_EVENT_NAME
FROM iter-data-storage-pv-uat.acsele_data.STPO_WILDCARDQUOTA_raw UAT 
INNER JOIN interseguro-data.acsele_data.STPO_WILDCARDQUOTA_raw PROD 
ON UAT.WQUO_ID = PROD.WQUO_ID