SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.NUMERO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBRE_PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.NOMBRE_PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_NOMBRE_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_SINIESTRO)) IS NULL AND TRIM(UPPER(UAT.NUMERO_SINIESTRO))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_SINIESTRO
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_RESERVA_SINIESTRO)) IS NULL AND TRIM(UPPER(UAT.ESTADO_RESERVA_SINIESTRO))="" THEN 1 ELSE 0 END) AS DIFF_ESTADO_RESERVA_SINIESTRO
,SUM(CASE WHEN TRIM(UPPER(PROD.COBERTURA)) IS NULL AND TRIM(UPPER(UAT.COBERTURA))="" THEN 1 ELSE 0 END) AS DIFF_COBERTURA
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_DOCUMENTO)) IS NULL AND TRIM(UPPER(UAT.TIPO_DOCUMENTO))="" THEN 1 ELSE 0 END) AS DIFF_TIPO_DOCUMENTO
,SUM(CASE WHEN TRIM(UPPER(PROD.MONEDA_PAGO)) IS NULL AND TRIM(UPPER(UAT.MONEDA_PAGO))="" THEN 1 ELSE 0 END) AS DIFF_MONEDA_PAGO
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTO_RESERVA)) IS NULL AND TRIM(UPPER(UAT.MONTO_RESERVA))="" THEN 1 ELSE 0 END) AS DIFF_MONTO_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_TRANSACCION_RESERVA)) IS NULL AND TRIM(UPPER(UAT.TIPO_TRANSACCION_RESERVA))="" THEN 1 ELSE 0 END) AS DIFF_TIPO_TRANSACCION_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.MOTIVO_RESERVA)) IS NULL AND TRIM(UPPER(UAT.MOTIVO_RESERVA))="" THEN 1 ELSE 0 END) AS DIFF_MOTIVO_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.COBERTURA_RESERVA)) IS NULL AND TRIM(UPPER(UAT.COBERTURA_RESERVA))="" THEN 1 ELSE 0 END) AS DIFF_COBERTURA_RESERVA
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_SINIESTRO_RESERVA_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_SINIESTRO_RESERVA_raw PROD 
ON UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION 
AND UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA