SELECT SUM(CASE WHEN TRIM(UPPER(PROD.THIRDPARTY)) IS NULL AND TRIM(UPPER(UAT.THIRDPARTY))="" THEN 1 ELSE 0 END) AS DIFF_THIRDPARTY
,SUM(CASE WHEN TRIM(UPPER(PROD.DESCPROPERTY)) IS NULL AND TRIM(UPPER(UAT.DESCPROPERTY))="" THEN 1 ELSE 0 END) AS DIFF_DESCPROPERTY
,SUM(CASE WHEN TRIM(UPPER(PROD.CONCEPT)) IS NULL AND TRIM(UPPER(UAT.CONCEPT))="" THEN 1 ELSE 0 END) AS DIFF_CONCEPT
,SUM(CASE WHEN TRIM(UPPER(PROD.AMMOUNT)) IS NULL AND TRIM(UPPER(UAT.AMMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_AMMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.PGC_CATEGORY)) IS NULL AND TRIM(UPPER(UAT.PGC_CATEGORY))="" THEN 1 ELSE 0 END) AS DIFF_PGC_CATEGORY
FROM iter-data-storage-pv-uat.acsele_data.THIRDPARTYMOVEMENTPOLICY_raw UAT 
INNER JOIN interseguro-data.acsele_data.THIRDPARTYMOVEMENTPOLICY_raw PROD 
ON UAT.PK = PROD.PK