SELECT SUM(CASE WHEN TRIM(UPPER(PROD.PRODUCTOSVIDAINPUT)) IS NULL AND TRIM(UPPER(UAT.PRODUCTOSVIDAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PRODUCTOSVIDAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PRODUCTOSVIDAVALUE)) IS NULL AND TRIM(UPPER(UAT.PRODUCTOSVIDAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PRODUCTOSVIDAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOPAGOPRIMAINPUT)) IS NULL AND TRIM(UPPER(UAT.PERIODOPAGOPRIMAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PERIODOPAGOPRIMAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOPAGOPRIMAVALUE)) IS NULL AND TRIM(UPPER(UAT.PERIODOPAGOPRIMAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PERIODOPAGOPRIMAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGANTACCINPUT)) IS NULL AND TRIM(UPPER(UAT.CAPITALASEGANTACCINPUT))="" THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGANTACCINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGANTACCVALUE)) IS NULL AND TRIM(UPPER(UAT.CAPITALASEGANTACCVALUE))="" THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGANTACCVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGURADOACCINPUT)) IS NULL AND TRIM(UPPER(UAT.CAPITALASEGURADOACCINPUT))="" THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGURADOACCINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGURADOACCVALUE)) IS NULL AND TRIM(UPPER(UAT.CAPITALASEGURADOACCVALUE))="" THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGURADOACCVALUE
FROM iter-data-storage-pv-uat.acsele_data.URVIDATOTALPROTEGIDA_raw UAT 
INNER JOIN interseguro-data.acsele_data.URVIDATOTALPROTEGIDA_raw PROD 
ON UAT.PK = PROD.PK