SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.NUMERO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTO_INICIAL)) IS NULL AND TRIM(UPPER(UAT.MONTO_INICIAL))="" THEN 1 ELSE 0 END) AS DIFF_MONTO_INICIAL
,SUM(CASE WHEN TRIM(UPPER(PROD.AMORTIZACIONPENDIENTE)) IS NULL AND TRIM(UPPER(UAT.AMORTIZACIONPENDIENTE))="" THEN 1 ELSE 0 END) AS DIFF_AMORTIZACIONPENDIENTE
,SUM(CASE WHEN TRIM(UPPER(PROD.INTERESPENDIENTE)) IS NULL AND TRIM(UPPER(UAT.INTERESPENDIENTE))="" THEN 1 ELSE 0 END) AS DIFF_INTERESPENDIENTE
,SUM(CASE WHEN TRIM(UPPER(PROD.TOTALPENDIENTE)) IS NULL AND TRIM(UPPER(UAT.TOTALPENDIENTE))="" THEN 1 ELSE 0 END) AS DIFF_TOTALPENDIENTE