SELECT SUM(CASE WHEN TRIM(UPPER(PROD.CONTRATANTE))!=TRIM(UPPER(UAT.CONTRATANTE)) THEN 1 ELSE 0 END) AS DIFF_CONTRATANTE
,SUM(CASE WHEN TRIM(UPPER(PROD.DIRECCION))!=TRIM(UPPER(UAT.DIRECCION)) THEN 1 ELSE 0 END) AS DIFF_DIRECCION
,SUM(CASE WHEN TRIM(UPPER(PROD.NRO_POLIZA_SOAT))!=TRIM(UPPER(UAT.NRO_POLIZA_SOAT)) THEN 1 ELSE 0 END) AS DIFF_NRO_POLIZA_SOAT
,SUM(CASE WHEN PROD.FECHAINICIOVIGENCIA!=UAT.FECHAINICIOVIGENCIA THEN 1 ELSE 0 END) AS DIFF_FECHAINICIOVIGENCIA
,SUM(CASE WHEN TRIM(UPPER(PROD.PLACA))!=TRIM(UPPER(UAT.PLACA)) THEN 1 ELSE 0 END) AS DIFF_PLACA
,SUM(CASE WHEN TRIM(UPPER(PROD.MARCA))!=TRIM(UPPER(UAT.MARCA)) THEN 1 ELSE 0 END) AS DIFF_MARCA
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_SINIESTRO))!=TRIM(UPPER(UAT.NUMERO_SINIESTRO)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_SINIESTRO
,SUM(CASE WHEN PROD.FECHA_OCURRENCIA!=UAT.FECHA_OCURRENCIA THEN 1 ELSE 0 END) AS DIFF_FECHA_OCURRENCIA
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_ACCIDENTE))!=TRIM(UPPER(UAT.TIPO_ACCIDENTE)) THEN 1 ELSE 0 END) AS DIFF_TIPO_ACCIDENTE
,SUM(CASE WHEN TRIM(UPPER(PROD.COBERTURA))!=TRIM(UPPER(UAT.COBERTURA)) THEN 1 ELSE 0 END) AS DIFF_COBERTURA
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTO_RESERVADO))!=TRIM(UPPER(UAT.MONTO_RESERVADO)) THEN 1 ELSE 0 END) AS DIFF_MONTO_RESERVADO
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTO_PAGADO))!=TRIM(UPPER(UAT.MONTO_PAGADO)) THEN 1 ELSE 0 END) AS DIFF_MONTO_PAGADO
,SUM(CASE WHEN TRIM(UPPER(PROD.DNILESIONADO))!=TRIM(UPPER(UAT.DNILESIONADO)) THEN 1 ELSE 0 END) AS DIFF_DNILESIONADO
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBREACCIDENTADO))!=TRIM(UPPER(UAT.NOMBREACCIDENTADO)) THEN 1 ELSE 0 END) AS DIFF_NOMBREACCIDENTADO
,SUM(CASE WHEN TRIM(UPPER(PROD.APELLIDOPATERNOACCIDENTADO))!=TRIM(UPPER(UAT.APELLIDOPATERNOACCIDENTADO)) THEN 1 ELSE 0 END) AS DIFF_APELLIDOPATERNOACCIDENTADO
,SUM(CASE WHEN TRIM(UPPER(PROD.APELLIDOMATERNOACCIDENTADO))!=TRIM(UPPER(UAT.APELLIDOMATERNOACCIDENTADO)) THEN 1 ELSE 0 END) AS DIFF_APELLIDOMATERNOACCIDENTADO
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.ACCIDENTADO_raw UAT 
INNER JOIN interseguro-data.acsele_data.ACCIDENTADO_raw PROD 
ON UAT.PK = PROD.PK