SELECT SUM(CASE WHEN PROD.CURRENCYORIGINID!=UAT.CURRENCYORIGINID THEN 1 ELSE 0 END) AS DIFF_CURRENCYORIGINID
,SUM(CASE WHEN PROD.CURRENCYTARGETID!=UAT.CURRENCYTARGETID THEN 1 ELSE 0 END) AS DIFF_CURRENCYTARGETID
,SUM(CASE WHEN PROD.DATERATE!=UAT.DATERATE THEN 1 ELSE 0 END) AS DIFF_DATERATE
,SUM(CASE WHEN TRIM(UPPER(PROD.RATE))!=TRIM(UPPER(UAT.RATE)) THEN 1 ELSE 0 END) AS DIFF_RATE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.CURRENCYRATE_raw UAT 
INNER JOIN interseguro-data.acsele_data.CURRENCYRATE_raw PROD 
ON UAT.CURRENCYTARGETID = PROD.CURRENCYTARGETID 
AND UAT.DATERATE = PROD.DATERATE 
AND UAT.CURRENCYORIGINID = PROD.CURRENCYORIGINID