SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_SINIESTRO))!=TRIM(UPPER(UAT.NUMERO_SINIESTRO)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_SINIESTRO
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA))!=TRIM(UPPER(UAT.NUMERO_POLIZA)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.LUGAR_SINIESTRO))!=TRIM(UPPER(UAT.LUGAR_SINIESTRO)) THEN 1 ELSE 0 END) AS DIFF_LUGAR_SINIESTRO
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO