SELECT SUM(CASE WHEN PROD.OIH_AUDITDATE!=UAT.OIH_AUDITDATE THEN 1 ELSE 0 END) AS DIFF_OIH_AUDITDATE
,SUM(CASE WHEN PROD.OPENITEMDATE!=UAT.OPENITEMDATE THEN 1 ELSE 0 END) AS DIFF_OPENITEMDATE
,SUM(CASE WHEN PROD.OPENITEMREFERENCEID!=UAT.OPENITEMREFERENCEID THEN 1 ELSE 0 END) AS DIFF_OPENITEMREFERENCEID
,SUM(CASE WHEN PROD.OPENITEMID!=UAT.OPENITEMID THEN 1 ELSE 0 END) AS DIFF_OPENITEMID
,SUM(CASE WHEN PROD.POLICYID!=UAT.POLICYID THEN 1 ELSE 0 END) AS DIFF_POLICYID
,SUM(CASE WHEN PROD.RISKUNITID!=UAT.RISKUNITID THEN 1 ELSE 0 END) AS DIFF_RISKUNITID
,SUM(CASE WHEN PROD.REFERENCE!=UAT.REFERENCE THEN 1 ELSE 0 END) AS DIFF_REFERENCE
,SUM(CASE WHEN PROD.ADDITIONALREFERENCE!=UAT.ADDITIONALREFERENCE THEN 1 ELSE 0 END) AS DIFF_ADDITIONALREFERENCE
,SUM(CASE WHEN TRIM(UPPER(PROD.PAYMENTSEQUENCE))!=TRIM(UPPER(UAT.PAYMENTSEQUENCE)) THEN 1 ELSE 0 END) AS DIFF_PAYMENTSEQUENCE
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_POLICYNUMBER))!=TRIM(UPPER(UAT.OPR_POLICYNUMBER)) THEN 1 ELSE 0 END) AS DIFF_OPR_POLICYNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_RISKUNITNUMBER))!=TRIM(UPPER(UAT.OPR_RISKUNITNUMBER)) THEN 1 ELSE 0 END) AS DIFF_OPR_RISKUNITNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_CLAIMNUMBER))!=TRIM(UPPER(UAT.OPR_CLAIMNUMBER)) THEN 1 ELSE 0 END) AS DIFF_OPR_CLAIMNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_RECOVERYNUMBER))!=TRIM(UPPER(UAT.OPR_RECOVERYNUMBER)) THEN 1 ELSE 0 END) AS DIFF_OPR_RECOVERYNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.PGC_CATEGORY))!=TRIM(UPPER(UAT.PGC_CATEGORY)) THEN 1 ELSE 0 END) AS DIFF_PGC_CATEGORY
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_PRODUCTPK))!=TRIM(UPPER(UAT.OPR_PRODUCTPK)) THEN 1 ELSE 0 END) AS DIFF_OPR_PRODUCTPK
,SUM(CASE WHEN PROD.CIOP_ID!=UAT.CIOP_ID THEN 1 ELSE 0 END) AS DIFF_CIOP_ID
,SUM(CASE WHEN PROD.OPR_COMPONENTID!=UAT.OPR_COMPONENTID THEN 1 ELSE 0 END) AS DIFF_OPR_COMPONENTID
,SUM(CASE WHEN PROD.AGV_ID!=UAT.AGV_ID THEN 1 ELSE 0 END) AS DIFF_AGV_ID
,SUM(CASE WHEN PROD.OPR_RCIN_ID!=UAT.OPR_RCIN_ID THEN 1 ELSE 0 END) AS DIFF_OPR_RCIN_ID
,SUM(CASE WHEN PROD.RCO_ID!=UAT.RCO_ID THEN 1 ELSE 0 END) AS DIFF_RCO_ID
,SUM(CASE WHEN PROD.ROP_ID!=UAT.ROP_ID THEN 1 ELSE 0 END) AS DIFF_ROP_ID
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.OPENITEMREFERENCE_raw UAT 
INNER JOIN interseguro-data.acsele_data.OPENITEMREFERENCE_raw PROD 
ON UAT.OPENITEMREFERENCEID = PROD.OPENITEMREFERENCEID