SELECT SUM(CASE WHEN PROD.OIH_AUDITDATE!=UAT.OIH_AUDITDATE THEN 1 ELSE 0 END) AS DIFF_OIH_AUDITDATE
,SUM(CASE WHEN PROD.OPENITEMID!=UAT.OPENITEMID THEN 1 ELSE 0 END) AS DIFF_OPENITEMID
,SUM(CASE WHEN PROD.THIRDPARTYID!=UAT.THIRDPARTYID THEN 1 ELSE 0 END) AS DIFF_THIRDPARTYID
,SUM(CASE WHEN PROD.DTY_ID!=UAT.DTY_ID THEN 1 ELSE 0 END) AS DIFF_DTY_ID
,SUM(CASE WHEN PROD.OPENITEMDATE!=UAT.OPENITEMDATE THEN 1 ELSE 0 END) AS DIFF_OPENITEMDATE
,SUM(CASE WHEN PROD.DOCDATE!=UAT.DOCDATE THEN 1 ELSE 0 END) AS DIFF_DOCDATE
,SUM(CASE WHEN PROD.DATEUSERECIPENT!=UAT.DATEUSERECIPENT THEN 1 ELSE 0 END) AS DIFF_DATEUSERECIPENT
,SUM(CASE WHEN PROD.DUEDATE!=UAT.DUEDATE THEN 1 ELSE 0 END) AS DIFF_DUEDATE
,SUM(CASE WHEN PROD.APPLIEDTO!=UAT.APPLIEDTO THEN 1 ELSE 0 END) AS DIFF_APPLIEDTO
,SUM(CASE WHEN PROD.PARENTOPENITEMID!=UAT.PARENTOPENITEMID THEN 1 ELSE 0 END) AS DIFF_PARENTOPENITEMID
,SUM(CASE WHEN PROD.CURRENCYID!=UAT.CURRENCYID THEN 1 ELSE 0 END) AS DIFF_CURRENCYID
,SUM(CASE WHEN TRIM(UPPER(PROD.AMOUNT))!=TRIM(UPPER(UAT.AMOUNT)) THEN 1 ELSE 0 END) AS DIFF_AMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.BALANCE))!=TRIM(UPPER(UAT.BALANCE)) THEN 1 ELSE 0 END) AS DIFF_BALANCE
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS))!=TRIM(UPPER(UAT.STATUS)) THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.REFERENCETYPE!=UAT.REFERENCETYPE THEN 1 ELSE 0 END) AS DIFF_REFERENCETYPE
,SUM(CASE WHEN PROD.SAPCURRENCYID!=UAT.SAPCURRENCYID THEN 1 ELSE 0 END) AS DIFF_SAPCURRENCYID
,SUM(CASE WHEN TRIM(UPPER(PROD.OPM_SUBSTATUS))!=TRIM(UPPER(UAT.OPM_SUBSTATUS)) THEN 1 ELSE 0 END) AS DIFF_OPM_SUBSTATUS
,SUM(CASE WHEN PROD.OPM_MASTEROPENITEMID!=UAT.OPM_MASTEROPENITEMID THEN 1 ELSE 0 END) AS DIFF_OPM_MASTEROPENITEMID
,SUM(CASE WHEN PROD.ROL_ID!=UAT.ROL_ID THEN 1 ELSE 0 END) AS DIFF_ROL_ID
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.OPENITEM_raw UAT 
INNER JOIN interseguro-data.acsele_data.OPENITEM_raw PROD 
ON UAT.OPENITEMID = PROD.OPENITEMID