SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANINTELIGOINPUT))!=TRIM(UPPER(UAT.PLANINTELIGOINPUT)) THEN 1 ELSE 0 END) AS DIFF_PLANINTELIGOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANINTELIGOVALUE))!=TRIM(UPPER(UAT.PLANINTELIGOVALUE)) THEN 1 ELSE 0 END) AS DIFF_PLANINTELIGOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGINPUT))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGINPUT)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGVALUE))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGVALUE)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAINPUT))!=TRIM(UPPER(UAT.PRIMACALCULADAINPUT)) THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAVALUE))!=TRIM(UPPER(UAT.PRIMACALCULADAVALUE)) THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAINPUT))!=TRIM(UPPER(UAT.FECHAVENTAINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAVALUE))!=TRIM(UPPER(UAT.FECHAVENTAVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CLASEREASEGUROINPUT))!=TRIM(UPPER(UAT.CLASEREASEGUROINPUT)) THEN 1 ELSE 0 END) AS DIFF_CLASEREASEGUROINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CLASEREASEGUROVALUE))!=TRIM(UPPER(UAT.CLASEREASEGUROVALUE)) THEN 1 ELSE 0 END) AS DIFF_CLASEREASEGUROVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITINPUT))!=TRIM(UPPER(UAT.PROVEEDORDIGITINPUT)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITVALUE))!=TRIM(UPPER(UAT.PROVEEDORDIGITVALUE)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTINPUT))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTVALUE))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.POLINTELIGO_raw UAT 
INNER JOIN interseguro-data.acsele_data.POLINTELIGO_raw PROD 
ON UAT.PK = PROD.PK