SELECT SUM(CASE WHEN PROD.stateid!=UAT.stateid THEN 1 ELSE 0 END) AS DIFF_stateid
,SUM(CASE WHEN PROD.lifecycleid!=UAT.lifecycleid THEN 1 ELSE 0 END) AS DIFF_lifecycleid
,SUM(CASE WHEN PROD.idnodo!=UAT.idnodo THEN 1 ELSE 0 END) AS DIFF_idnodo
,SUM(CASE WHEN TRIM(UPPER(PROD.description))!=TRIM(UPPER(UAT.description)) THEN 1 ELSE 0 END) AS DIFF_description
,SUM(CASE WHEN PROD.width!=UAT.width THEN 1 ELSE 0 END) AS DIFF_width
,SUM(CASE WHEN PROD.height!=UAT.height THEN 1 ELSE 0 END) AS DIFF_height
,SUM(CASE WHEN PROD.x!=UAT.x THEN 1 ELSE 0 END) AS DIFF_x
,SUM(CASE WHEN PROD.y!=UAT.y THEN 1 ELSE 0 END) AS DIFF_y
,SUM(CASE WHEN PROD.status!=UAT.status THEN 1 ELSE 0 END) AS DIFF_status
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.STATE_raw UAT 
INNER JOIN interseguro-data.acsele_data.STATE_raw PROD 
ON UAT.STATEID = PROD.STATEID