SELECT SUM(CASE WHEN TRIM(UPPER(PROD.COVI_INVOICE))!=TRIM(UPPER(UAT.COVI_INVOICE)) THEN 1 ELSE 0 END) AS DIFF_COVI_INVOICE
,SUM(CASE WHEN PROD.COVI_DATE!=UAT.COVI_DATE THEN 1 ELSE 0 END) AS DIFF_COVI_DATE
,SUM(CASE WHEN PROD.TPT_ID!=UAT.TPT_ID THEN 1 ELSE 0 END) AS DIFF_TPT_ID
,SUM(CASE WHEN PROD.DCO_ID!=UAT.DCO_ID THEN 1 ELSE 0 END) AS DIFF_DCO_ID
,SUM(CASE WHEN PROD.CRBF_ID!=UAT.CRBF_ID THEN 1 ELSE 0 END) AS DIFF_CRBF_ID
,SUM(CASE WHEN PROD.COT_ID!=UAT.COT_ID THEN 1 ELSE 0 END) AS DIFF_COT_ID
,SUM(CASE WHEN PROD.POD_ID!=UAT.POD_ID THEN 1 ELSE 0 END) AS DIFF_POD_ID
,SUM(CASE WHEN PROD.DCO_IDTAXES!=UAT.DCO_IDTAXES THEN 1 ELSE 0 END) AS DIFF_DCO_IDTAXES
,SUM(CASE WHEN PROD.COT_IDTAXES!=UAT.COT_IDTAXES THEN 1 ELSE 0 END) AS DIFF_COT_IDTAXES
,SUM(CASE WHEN PROD.COVI_RATE!=UAT.COVI_RATE THEN 1 ELSE 0 END) AS DIFF_COVI_RATE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.STCL_COVERAGEINVOICE_raw UAT 
INNER JOIN interseguro-data.acsele_data.STCL_COVERAGEINVOICE_raw PROD 
ON UAT.COVI_INVOICE = PROD.COVI_INVOICE