SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.AGREGATEDOBJECTID!=UAT.AGREGATEDOBJECTID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDOBJECTID
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.DCOID!=UAT.DCOID THEN 1 ELSE 0 END) AS DIFF_DCOID
,SUM(CASE WHEN TRIM(UPPER(PROD.PAYMENTMODETEMPLATENAME))!=TRIM(UPPER(UAT.PAYMENTMODETEMPLATENAME)) THEN 1 ELSE 0 END) AS DIFF_PAYMENTMODETEMPLATENAME
,SUM(CASE WHEN PROD.PAYMENTMODEDCOPK!=UAT.PAYMENTMODEDCOPK THEN 1 ELSE 0 END) AS DIFF_PAYMENTMODEDCOPK
,SUM(CASE WHEN PROD.ADDRESSBOOKID!=UAT.ADDRESSBOOKID THEN 1 ELSE 0 END) AS DIFF_ADDRESSBOOKID
,SUM(CASE WHEN PROD.ADDRESSBOOKMAILID!=UAT.ADDRESSBOOKMAILID THEN 1 ELSE 0 END) AS DIFF_ADDRESSBOOKMAILID
,SUM(CASE WHEN PROD.TIME_STAMP!=UAT.TIME_STAMP THEN 1 ELSE 0 END) AS DIFF_TIME_STAMP
,SUM(CASE WHEN PROD.AUDITDATE_PPD!=UAT.AUDITDATE_PPD THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_PPD
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN PROD.CNW_ID!=UAT.CNW_ID THEN 1 ELSE 0 END) AS DIFF_CNW_ID
,SUM(CASE WHEN PROD.CTOB_ID!=UAT.CTOB_ID THEN 1 ELSE 0 END) AS DIFF_CTOB_ID
,SUM(CASE WHEN PROD.CTO_ID!=UAT.CTO_ID THEN 1 ELSE 0 END) AS DIFF_CTO_ID
,SUM(CASE WHEN TRIM(UPPER(PROD.FIRSTPAYMENTMODETEMPLATE))!=TRIM(UPPER(UAT.FIRSTPAYMENTMODETEMPLATE)) THEN 1 ELSE 0 END) AS DIFF_FIRSTPAYMENTMODETEMPLATE
,SUM(CASE WHEN PROD.FIRSTPAYMENTMODEDCOK!=UAT.FIRSTPAYMENTMODEDCOK THEN 1 ELSE 0 END) AS DIFF_FIRSTPAYMENTMODEDCOK
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.STPO_POLICYPARTICIPATIONDCO_raw UAT 
INNER JOIN interseguro-data.acsele_data.STPO_POLICYPARTICIPATIONDCO_raw PROD 
ON UAT.AGREGATEDOBJECTID = PROD.AGREGATEDOBJECTID 
AND UAT.OPERATIONPK = PROD.OPERATIONPK