SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA))!=TRIM(UPPER(UAT.NUMERO_POLIZA)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN PROD.NUMERO_OPERACION!=UAT.NUMERO_OPERACION THEN 1 ELSE 0 END) AS DIFF_NUMERO_OPERACION
,SUM(CASE WHEN TRIM(UPPER(PROD.AUDITDATE_SYSTEM_DATE))!=TRIM(UPPER(UAT.AUDITDATE_SYSTEM_DATE)) THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_SYSTEM_DATE
,SUM(CASE WHEN TRIM(UPPER(PROD.OPERATION_DATETIME))!=TRIM(UPPER(UAT.OPERATION_DATETIME)) THEN 1 ELSE 0 END) AS DIFF_OPERATION_DATETIME
,SUM(CASE WHEN PROD.ID_PRODUCTO!=UAT.ID_PRODUCTO THEN 1 ELSE 0 END) AS DIFF_ID_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBRE_PRODUCTO))!=TRIM(UPPER(UAT.NOMBRE_PRODUCTO)) THEN 1 ELSE 0 END) AS DIFF_NOMBRE_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS_OPERATION))!=TRIM(UPPER(UAT.STATUS_OPERATION)) THEN 1 ELSE 0 END) AS DIFF_STATUS_OPERATION
,SUM(CASE WHEN PROD.THIRDPARTYID!=UAT.THIRDPARTYID THEN 1 ELSE 0 END) AS DIFF_THIRDPARTYID
,SUM(CASE WHEN PROD.ROL_ID!=UAT.ROL_ID THEN 1 ELSE 0 END) AS DIFF_ROL_ID
,SUM(CASE WHEN TRIM(UPPER(PROD.DESCRIPTION))!=TRIM(UPPER(UAT.DESCRIPTION)) THEN 1 ELSE 0 END) AS DIFF_DESCRIPTION
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_POLIZA))!=TRIM(UPPER(UAT.ESTADO_POLIZA)) THEN 1 ELSE 0 END) AS DIFF_ESTADO_POLIZA
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_CONTRATANTE_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_CONTRATANTE_raw PROD 
ON UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA 
AND UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION