SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA))!=TRIM(UPPER(UAT.NUMERO_POLIZA)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN PROD.NUMERO_OPERACION!=UAT.NUMERO_OPERACION THEN 1 ELSE 0 END) AS DIFF_NUMERO_OPERACION
,SUM(CASE WHEN PROD.AUDITDATE_SYSTEM_DATE!=UAT.AUDITDATE_SYSTEM_DATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_SYSTEM_DATE
,SUM(CASE WHEN PROD.ID_PRODUCTO!=UAT.ID_PRODUCTO THEN 1 ELSE 0 END) AS DIFF_ID_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBRE_PRODUCTO))!=TRIM(UPPER(UAT.NOMBRE_PRODUCTO)) THEN 1 ELSE 0 END) AS DIFF_NOMBRE_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_SINIESTRO))!=TRIM(UPPER(UAT.NUMERO_SINIESTRO)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_SINIESTRO
,SUM(CASE WHEN PROD.FECHA_SINIESTRO!=UAT.FECHA_SINIESTRO THEN 1 ELSE 0 END) AS DIFF_FECHA_SINIESTRO
,SUM(CASE WHEN PROD.FECHA_CREACION_SINIESTRO!=UAT.FECHA_CREACION_SINIESTRO THEN 1 ELSE 0 END) AS DIFF_FECHA_CREACION_SINIESTRO
,SUM(CASE WHEN PROD.ID_SINIESTRO!=UAT.ID_SINIESTRO THEN 1 ELSE 0 END) AS DIFF_ID_SINIESTRO
,SUM(CASE WHEN PROD.ID_ESTADO_RESERVA_SINIESTRO!=UAT.ID_ESTADO_RESERVA_SINIESTRO THEN 1 ELSE 0 END) AS DIFF_ID_ESTADO_RESERVA_SINIESTRO
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_RESERVA_SINIESTRO))!=TRIM(UPPER(UAT.ESTADO_RESERVA_SINIESTRO)) THEN 1 ELSE 0 END) AS DIFF_ESTADO_RESERVA_SINIESTRO
,SUM(CASE WHEN TRIM(UPPER(PROD.COBERTURA))!=TRIM(UPPER(UAT.COBERTURA)) THEN 1 ELSE 0 END) AS DIFF_COBERTURA
,SUM(CASE WHEN PROD.FECHA_RECLAMO_RESERVA_NORMAL!=UAT.FECHA_RECLAMO_RESERVA_NORMAL THEN 1 ELSE 0 END) AS DIFF_FECHA_RECLAMO_RESERVA_NORMAL
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_DOCUMENTO))!=TRIM(UPPER(UAT.TIPO_DOCUMENTO)) THEN 1 ELSE 0 END) AS DIFF_TIPO_DOCUMENTO
,SUM(CASE WHEN TRIM(UPPER(PROD.MONEDA_PAGO))!=TRIM(UPPER(UAT.MONEDA_PAGO)) THEN 1 ELSE 0 END) AS DIFF_MONEDA_PAGO
,SUM(CASE WHEN PROD.FECHA_TRANSACCION_RESERVA!=UAT.FECHA_TRANSACCION_RESERVA THEN 1 ELSE 0 END) AS DIFF_FECHA_TRANSACCION_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTO_RESERVA))!=TRIM(UPPER(UAT.MONTO_RESERVA)) THEN 1 ELSE 0 END) AS DIFF_MONTO_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_TRANSACCION_RESERVA))!=TRIM(UPPER(UAT.TIPO_TRANSACCION_RESERVA)) THEN 1 ELSE 0 END) AS DIFF_TIPO_TRANSACCION_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.MOTIVO_RESERVA))!=TRIM(UPPER(UAT.MOTIVO_RESERVA)) THEN 1 ELSE 0 END) AS DIFF_MOTIVO_RESERVA
,SUM(CASE WHEN TRIM(UPPER(PROD.COBERTURA_RESERVA))!=TRIM(UPPER(UAT.COBERTURA_RESERVA)) THEN 1 ELSE 0 END) AS DIFF_COBERTURA_RESERVA
,SUM(CASE WHEN PROD.ID_RESERVA!=UAT.ID_RESERVA THEN 1 ELSE 0 END) AS DIFF_ID_RESERVA
,SUM(CASE WHEN PROD.ID_AJUSTE_RESERVA!=UAT.ID_AJUSTE_RESERVA THEN 1 ELSE 0 END) AS DIFF_ID_AJUSTE_RESERVA
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_SINIESTRO_RESERVA_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_SINIESTRO_RESERVA_raw PROD 
ON UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION 
AND UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA