SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA))!=TRIM(UPPER(UAT.NUMERO_POLIZA)) THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN PROD.OPERACION!=UAT.OPERACION THEN 1 ELSE 0 END) AS DIFF_OPERACION
,SUM(CASE WHEN TRIM(UPPER(PROD.AUDITDATE_SYSTEM_DATE))!=TRIM(UPPER(UAT.AUDITDATE_SYSTEM_DATE)) THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_SYSTEM_DATE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHA_OPERACION))!=TRIM(UPPER(UAT.FECHA_OPERACION)) THEN 1 ELSE 0 END) AS DIFF_FECHA_OPERACION
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS_OPERATION))!=TRIM(UPPER(UAT.STATUS_OPERATION)) THEN 1 ELSE 0 END) AS DIFF_STATUS_OPERATION
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOPAGOPRIMAINPUT))!=TRIM(UPPER(UAT.PERIODOPAGOPRIMAINPUT)) THEN 1 ELSE 0 END) AS DIFF_PERIODOPAGOPRIMAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGURADOINPUT))!=TRIM(UPPER(UAT.CAPITALASEGURADOINPUT)) THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGURADOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOPAGOBENEFINPUT))!=TRIM(UPPER(UAT.PERIODOPAGOBENEFINPUT)) THEN 1 ELSE 0 END) AS DIFF_PERIODOPAGOBENEFINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGANTSURAINPUT))!=TRIM(UPPER(UAT.CAPITALASEGANTSURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGANTSURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGCRECANTSURAINPUT))!=TRIM(UPPER(UAT.CAPITALASEGCRECANTSURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGCRECANTSURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CAPITALASEGCRECSURAINPUT))!=TRIM(UPPER(UAT.CAPITALASEGCRECSURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_CAPITALASEGCRECSURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FACTORCRECSURAINPUT))!=TRIM(UPPER(UAT.FACTORCRECSURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_FACTORCRECSURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROANUALIDADESSURAINPUT))!=TRIM(UPPER(UAT.NUMEROANUALIDADESSURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_NUMEROANUALIDADESSURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOCOBERTURASURAINPUT))!=TRIM(UPPER(UAT.PERIODOCOBERTURASURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_PERIODOCOBERTURASURAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PERIODOPAGOPRIMASURAINPUT))!=TRIM(UPPER(UAT.PERIODOPAGOPRIMASURAINPUT)) THEN 1 ELSE 0 END) AS DIFF_PERIODOPAGOPRIMASURAINPUT
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_OPERACION_UNIDAD_RIESGO_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_OPERACION_UNIDAD_RIESGO_raw PROD 
ON UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION 
AND UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA