CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.sp_master_product_poliza_stock_bancaseguro()
BEGIN

CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.master_product.POLIZA_STOCK_BANCASEGURO`
AS
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_EXTRACASH_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_EXTRACASH_raw`)
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_MULTIPROTECCION_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_MULTIPROTECCION_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PACCIDENTES_raw`
WHERE FECHA_DIA =(SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PACCIDENTES_raw`)
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PCREDITOS_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PCREDITOS_raw`)
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PRESTAMOPROTEGIDO_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM  `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PRESTAMOPROTEGIDO_raw`)
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PROTECCION_CREDITO_FULL_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PROTECCION_CREDITO_FULL_raw`)
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PT360_raw`
WHERE FECHA_DIA = ( SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PT360_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTBLINDAJEPLUS_raw`
WHERE FECHA_DIA = ( SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTBLINDAJEPLUS_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTFIT_raw`
WHERE FECHA_DIA = ( SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTBLINDAJEPLUS_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTINDIVIDUAL_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTINDIVIDUAL_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTMIGRACION_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_PTMIGRACION_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_RH_IS_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_RH_IS_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_SEGURO_MULTIPROTECCION_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_SEGURO_MULTIPROTECCION_raw` )
UNION ALL 
SELECT 
 POLIZA AS NUMERO_POLIZA
,IDCERTIFICADO AS ID_CERTIFICADO
,CERTIFICADO AS NUMERO_CERTIFICADO
,NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA
,NOMBRE AS NOMBRE_PRODUCTO
,NUMERODOCUMENTOCONTRATANTE AS NUMERO_DOCUMENTO_CONTRATANTE
,SEXO AS GENERO
,FECHANACIMIENTO AS FECHA_NACIMIENTO
,FECHAVENTA AS FECHA_VENTA
,INICIOVIGENCIA AS FECHA_INICIO_VIGENCIA
,FINVIGENCIA AS FECHA_FIN_VIGENCIA
,PRIMATOTAL AS PRIMA_TOTAL
,PRIMACOBRAR AS PRIMA_COBRAR
,IDMONEDAPRIMA AS ID_MONEDA
,ESTADO
,MEDIOPAGO AS MEDIO_PAGO
,NOMBRE_TIENDA 
,CANAL
,MOTIVOANULACION AS MOTIVO_ANULACION
,FECANULACION AS FECHA_ANULACION
,FECANULACIONSOLICITUD AS FECHA_ANULACION_SOLICITUD
FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_VIVESALUD_raw`
WHERE FECHA_DIA = (SELECT MAX(FECHA_DIA) FROM `iter-data-storage-pv-uat.affinity_data.STOCK_INTERSEGURO_VIVESALUD_raw` )
;

END;