SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.FECHA_ULTIMO_TRASPASO_CP
,UAT.FECHA_ULTIMO_TRASPASO_CP
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.FECHA_ULTIMO_TRASPASO_CP!=UAT.FECHA_ULTIMO_TRASPASO_CP THEN 1 ELSE 0 END )=1
