SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.FLAG_INDICADOR_PRESTAMO
,UAT.FLAG_INDICADOR_PRESTAMO
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.FLAG_INDICADOR_PRESTAMO))!=TRIM(UPPER(UAT.FLAG_INDICADOR_PRESTAMO)) THEN 1 ELSE 0 END )=1
