SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.NOMBRE_COBERTURA
,UAT.NOMBRE_COBERTURA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.NOMBRE_COBERTURA))!=TRIM(UPPER(UAT.NOMBRE_COBERTURA)) THEN 1 ELSE 0 END )=1
