SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.NUMERO_PROPUESTA
,UAT.NUMERO_PROPUESTA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.NUMERO_PROPUESTA))!=TRIM(UPPER(UAT.NUMERO_PROPUESTA)) THEN 1 ELSE 0 END )=1
