SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.PORCENTAJE_CESIONADA
,UAT.PORCENTAJE_CESIONADA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.PORCENTAJE_CESIONADA))!=TRIM(UPPER(UAT.PORCENTAJE_CESIONADA)) THEN 1 ELSE 0 END )=1
