SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.PRIMA_NETA_ANUAL_PEN
,UAT.PRIMA_NETA_ANUAL_PEN
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.PRIMA_NETA_ANUAL_PEN!=UAT.PRIMA_NETA_ANUAL_PEN THEN 1 ELSE 0 END )=1
