SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.TIPO_CAMBIO_HM
,UAT.TIPO_CAMBIO_HM
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN PROD.TIPO_CAMBIO_HM!=UAT.TIPO_CAMBIO_HM THEN 1 ELSE 0 END )=1
