SELECT 
PROD.NUMERO_POLIZA
,PROD.ID_PRODUCTO
,PROD.VIAJE_PASARELA
,UAT.VIAJE_PASARELA
FROM POLIZA_PROD PROD
LEFT JOIN POLIZA_UAT UAT
ON PROD.NUMERO_POLIZA= UAT.NUMERO_POLIZA
AND PROD.ID_PRODUCTO= UAT.ID_PRODUCTO
WHERE (CASE WHEN TRIM(UPPER(PROD.VIAJE_PASARELA))!=TRIM(UPPER(UAT.VIAJE_PASARELA)) THEN 1 ELSE 0 END )=1
