CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.ACCIDENTADO_landing`
(
  CONTRATANTE STRING,
  DIRECCION STRING,
  NRO_POLIZA_SOAT STRING,
  FECHAINICIOVIGENCIA TIMESTAMP,
  PLACA STRING,
  MARCA STRING,
  NUMERO_SINIESTRO STRING,
  FECHA_OCURRENCIA TIMESTAMP,
  TIPO_ACCIDENTE STRING,
  COBERTURA STRING,
  MONTO_RESERVADO STRING,
  MONTO_PAGADO STRING,
  DNILESIONADO STRING,
  NOMBREACCIDENTADO STRING,
  APELLIDOPATERNOACCIDENTADO STRING,
  APELLIDOMATERNOACCIDENTADO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/ACCIDENTADO_landing/*.parquet"]);