CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.AGREGATEDINSURANCEOBJECT_raw`
(
  AUDITDATE TIMESTAMP,
  AGREGATEDINSURANCEOBJECTID NUMERIC,
  AGREGATEDRISKUNITID NUMERIC,
  TYPEID NUMERIC,
  OPERATIONPK NUMERIC,
  TIME_STAMP TIMESTAMP,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/AGREGATEDINSURANCEOBJECT_raw/*.parquet"]);