CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.CLAIMINSURANCEOBJECT_raw`
(
  CLAIMDATE TIMESTAMP,
  CLAIMINSURANCEOBJECTID NUMERIC,
  AGREGATEDINSURANCEOBJECTID NUMERIC,
  CLAIMRISKUNITID NUMERIC,
  DESCRIPTION STRING,
  DAMAGEDCOID NUMERIC,
  DAMAGEDCOTEMPLATE NUMERIC,
  OPERATIONPK NUMERIC,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/CLAIMINSURANCEOBJECT_raw/*.parquet"]);