CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.CONTRATANTEPOL_raw`
(
  OPERATIONPK NUMERIC,
  AUDITDATE STRING,
  STATUS NUMERIC,
  THIRDPARTYID NUMERIC,
  DESCRIPTION STRING,
  ROL_ID NUMERIC,
  TYPEID NUMERIC,
  AGREGATEDPARENTID NUMERIC,
  AGREGATEDOBJECTID NUMERIC,
  NUMERO_POLIZA STRING,
  NUMERO_COTIZACION STRING,
  DCOID NUMERIC,
  ESTADO STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/CONTRATANTEPOL_raw/*.parquet"]);