CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.COVERAGEDCO_raw`
(
  AGREGATEDOBJECTID NUMERIC,
  OPERATIONPK NUMERIC,
  DCOID NUMERIC,
  STATEID NUMERIC,
  INITIALDATE TIMESTAMP,
  FINISHDATE TIMESTAMP,
  TIME_STAMP TIMESTAMP,
  AUDITDATE TIMESTAMP,
  DESCRIPTION STRING,
  EVENT STRING,
  IDDCOEVENT NUMERIC,
  COD_ISINHERITEDEVENT NUMERIC,
  AGREGATEDPARENTID NUMERIC,
  STATUS NUMERIC,
  EVALUATEDCOVERAGEID NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/COVERAGEDCO_raw/*.parquet"]);