CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_PRIMA_MONTO_raw`
(
  POLICYID NUMERIC,
  OPERATIONPK NUMERIC,
  PRIMANETA_VALOR STRING,
  IGV_VALOR STRING,
  DERECHOEMISIONDOC_VALOR STRING,
  PRIMATOTAL_VALOR STRING,
  PRIMANETAANUAL_VALOR STRING,
  IGVDOC_VALOR STRING,
  PRIMATOTALANUAL_VALOR STRING,
  DERECHOEMISION_VALOR STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_PRIMA_MONTO_raw/*.parquet"]);