CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_PORTAFOLIO_CAB_raw`
(
  CODIGO_CAB STRING,
  ARCHIVO STRING,
  FECHA_CARGA TIMESTAMP,
  PERIODO STRING,
  COD_ESTADO STRING,
  USUARIO_CREA STRING,
  FECHA_CREA TIMESTAMP,
  USUARIO_MODIFICA STRING,
  FECHA_MODIFICA TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_PORTAFOLIO_CAB_raw/*.parquet"]);