CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_RENTABILIDAD_DET_raw`
(
  CODIGO_DET STRING,
  CODIGO_CAB STRING,
  PERIODO STRING,
  CODIGO_PROD STRING,
  PRODUCTO STRING,
  TIPO_FONDO STRING,
  RENTABILIDAD_1 NUMERIC,
  RENTABILIDAD_3 NUMERIC,
  RENTABILIDAD_5 NUMERIC,
  RENTABILIDAD_10 NUMERIC,
  RENTABILIDAD_DETALLE STRING,
  USUARIO_CREA STRING,
  FECHA_CREA TIMESTAMP,
  USUARIO_MODIFICA STRING,
  FECHA_MODIFICA TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_RENTABILIDAD_DET_raw/*.parquet"]);