CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_POLIZA_UNI_raw`
(
  FECHA_INI TIMESTAMP,
  FECHA_FIN TIMESTAMP,
  IDPOLIZA NUMERIC,
  IDOPERACION NUMERIC,
  NUMEROPOLIZA STRING,
  MONEDA STRING,
  FECHA_EMISION TIMESTAMP,
  FRECUENCIAPAGO STRING,
  EMAILPOLIZA STRING,
  INICIOVIGENCIA TIMESTAMP,
  IDPRODUCTO NUMERIC,
  PRODUCTO STRING,
  TIME_STAMP TIMESTAMP,
  DCOID NUMERIC,
  PRIMAMINIMA STRING,
  INDENVPOLELECT STRING,
  PLANVIDA STRING,
  PERIODOPAGOPRIMA STRING,
  AGENTE STRING,
  FINISHDATE TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_POLIZA_UNI_raw/*.parquet"]);