CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_POLIZA_TIR_raw`
(
  NUMPOLIZA STRING,
  PERIODO STRING,
  SALDOFINAL_CP NUMERIC,
  SALDOFINAL_CAV NUMERIC,
  TIRMENSUAL_CP NUMERIC,
  TIRMENSUAL_CAV NUMERIC,
  TIRANUAL_CP NUMERIC,
  TIRANUAL_CAV NUMERIC,
  USUARIO_CREA STRING,
  FECHA_CREA TIMESTAMP,
  USUARIO_MODIFICA STRING,
  FECHA_MODIFICA TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_POLIZA_TIR_raw/*.parquet"]);