CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_PORTAFOLIO_DET_raw`
(
  CODIGO_DET STRING,
  CODIGO_CAB STRING,
  PERIODO STRING,
  CODIGO_PROD STRING,
  PRODUCTO STRING,
  FONDO STRING,
  TIPO_FONDO STRING,
  PORTAFOLIO STRING,
  PESO STRING,
  PRECIO STRING,
  USUARIO_CREA STRING,
  FECHA_CREA TIMESTAMP,
  USUARIO_MODIFICA STRING,
  FECHA_MODIFICA TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_PORTAFOLIO_DET_raw/*.parquet"]);