CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_COBERTURA_raw`
(
  NUMEROPOLIZA STRING,
  FECHA_INI TIMESTAMP,
  FECHA_FIN TIMESTAMP,
  IDPOLIZA NUMERIC,
  IDOPERACION NUMERIC,
  COVDESCCOBERTURAINPUT STRING,
  COVSUMAASEGURADA STRING,
  ORDEN STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_COBERTURA_raw/*.parquet"]);