CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_RPT_FLEXRESUMEN_raw`
(
  NUMEROPOLIZA STRING,
  FEC_INICIO_COBERTURA STRING,
  FEC_TERMINO_COBERTURA STRING,
  FEC_PAGO_REAL STRING,
  VAL_ORIGEN_CARGO STRING,
  VAL_ORIGEN_ABONO STRING,
  VAL_PRIMA_MINIMA_PAGADA STRING,
  VAL_PRIMA_VOLUNTARIA_PAGADA STRING,
  VAL_INTERES_PRESTAMO STRING,
  VAL_GASTO_COBRANZA STRING,
  VIA_PAGO NUMERIC,
  TIPO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_RPT_FLEXRESUMEN_raw/*.parquet"]);