CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_CARGOS_raw`
(
  NUM_POLIZA STRING,
  FECHA_INI TIMESTAMP,
  FECHA_FIN TIMESTAMP,
  FEC_INICIO_COBERTURA TIMESTAMP,
  FEC_TERMINO_COBERTURA TIMESTAMP,
  FEC_PAGO_REAL TIMESTAMP,
  VAL_ORIGEN_CARGO STRING,
  VAL_ORIGEN_ABONO STRING,
  VAL_PRIMA_MINIMA_PAGADA STRING,
  VAL_PRIMA_VOLUNTARIA_PAGADA STRING,
  VAL_INTERES_PRESTAMO STRING,
  VAL_GASTO_COBRANZA STRING,
  OPENITEMDATE TIMESTAMP,
  DOCDATE TIMESTAMP,
  ORDEN STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_CARGOS_raw/*.parquet"]);