CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.EXT_FLEX_RPT_PORTAFOLIO_raw`
(
  FECHA_INI TIMESTAMP,
  FECHA_FIN TIMESTAMP,
  NUMEROPOLIZA STRING,
  PERIODO STRING,
  PRODUCTO STRING,
  FONDO STRING,
  TIPO_FONDO STRING,
  PORTAFOLIO STRING,
  PESO STRING,
  PRECIO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/EXT_FLEX_RPT_PORTAFOLIO_raw/*.parquet"]);