CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.INSURANCEOBJECTDCO_raw`
(
  AGREGATEDOBJECTID NUMERIC,
  OPERATIONPK NUMERIC,
  DCOID NUMERIC,
  PLANID NUMERIC,
  DESCRIPTION STRING,
  STATEID NUMERIC,
  INITIALDATE TIMESTAMP,
  FINISHDATE TIMESTAMP,
  TIME_STAMP TIMESTAMP,
  AUDITDATE TIMESTAMP,
  EVENT STRING,
  IDDCOEVENT NUMERIC,
  IOD_ISINHERITEDEVENT NUMERIC,
  AGREGATEDPARENTID NUMERIC,
  STATUS NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/INSURANCEOBJECTDCO_raw/*.parquet"]);