CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.OAACCIDENTEASISTEN_raw`
(
  AUDITDATE TIMESTAMP,
  PK STRING,
  STATIC STRING,
  STATUS STRING,
  EDADASEGINPUT STRING,
  EDADASEGVALUE STRING,
  SEXOASEGINPUT STRING,
  SEXOASEGVALUE STRING,
  OPCIONPLANAOINPUT STRING,
  OPCIONPLANAOVALUE STRING,
  FECHA_PROCESO DATETIME
)
OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/OAACCIDENTEASISTEN_raw/*.parquet"]);