CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.OAPROTBLININDPLUSFUNO_raw`
(
  AUDITDATE TIMESTAMP,
  PK NUMERIC,
  STATIC NUMERIC,
  STATUS NUMERIC,
  EDADINPUT STRING,
  EDADVALUE STRING,
  NUMPLANINTERLOCBINPUT STRING,
  NUMPLANINTERLOCBVALUE STRING,
  FECHANACIMIENTOMASIVOINPUT STRING,
  FECHANACIMIENTOMASIVOVALUE STRING,
  EDADMINIMAASEGMASIVOINPUT STRING,
  EDADMINIMAASEGMASIVOVALUE STRING,
  EDADMAXIMAASEGMASIVOINPUT STRING,
  EDADMAXIMAASEGMASIVOVALUE STRING,
  EDADPERMANASEGMASIVOINPUT STRING,
  EDADPERMANASEGMASIVOVALUE STRING,
  EDADALCAFINPOLMASIVOSINPUT STRING,
  EDADALCAFINPOLMASIVOSVALUE STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/OAPROTBLININDPLUSFUNO_raw/*.parquet"]);