CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.OAPTINDIVIDUALOH_landing`
(
  AUDITDATE TIMESTAMP,
  PK NUMERIC,
  STATIC NUMERIC,
  STATUS NUMERIC,
  EDADINPUT STRING,
  EDADVALUE STRING,
  EDADMINIMAASEGMASIVOINPUT STRING,
  EDADMINIMAASEGMASIVOVALUE STRING,
  EDADMAXIMAASEGMASIVOINPUT STRING,
  EDADMAXIMAASEGMASIVOVALUE STRING,
  EDADPERMANASEGMASIVOINPUT STRING,
  EDADPERMANASEGMASIVOVALUE STRING,
  EDADALCAFINPOLMASIVOSINPUT STRING,
  EDADALCAFINPOLMASIVOSVALUE STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/OAPTINDIVIDUALOH_landing/*.parquet"]);