CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.OATARJETADECREDITO_raw`
(
  AUDITDATE TIMESTAMP,
  PK STRING,
  STATIC STRING,
  STATUS STRING,
  OPCIONPLANINPUT STRING,
  OPCIONPLANVALUE STRING,
  EDADASEGINPUT STRING,
  EDADASEGVALUE STRING,
  TARIFESPMIGRINPUT STRING,
  TARIFESPMIGRVALUE STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/OATARJETADECREDITO_raw/*.parquet"]);