CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.OPENITEM_raw`
(
  OIH_AUDITDATE TIMESTAMP,
  OPENITEMID NUMERIC,
  THIRDPARTYID NUMERIC,
  DTY_ID NUMERIC,
  OPENITEMDATE TIMESTAMP,
  DOCDATE TIMESTAMP,
  DATEUSERECIPENT TIMESTAMP,
  DUEDATE TIMESTAMP,
  APPLIEDTO NUMERIC,
  PARENTOPENITEMID NUMERIC,
  CURRENCYID NUMERIC,
  AMOUNT STRING,
  BALANCE STRING,
  STATUS STRING,
  OPERATIONPK NUMERIC,
  REFERENCETYPE NUMERIC,
  SAPCURRENCYID NUMERIC,
  OPM_SUBSTATUS STRING,
  OPM_MASTEROPENITEMID NUMERIC,
  ROL_ID NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/OPENITEM_raw/*.parquet"]);