CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.PERSONAJURIDICA_raw`
(
  ADT_EVENTDATE TIMESTAMP,
  PK STRING,
  STATIC STRING,
  STATUS STRING,
  RUCINPUT STRING,
  RUCVALUE STRING,
  NOMBRECOMPEMPVALUE STRING,
  FECHACONSTITUCIONINPUT STRING,
  FECHACONSTITUCIONVALUE STRING,
  PAGINAWEBINPUT STRING,
  PAGINAWEBVALUE STRING,
  NOMBRECOMPEMPINPUT STRING,
  FECHA_PROCESO DATETIME,
  ADT_EVENTDATE_YYYYMMDD NUMERIC
)
OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/PERSONAJURIDICA_raw/*.parquet"]);