CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.POLINTELIGO_raw`
(
  AUDITDATE TIMESTAMP,
  PK NUMERIC,
  STATIC NUMERIC,
  STATUS NUMERIC,
  PLANINTELIGOINPUT STRING,
  PLANINTELIGOVALUE STRING,
  NIVELAGRUPREASEGINPUT STRING,
  NIVELAGRUPREASEGVALUE STRING,
  PRIMACALCULADAINPUT STRING,
  PRIMACALCULADAVALUE STRING,
  FECHAVENTAINPUT STRING,
  FECHAVENTAVALUE STRING,
  CLASEREASEGUROINPUT STRING,
  CLASEREASEGUROVALUE STRING,
  PROVEEDORDIGITINPUT STRING,
  PROVEEDORDIGITVALUE STRING,
  FECHANACIMIENTOASISTINPUT STRING,
  FECHANACIMIENTOASISTVALUE STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/POLINTELIGO_raw/*.parquet"]);