CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.POLICYDCO_raw`
(
  DCOID NUMERIC,
  OPERATIONPK NUMERIC,
  AGREGATEDOBJECTID NUMERIC,
  INITIALDATE TIMESTAMP,
  FINISHDATE TIMESTAMP,
  STATEID NUMERIC,
  AUDITDATE TIMESTAMP,
  ESTADO_CARGA NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/POLICYDCO_raw/*.parquet"]);