CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.PREPOLICY_raw`
(
  PK STRING,
  STATIC STRING,
  NUMEROPOLIZAINPUT STRING,
  FECHAEMISIONINPUT STRING,
  VIGENCIAINPUT STRING,
  CANALVENTAINPUT STRING,
  FRECUENCIAPAGOINPUT STRING,
  FECHASUSPCANCELINPUT STRING,
  MONEDAVALUE STRING,
  EMAILENVIOPOLIZAINPUT STRING,
  ESTADO_CARGA NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/PREPOLICY_raw/*.parquet"]);