CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.PRIMA_OPERACION_COBERTURA_raw`
(
  NUMERO_POLIZA STRING,
  OPERATIONPK NUMERIC,
  MONEDA STRING,
  CODIGO_COBERTURA STRING,
  NOMBRE_COBERTURA STRING,
  ID_PRODUCTO NUMERIC,
  COBERTURA_PRIMA_NETA STRING,
  COBERTURA_PRIMA STRING,
  PAGO STRING,
  FRECUENCIA_PAGO STRING,
  FECHA_EMISION STRING,
  AUDITDATE TIMESTAMP,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/PRIMA_OPERACION_COBERTURA_raw/*.parquet"]);