CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.PRODUCT_landing`
(
  PRODUCTID NUMERIC,
  PRODUCTTYPE NUMERIC,
  COTRISKUNITID NUMERIC,
  DESCRIPTION STRING,
  PRO_PUBLISHEDDATE TIMESTAMP,
  PRO_CLOSEDDATE TIMESTAMP,
  PRO_VERSIONID NUMERIC,
  PRO_DCOID NUMERIC,
  PRO_PARENTID NUMERIC,
  PRO_RUHIERARCHYSTATE NUMERIC,
  PRO_HIERARCHYSTATE NUMERIC,
  PRO_ISACTIVE NUMERIC,
  PRO_ISCOMMERCIAL NUMERIC,
  PRO_ISVISIBLE NUMERIC
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/PRODUCT_landing/*.parquet"]);