CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.RISKUNITDCO_raw`
(
  AUDITDATE TIMESTAMP,
  RUD_VALIDITY NUMERIC,
  STATUS NUMERIC,
  AGREGATEDPARENTID NUMERIC,
  RUD_ISINHERITEDEVENT NUMERIC,
  IDDCOEVENT NUMERIC,
  EVENT STRING,
  TIME_STAMP TIMESTAMP,
  FINISHDATE TIMESTAMP,
  INITIALDATE TIMESTAMP,
  STATEID NUMERIC,
  DCOID NUMERIC,
  OPERATIONPK NUMERIC,
  AGREGATEDOBJECTID NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/RISKUNITDCO_raw/*.parquet"]);