CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.STPO_WILDCARDQUOTA_raw`
(
  WQUO_ID NUMERIC,
  WQUO_IDREF NUMERIC,
  APO_ID NUMERIC,
  WQUO_NUMQUOTA NUMERIC,
  WQUO_SCHEDULEDDATE TIMESTAMP,
  WQUO_SCHEDULEDTYPE NUMERIC,
  WQUO_APPLIEDDATE TIMESTAMP,
  WQUO_STATUS NUMERIC,
  WQUO_RESTRICTIVEDATE STRING,
  OPM_ID NUMERIC,
  COR_ID NUMERIC,
  EVENT_NAME STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/STPO_WILDCARDQUOTA_raw/*.parquet"]);