CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.STPO_INSOBJPARTICIPATIONDCO_raw`
(
  AUDITDATE TIMESTAMP,
  FIRSTPAYMENTMODEDCOK NUMERIC,
  FIRSTPAYMENTMODETEMPLATE STRING,
  CNW_ID NUMERIC,
  STATUS NUMERIC,
  TIME_STAMP TIMESTAMP,
  ADDRESSBOOKMAILID NUMERIC,
  ADDRESSBOOKID NUMERIC,
  PAYMENTMODEDCOPK NUMERIC,
  PAYMENTMODETEMPLATENAME STRING,
  DCOID NUMERIC,
  OPERATIONPK NUMERIC,
  AGREGATEDOBJECTID NUMERIC,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/STPO_INSOBJPARTICIPATIONDCO_raw/*.parquet"]);