CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.STPO_INSOBJPARTICIPATION_raw`
(
  AUDITDATE TIMESTAMP,
  AGREGATEDOBJECTID NUMERIC,
  AGREGATEDPARENTID NUMERIC,
  OPERATIONPK NUMERIC,
  TYPEID NUMERIC,
  DESCRIPTION STRING,
  THIRDPARTYID NUMERIC,
  ROL_ID NUMERIC,
  TIME_STAMP TIMESTAMP,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/STPO_INSOBJPARTICIPATION_raw/*.parquet"]);