CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_ESTADO_ENDOSO_raw`
(
  NUMERO_POLIZA STRING,
  NUMERO_OPERACION NUMERIC,
  ID_POLIZA STRING,
  PRODUCTID NUMERIC,
  NOMBRE_PRODUCTO STRING,
  EVENT STRING,
  FECHA_SOLICITUD DATE,
  FECHA_MOVIMIENTO DATE,
  FECHA_EFECTIVA DATE,
  TIPO_ENDOSO STRING,
  USUARIO_SOLICITUD STRING,
  NUMERO_SOLICITUD STRING,
  MOVIMIENTO STRING,
  MESES_DIFERIDOS NUMERIC
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_ESTADO_ENDOSO_raw/*.parquet"]);