CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_ESTADO_ENDOSO_landing`
(
  NUMERO_POLIZA STRING,
  NUMERO_OPERACION NUMERIC,
  ID_POLIZA STRING,
  PRODUCTID NUMERIC,
  NOMBRE_PRODUCTO STRING,
  EVENT STRING,
  FECHA_SOLICITUD STRING,
  FECHA_MOVIMIENTO STRING,
  FECHA_EFECTIVA STRING,
  TIPO_ENDOSO STRING,
  USUARIO_SOLICITUD STRING,
  NUMERO_SOLICITUD STRING,
  MESES_DIFERIDOS STRING,
  MOVIMIENTO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_ESTADO_ENDOSO_landing/*.parquet"]);