CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_ESTADO_RECHAZAR_raw`
(
  NUMERO_POLIZA STRING,
  NUMERO_OPERACION NUMERIC,
  ID_POLIZA STRING,
  PRODUCTID NUMERIC,
  NOMBRE_PRODUCTO STRING,
  EVENT STRING,
  FECHA_MOVIMIENTO DATE,
  MOTIVO_MOVIMIENTO STRING,
  FECHA_RECEPCION DATE,
  MOVIMIENTO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_ESTADO_RECHAZAR_raw/*.parquet"]);