CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_OPENITEM_MAESTRA_raw`
(
  OPENITEMID NUMERIC,
  ID_TIPO_OPENITEM NUMERIC,
  TIPO_OPENITEM STRING,
  FECHA_INICIO_OPENITEM DATE,
  FECHA_DOCUMENTO DATE,
  FECHA_USO_RECIBIDO DATE,
  FECHA_VENCIMIENTO DATE,
  MONTO FLOAT64,
  MONTO_BALANCE FLOAT64,
  ESTADO_OPENITEM STRING,
  MONEDA_ISO STRING,
  ID_PRODUCTO STRING,
  PRODUCTO STRING,
  CANTIDAD_OPENITEM INT64,
  FECHA_CARGA DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_OPENITEM_MAESTRA_raw/*.parquet"]);