CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_POLIZA_COMODIN_raw`
(
  NUMERO_POLIZA STRING,
  ID_POLIZA STRING,
  NOMBRE_PRODUCTO STRING,
  NUMERO_CUOTA INT64,
  TIPO_PROGRAMACION INT64,
  FECHA_APLICADA TIMESTAMP,
  FECHA_PROGRAMADA TIMESTAMP,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_POLIZA_COMODIN_raw/*.parquet"]);