CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_POLIZA_ASEGURADO_raw`
(
  NUMERO_POLIZA STRING,
  NUMERO_OPERACION NUMERIC,
  AUDITDATE_SYSTEM_DATE STRING,
  OPERATION_DATETIME STRING,
  ID_PRODUCTO NUMERIC,
  NOMBRE_PRODUCTO STRING,
  STATUS_OPERATION STRING,
  THIRDPARTYID NUMERIC,
  ROL_ID NUMERIC,
  DESCRIPTION STRING,
  ESTADO_POLIZA STRING,
  FECHA_PROCESO DATETIME,
  ID_ASEGURADO NUMERIC
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_POLIZA_ASEGURADO_raw/*.parquet"]);