CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_PRODUCTO_raw`
(
  ID_PRODUCTO NUMERIC,
  NOMBRE_PRODUCTO STRING,
  RAMO STRING,
  ID_RAMO STRING,
  SUB_RAMO STRING,
  ID_SUBRAMO STRING,
  NOMBRE_PRODUCTO_COD_SBS STRING,
  TIPO_CONTRATO STRING,
  CODIGORAMOSBS STRING,
  RAMOSBS STRING,
  TIPO_OPENITEM STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_PRODUCTO_raw/*.parquet"]);