CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.TD_POLIZA_OPERACION_UNIDAD_RIESGO_raw`
(
  NUMERO_POLIZA STRING,
  OPERACION NUMERIC,
  AUDITDATE_SYSTEM_DATE STRING,
  FECHA_OPERACION STRING,
  STATUS_OPERATION STRING,
  PK NUMERIC,
  STATIC NUMERIC,
  PERIODOPAGOPRIMAINPUT STRING,
  CAPITALASEGURADOINPUT STRING,
  PERIODOPAGOBENEFINPUT STRING,
  CAPITALASEGANTSURAINPUT STRING,
  CAPITALASEGCRECANTSURAINPUT STRING,
  CAPITALASEGCRECSURAINPUT STRING,
  FACTORCRECSURAINPUT STRING,
  NUMEROANUALIDADESSURAINPUT STRING,
  PERIODOCOBERTURASURAINPUT STRING,
  PERIODOPAGOPRIMASURAINPUT STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/TD_POLIZA_OPERACION_UNIDAD_RIESGO_raw/*.parquet"]);