CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.THIRDPARTYMOVEMENTPOLICY_landing`
(
  AUDITDATE TIMESTAMP,
  PK NUMERIC,
  POLICYID NUMERIC,
  OPERATIONPK NUMERIC,
  THIRDPARTY STRING,
  ROL_ID NUMERIC,
  DESCPROPERTY STRING,
  CONCEPT STRING,
  AMMOUNT STRING,
  DATEOPERATION TIMESTAMP,
  DATEUSERECIPENT TIMESTAMP,
  DUEDATE TIMESTAMP,
  STATUS NUMERIC,
  ISMANUAL NUMERIC,
  POST NUMERIC,
  IDMOVEMENTPARENT NUMERIC,
  TMP_TYPE NUMERIC,
  PGC_CATEGORY STRING,
  ISVISIBLE NUMERIC,
  TMP_VISIBILITYINDOCUMENTS NUMERIC
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/THIRDPARTYMOVEMENTPOLICY_landing/*.parquet"]);