CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.URPVIDAFREE_raw`
(
  PK NUMERIC,
  STATIC NUMERIC,
  STATUS NUMERIC,
  PERIODOPAGOPRIMAINPUT STRING,
  CAPITALASEGURADOINPUT STRING,
  PERIODOPAGOBENEFINPUT STRING,
  CAPITALASEGANTVFINPUT STRING,
  URPRIMAANUALINPUT STRING,
  URPRIMAFPINPUT STRING,
  SUMAASEGURADASEGTRAMOINPUT STRING,
  PORCDEVPRIMASFINALINPUT STRING,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/URPVIDAFREE_raw/*.parquet"]);