CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.URVIDATOTALPROTEGIDA_raw`
(
  AUDITDATE TIMESTAMP,
  PK NUMERIC,
  STATIC NUMERIC,
  STATUS NUMERIC,
  PRODUCTOSVIDAINPUT STRING,
  PRODUCTOSVIDAVALUE STRING,
  PERIODOPAGOPRIMAINPUT STRING,
  PERIODOPAGOPRIMAVALUE STRING,
  CAPITALASEGANTACCINPUT STRING,
  CAPITALASEGANTACCVALUE STRING,
  CAPITALASEGURADOACCINPUT STRING,
  CAPITALASEGURADOACCVALUE STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/URVIDATOTALPROTEGIDA_raw/*.parquet"]);