CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.VIEW_PROPLISTA_DEPEN_raw`
(
  PRID_PARENT NUMERIC,
  SIMBOLO_PADRE STRING,
  TRID_PADRE NUMERIC,
  TRDESC_PADRE STRING,
  TRVAL_PADRE FLOAT64,
  TR_DISPLAY_PADRE STRING,
  PRID_HIJO NUMERIC,
  SIMBOLO_HIJO STRING,
  TRID_HIJO NUMERIC,
  COUNT_HIJO NUMERIC,
  TRDESC_HIJO STRING,
  TRVAL_HIJO FLOAT64,
  TR_DISPLAY_HIJO STRING,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/VIEW_PROPLISTA_DEPEN_raw/*.parquet"]);