CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.VIEW_PROPIEDAD_VALORES_raw`
(
  PRID NUMERIC,
  SIMBOLO STRING,
  TIPO STRING,
  PTR_DISPLAY STRING,
  PTR_DISPLAY_OPCIONAL STRING,
  PTR_OPCION NUMERIC,
  TRID NUMERIC,
  TRDESC STRING,
  TRVAL FLOAT64,
  TR_DISPLAY STRING,
  TR_DISPLAY_OPCIONAL STRING,
  TR_OPCION NUMERIC,
  TIPOPROP STRING,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/VIEW_PROPIEDAD_VALORES_raw/*.parquet"]);