CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.acsele_temp.VIEW_PRESTAMO_raw`
(
  NUMERO_POLIZA STRING,
  NUMERO_PRESTAMO NUMERIC,
  MONTO_INICIAL STRING,
  AMORTIZACIONPENDIENTE STRING,
  INTERESPENDIENTE STRING,
  TOTALPENDIENTE STRING,
  FECHA_INICIAL TIMESTAMP,
  FECHA_FINAL TIMESTAMP,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/acsele_data/VIEW_PRESTAMO_raw/*.parquet"]);