CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.ABO_CAR_DEV_COL_raw`
(
  ID_ABO_CAR_DEV_COL NUMERIC,
  ID_ABONO STRING,
  ID_CAR_COL STRING,
  ID_DEVOLUCION NUMERIC,
  MONTO_CANTIDAD NUMERIC,
  MONTO_MONEDA STRING,
  FEC_APLICADO TIMESTAMP,
  ESTADO NUMERIC,
  FECHA_CREACION TIMESTAMP,
  FECHA_MODIFICACION TIMESTAMP,
  ID_PLANILLA NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/ABO_CAR_DEV_COL_raw/*.parquet"]);