CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.ABONO_CARGO_raw`
(
  ID_ABONO STRING,
  ID_CARGO STRING,
  MONTO_MONEDA STRING,
  MONTO_CANTIDAD NUMERIC,
  FEC_APLICADO TIMESTAMP,
  ID_ABONO_CARGO NUMERIC,
  ID_DEVOLUCION NUMERIC,
  USUARIO_CREACION STRING,
  FECHA_CREACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  ESTADO NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/ABONO_CARGO_raw/*.parquet"]);