CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.APLICACION_RECIBO_CAJA_raw`
(
  ID_APLICACION_RECIBO NUMERIC,
  ID_RECIBO_CAJA NUMERIC,
  FECHA_APLICACION TIMESTAMP,
  MONTO_APLICADO_CANTIDAD NUMERIC,
  MONTO_APLICADO_MONEDA STRING,
  ID_CUENTA_POLIZA NUMERIC,
  CONCEPTO_APLICADO STRING,
  ID_DETALLE_MOVIMIENTO NUMERIC,
  ID_CARGO_APLICADO NUMERIC,
  ID_PLANILLA_APLICADO NUMERIC,
  USUARIO_CREACION STRING,
  FECHA_CREACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  ESTADO NUMERIC,
  ID_DETALLE_PLANILLA_ASOCIADO NUMERIC,
  TIPO_APLICACION_RECIBO NUMERIC,
  ID_CARGO_COLECTIVO_APLICADO NUMERIC,
  ID_DEVOLUCION NUMERIC,
  FECHA_PROCESO DATE
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/APLICACION_RECIBO_CAJA_raw/*.parquet"]);