CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.CARGO_raw`
(
  ID NUMERIC,
  CONCEPTO NUMERIC,
  PERIODO_COBRANZA TIMESTAMP,
  ESTADO NUMERIC,
  NUMERO_CARGO NUMERIC,
  ID_CUENTA_POLIZA NUMERIC,
  MONTO_CARGO_MONEDA STRING,
  MONTO_CARGO_CANTIDAD NUMERIC,
  SALDO_CANTIDAD NUMERIC,
  SALDO_MONEDA STRING,
  FECHA_COBERTURA_INICIO TIMESTAMP,
  FECHA_COBERTURA_FIN TIMESTAMP,
  FECHA_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  INDICADOR_PAGADO STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/CARGO_raw/*.parquet"]);