CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.COBRO_raw`
(
  ID NUMERIC,
  FECHA_INICIO_COBERTURA TIMESTAMP,
  FECHA_TERMINO_COBERTURA TIMESTAMP,
  NUMERO_POLIZA NUMERIC,
  ESTADO_COBRO NUMERIC,
  ID_PROCESO_COBRANZA NUMERIC,
  COBRO_CANTIDAD NUMERIC,
  COBRO_MONEDA STRING,
  MONTO_ENVIADO NUMERIC,
  OBSERVACION STRING,
  MONTO_VIACOBRO_CANTIDAD NUMERIC,
  MONTO_VIACOBRO_MONEDA STRING,
  NUM_CORRELATIVO NUMERIC,
  FECHA_ESTIMADA_PAGO TIMESTAMP,
  GLOSA_CONCEPTO STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/COBRO_raw/*.parquet"]);