CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.CUENTA_POLIZA_raw`
(
  FECHA_CREACION TIMESTAMP,
  FECHA_MODIFICACION TIMESTAMP,
  ID NUMERIC,
  NUMERO_POLIZA NUMERIC,
  NUMERO_PROPUESTA NUMERIC,
  TIPO NUMERIC,
  MONEDA STRING,
  IND_ACSELE STRING,
  ID_POLIZA_ACSELE NUMERIC,
  ID_CARGO NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/CUENTA_POLIZA_raw/*.parquet"]);