CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.DEPOSITO_raw`
(
  ID_DEPOSITO NUMERIC,
  FECHA_REGISTRO TIMESTAMP,
  DESCRIPCION STRING,
  MONTO_CANTIDAD NUMERIC,
  ESTADO_DEPOSITO NUMERIC,
  ID_PRODUCTO_FINANCIERO NUMERIC,
  NUMERO_OPERACION STRING,
  MONTO_MONEDA STRING,
  BANCO STRING,
  NOMBRE_ARCHIVO STRING,
  FECHA_CREACION STRING,
  FECHA_MODIFICACION STRING,
  IND_EMISION_AUTOMATICA STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/DEPOSITO_raw/*.parquet"]);