CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.DETALLE_RECEPCION_raw`
(
  FECHA_CREACION TIMESTAMP,
  FECHA_MODIFICACION TIMESTAMP,
  ID_DETALLE_RECEPCION NUMERIC,
  ID_RECEPCION NUMERIC,
  MONTO_CANTIDAD NUMERIC,
  NUM_POLIZA STRING,
  NUM_CORRELATIVO STRING,
  RESPUESTA_COBRO STRING,
  MONTO_MONEDA STRING,
  TIPO_CUENTA NUMERIC,
  COD_CONCEPTO NUMERIC,
  FECHA_DEPOSITO TIMESTAMP,
  NUMERO_OPERACION STRING,
  MONTO_POLIZA_CANTIDAD NUMERIC,
  MONTO_POLIZA_MONEDA STRING,
  CODIGO_RECHAZO STRING,
  COD_SERVICIO STRING,
  COD_DEUDOR STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/DETALLE_RECEPCION_raw/*.parquet"]);