CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.DETALLE_PLANILLA_raw`
(
  ID_DETALLE_PLANILLA NUMERIC,
  NUMERO_POLIZA NUMERIC,
  CODIGO_CONCEPTO STRING,
  GLOSA_CONCEPTO STRING,
  MONTO NUMERIC,
  ID_PLANILLA NUMERIC,
  ID_ABONO STRING,
  ID_DETALLE_RECEPCION NUMERIC,
  ESTADO_LINEA_PLANILLA NUMERIC,
  FECHA_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  INDACSELE STRING,
  IND_REG_CONCILIACION_EMI_AUT STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/DETALLE_PLANILLA_raw/*.parquet"]);