CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.DETALLE_COMPROBANTE_raw`
(
  ID_DETALLE_COMPROBANTE NUMERIC,
  ID_COMPROBANTE NUMERIC,
  NUM_CORRELANTIVO NUMERIC,
  TOTAL NUMERIC,
  COD_CONCEPTO STRING,
  DESCRIPCION_CONCEPTO STRING,
  MONTO_MONEDA STRING,
  AFECTO NUMERIC,
  NO_AFECTO NUMERIC,
  IMPUESTO NUMERIC,
  ES_AFECTO_IGV NUMERIC,
  ID_CARGO NUMERIC,
  DERECHO_EMISION NUMERIC,
  ESTADO NUMERIC,
  FECHA_INICIO_COBERTURA DATE,
  FECHA_TERMINO_COBERTURA DATE,
  FECHA_PROCESO DATE,
  FECHA_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  USUARIO_MODIFICACION STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/DETALLE_COMPROBANTE_raw/*.parquet"]);