CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.INTERMEDIO_CARGO_raw`
(
  OPENITEMDATE TIMESTAMP,
  ID_INTERMEDIO NUMERIC,
  ID_OPENITEM NUMERIC,
  ID_CARGO NUMERIC,
  ID_POLIZA NUMERIC,
  FEC_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  NUMERO_POLIZA NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/INTERMEDIO_CARGO_raw/*.parquet"]);