CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.PLANILLA_raw`
(
  ID_PLANILLA NUMERIC,
  FECHA_PLANILLA TIMESTAMP,
  DESCRIPCION STRING,
  ESTADO_PLANILLA NUMERIC,
  ID_PRODUCTO_FINANCIERO NUMERIC,
  ID_VIA_COBRO NUMERIC,
  FECHA_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  COMISION_MONEDA STRING,
  COMISION_CANTIDAD NUMERIC,
  TOTAL_MONEDA STRING,
  TOTAL_CANTIDAD NUMERIC,
  TIPO_PLANILLA NUMERIC,
  TIPO_INGRESO NUMERIC,
  ORIGEN_RECAUDACION NUMERIC,
  MODO_RECAUDACION NUMERIC,
  MONTO_REDONDEO NUMERIC,
  IND_EMISION_AUTOMATICA STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/PLANILLA_raw/*.parquet"]);