CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.POLIZA_RENVI_raw`
(
  NUMERO_POLIZA NUMERIC,
  CODIGO_MONEDA STRING,
  CODIGO_MODALIDAD STRING,
  GLS_MONEDA_INTERFACE STRING,
  PORCENTAJE_DOLARES NUMERIC,
  PORCENTAJE_SOLES NUMERIC
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/POLIZA_RENVI_raw/*.parquet"]);