CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.PROCESO_COBRANZA_raw`
(
  ID NUMERIC,
  NOMBRE_ARCHIVO_RECEPCION STRING,
  NOMBRE_ARCHIVO_ENVIO STRING,
  FECHA_ENVIO TIMESTAMP,
  ESTADO NUMERIC,
  NOMBRE_USUARIO STRING,
  PERIODO NUMERIC,
  TIPO NUMERIC,
  ID_VIA_COBRO NUMERIC,
  TIPO_MONEDA STRING,
  VALOR_TIPO_CAMBIO NUMERIC,
  DIA_COBRO NUMERIC,
  FECHA_GENERACION TIMESTAMP,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/PROCESO_COBRANZA_raw/*.parquet"]);