CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.PRODUCTO_FINANCIERO_raw`
(
  ID NUMERIC,
  TIPO_PRODUCTO STRING,
  NUMERO STRING,
  ID_EMISOR NUMERIC,
  ID_TITULAR NUMERIC,
  MONEDA STRING,
  TIPO_CUENTA NUMERIC,
  FECHA_VENCIMIENTO STRING,
  ID_MARCA NUMERIC,
  TIPO_ORIGEN_DEPOSITO NUMERIC,
  MONTO_CUENTA NUMERIC,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/PRODUCTO_FINANCIERO_raw/*.parquet"]);