CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.RECEPCION_raw`
(
  ID_RECEPCION STRING,
  ARCHIVO_APROBADOS STRING,
  ARCHIVO_RECHAZADOS STRING,
  ID_INSTITUCION_FINANCIERA STRING,
  FECHA_RECEPCION TIMESTAMP,
  ID_PLANILLA STRING,
  ID_PROCESO_COBRANZA STRING,
  ID_ESTADO NUMERIC,
  FECHA_CREACION TIMESTAMP,
  USUARIO_CREACION STRING,
  FECHA_MODIFICACION TIMESTAMP,
  USUARIO_MODIFICACION STRING,
  ID_PRODUCTO_FINANCIERO STRING,
  TIPO_CONCILIACION NUMERIC,
  CANAL NUMERIC,
  CODIGO_VIA_COBRO STRING,
  NUMERO_OPERACION STRING,
  IND_EMISION_AUTOMATICA STRING,
  FECHA_PROCESO TIMESTAMP
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/RECEPCION_raw/*.parquet"]);