CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.TD_POLIZA_CARGO_DEVOLUCION_raw`
(
  NUMERO_POLIZA NUMERIC,
  NUMERO_CARGO NUMERIC,
  ID_CARGO NUMERIC,
  ID_DEVOLUCION STRING,
  ESTADO_CARGO STRING,
  FECHA_HORA_DEVOLUCION TIMESTAMP,
  FECHA_DEVOLUCION DATE,
  MONTO_DEVOLUCION NUMERIC,
  MONEDA_DEVOLUCION STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/TD_POLIZA_CARGO_DEVOLUCION_raw/*.parquet"]);