CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.samp_temp.VIA_COBRO_raw`
(
  ID NUMERIC,
  NOMBRE STRING,
  ID_TIPO_VIA_COBRO NUMERIC,
  MONEDA_COBRANZA STRING,
  ID_MARCA_TARJETA NUMERIC,
  INDICADOR_VALIDACION NUMERIC,
  ID_INSTITUCION_FINANCIERA NUMERIC,
  ID_MEDIO_ENVIO NUMERIC,
  ESTADO_AFILIACION NUMERIC,
  ESTADO_COBRANZA NUMERIC,
  ESTRATEGIA_AGRUPACION NUMERIC,
  CORREO_AFILIACION STRING,
  FECHA_PROCESO DATETIME
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/samp_data/VIA_COBRO_raw/*.parquet"]);