WITH TMP_DATA AS (

/*SELECT 
'CANCELARFLEX' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARFLEX
UNION ALL
*/
/*
SELECT
'CANCELARVCASHSTOCK' AS ESTADO
,STATUS
,STATIC
,PK
,PERIODODEVTOTALCANCVALUE
,PERIODODEVTOTALCANCINPUT
,MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONINPUT
,FRECUENCIAPAGOENDOSOVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEMISIONVALUE
,FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVCASHSTOCK
UNION ALL
*/

SELECT
 'CANCELARVE' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,NULL AS MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVE
UNION ALL
SELECT
 'CANCELAREG' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,NULL AS MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELAREG
UNION ALL
/*
SELECT
 'CANCELARVF' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVF

UNION ALL
*/
/*
SELECT
 'CANCELARVCASH' AS ESTADO
,STATUS
,STATIC
,PK
,PERIODODEVTOTALCANCVALUE
,PERIODODEVTOTALCANCINPUT
,MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEMISIONVALUE
,FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVCASH
UNION ALL
*/

SELECT
 'CANCELARSURA'AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARSURA
UNION ALL
SELECT
 'CANCELARVP' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,NULL AS MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVP

UNION ALL
SELECT
 'CANCELAR'AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,NULL AS MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELAR
UNION ALL
SELECT
 'CANCELARVEH' AS ESTADO
,STATUS
,STATIC
,PK
,PERIODODEVTOTALCANCVALUE
,PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,MOTIVOCANCELACIONVEHINPUT --
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT

,NULL AS RAZONCANCELACIONEXINPUT
,NULL AS RAZONCANCELACIONEXVALUE
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS FECHASOLANULACIONINPUT	
,NULL AS FECHASOLANULACIONVALUE
FROM INTERSEGURO.CANCELARVEH
UNION ALL
SELECT
 'CANCELARVEH' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS PERIODODEVTOTALCANCVALUE
,NULL AS PERIODODEVTOTALCANCINPUT
,NULL AS MOTIVOCANCELACIONVALUE
,NULL AS MOTIVOCANCELACIONINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEMISIONVALUE
,NULL AS FECHAEMISIONINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,RAZONCANCELACIONEXINPUT
,RAZONCANCELACIONEXVALUE
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,FECHASOLANULACIONINPUT	
,FECHASOLANULACIONVALUE	
FROM INTERSEGURO.CANCELAREX
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    ,BAJ.FECHASOLICITUDINPUT AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    ,BAJ.FECHASOLANULACIONINPUT AS FECHA_ANULACION
    ,BAJ.FECHAEFECTIVAINPUT AS FECHA_EFECTIVA
  --  ,BAJ.FRECUENCIAPAGOENDOSOINPUT AS FRECUENCIA_PAGO_ENDOSO
  --  ,BAJ.PERIODODEVTOTALCANCINPUT AS PERIODO_TOTAL_CANCELACION
  --  ,BAJ.FECHARECEPCARTAINPUT AS FECHA_RECEPCION
    ,BAJ.OBSERVACIONINPUT AS OBSERVACION
    ,BAJ.MOTIVOCANCELACIONINPUT AS  MOTIVO_MOVIMIENTO
    ,BAJ.ESTADO AS MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 --INNER JOIN INTERSEGURO.STATE STA
 --       ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
  --   AND COT.STATUS=2
   --  AND PRE.NUMEROPOLIZAINPUT='29640'
     
     --> POLIZA OPERACION REVISAR QUERY 
     
     AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');

     --POLIZA_OPERACION_EVENT_raw
     --AND EVE.DESCRIPTION='RehabSaldadoEfectivo' 
     --RehabilitarSaldado
     --SolicitarRehabSaldado
     
     
     