WITH TMP_DATA AS (
SELECT 
'REHABILITAR' AS ESTADO
,NULL AS TIPOVIGREHABVALUE
,NULL AS TIPOVIGREHABINPUT
,NULL AS TIPOVIGENCIAENDOSODSVALUE
,NULL AS TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,RAZONREHABILITACIONVALUE
,RAZONREHABILITACIONINPUT
,PK
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGREHABVALUE
,NULL AS INICIOVIGREHABINPUT
,NULL AS INICIOVIGENCIAENDOSODSVALUE
,NULL AS INICIOVIGENCIAENDOSODSINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACANCVALUE
,NULL AS FECHACANCINPUT
,NULL AS FECHACADUCVALUE
,NULL AS FECHACADUCINPUT
FROM INTERSEGURO.REHABILITAR
UNION ALL
SELECT 
'REHABILITARTCD' AS ESTADO
,NULL AS TIPOVIGREHABVALUE
,NULL AS TIPOVIGREHABINPUT
,TIPOVIGENCIAENDOSODSVALUE
,TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,NULL AS RAZONREHABILITACIONVALUE
,NULL AS RAZONREHABILITACIONINPUT
,PK
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGREHABVALUE
,NULL AS INICIOVIGREHABINPUT
,INICIOVIGENCIAENDOSODSVALUE
,INICIOVIGENCIAENDOSODSINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACANCVALUE
,FECHACANCINPUT
,NULL AS FECHACADUCVALUE
,NULL AS FECHACADUCINPUT
FROM INTERSEGURO.REHABILITARTCD
UNION ALL
SELECT 
'REHABILITARCANC' AS ESTADO
,TIPOVIGREHABVALUE
,TIPOVIGREHABINPUT
,NULL AS TIPOVIGENCIAENDOSODSVALUE
,NULL AS TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,NULL AS RAZONREHABILITACIONVALUE
,NULL AS RAZONREHABILITACIONINPUT
,PK
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGREHABVALUE
,INICIOVIGREHABINPUT
,NULL AS INICIOVIGENCIAENDOSODSVALUE
,NULL AS INICIOVIGENCIAENDOSODSINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACANCVALUE
,NULL AS FECHACANCINPUT
,NULL AS FECHACADUCVALUE
,NULL AS FECHACADUCINPUT
FROM INTERSEGURO.REHABILITARCANC
UNION ALL
SELECT 
'REHABILITARSURA' AS ESTADO
,TIPOVIGREHABVALUE
,TIPOVIGREHABINPUT
,NULL AS TIPOVIGENCIAENDOSODSVALUE
,NULL AS TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,NULL AS RAZONREHABILITACIONVALUE
,NULL AS RAZONREHABILITACIONINPUT
,PK
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGREHABVALUE
,INICIOVIGREHABINPUT
,NULL AS INICIOVIGENCIAENDOSODSVALUE
,NULL AS INICIOVIGENCIAENDOSODSINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACANCVALUE
,NULL AS FECHACANCINPUT
,NULL AS FECHACADUCVALUE
,NULL AS FECHACADUCINPUT
FROM INTERSEGURO.REHABILITARSURA
UNION ALL
SELECT
'REHABILITARCADUC' AS ESTADO
,TIPOVIGREHABVALUE
,TIPOVIGREHABINPUT
,NULL AS TIPOVIGENCIAENDOSODSVALUE
,NULL AS TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,NULL AS RAZONREHABILITACIONVALUE
,NULL AS RAZONREHABILITACIONINPUT
,PK
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGREHABVALUE
,INICIOVIGREHABINPUT
,NULL AS INICIOVIGENCIAENDOSODSVALUE
,NULL AS INICIOVIGENCIAENDOSODSINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACANCVALUE
,NULL AS FECHACANCINPUT
,FECHACADUCVALUE
,FECHACADUCINPUT
FROM INTERSEGURO.REHABILITARCADUC
UNION ALL
SELECT
'REHABILITARSALDADO' AS ESTADO
,TIPOVIGREHABVALUE
,TIPOVIGREHABINPUT
,NULL AS TIPOVIGENCIAENDOSODSVALUE
,NULL AS TIPOVIGENCIAENDOSODSINPUT
,STATUS
,STATIC
,NULL AS RAZONREHABILITACIONVALUE
,NULL AS RAZONREHABILITACIONINPUT
,PK
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGREHABVALUE
,INICIOVIGREHABINPUT
,NULL AS INICIOVIGENCIAENDOSODSVALUE
,NULL AS INICIOVIGENCIAENDOSODSINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACANCVALUE
,NULL AS FECHACANCINPUT
,NULL AS FECHACADUCVALUE
,NULL AS FECHACADUCINPUT
FROM INTERSEGURO.REHABILITARSALDADO

)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    ,BAJ.FECHASOLICITUDINPUT AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    ,BAJ.FECHAEFECTIVAINPUT AS FECHA_EFECTIVA
    ,COALESCE(BAJ.RAZONREHABILITACIONINPUT,BAJ.INICIOVIGREHABINPUT) AS MOTIVO_MOVIMIENTO
    ,BAJ.ESTADO AS MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 --INNER JOIN INTERSEGURO.STATE STA
 --      ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
     
     AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');

    -- AND COT.STATUS=2