WITH TMP_DATA AS (
SELECT 
'RECHAZARPROPMANUAL' AS ESTADO
,STATUS
,STATIC
,PK
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,MOTIVORECHPROPMANUALVALUE
,MOTIVORECHPROPMANUALINPUT
,FECHARECEPCARTAVALUE
,FECHARECEPCARTAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.RECHAZARPROPMANUAL
UNION ALL
SELECT 
'RECHAZARPROPRAPIDA' AS ESTADO
,STATUS
,STATIC
,PK
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,NULL AS MOTIVORECHPROPMANUALVALUE
,NULL AS MOTIVORECHPROPMANUALINPUT
,NULL AS FECHARECEPCARTAVALUE
,NULL AS FECHARECEPCARTAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.RECHAZARPROPRAPIDA
UNION ALL
SELECT
'RECHAZARPROPUESTA' AS ESTADO
,STATUS
,STATIC
,PK
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,NULL AS MOTIVORECHPROPMANUALVALUE
,NULL AS MOTIVORECHPROPMANUALINPUT
,NULL AS FECHARECEPCARTAVALUE
,NULL AS FECHARECEPCARTAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.RECHAZARPROPUESTA
UNION ALL
SELECT 
'RECHAZAR' AS ESTADO
,STATUS
,STATIC
,PK
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS MOTIVORECHPROPMANUALVALUE
,NULL AS MOTIVORECHPROPMANUALINPUT
,NULL AS FECHARECEPCARTAVALUE
,NULL AS FECHARECEPCARTAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.RECHAZAR
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    --,NULL AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    ,BAJ.FECHARECEPCARTAINPUT AS FECHA_RECEPCION
    ,BAJ.OBSERVACIONINPUT AS OBSERVACION
    ,BAJ.MOTIVORECHPROPMANUALINPUT AS  MOTIVO_MOVIMIENTO
    ,BAJ.ESTADO AS MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 --INNER JOIN INTERSEGURO.STATE STA
 --       ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
  --   AND COT.STATUS=2
   --  AND PRE.NUMEROPOLIZAINPUT='29640'
     
     --> POLIZA OPERACION REVISAR QUERY 
     
     AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');

     --POLIZA_OPERACION_EVENT_raw
     --AND EVE.DESCRIPTION='RehabSaldadoEfectivo' 
     --RehabilitarSaldado
     --SolicitarRehabSaldado
     
     
     