WITH TMP_DATA AS (
/*
SELECT 
'TERMINARVF' AS TERMINARVF
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,MOTIVOTERMINACIONVALUE
,MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARVF
UNION ALL
*/
SELECT 
'TERMINARSALPROSURA' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,MOTIVOTERMINACIONVALUE
,MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARSALPROSURA
/*
UNION ALL
SELECT 
'TERMINARVCASH' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,MOTIVOTERMINACIONVALUE
,MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARVCASH
*/
UNION ALL
SELECT
'TERMINARVEH' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,MOTIVOTERMINACIONVEHVALUE
,MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARVEH
UNION ALL
SELECT 
'TERMINAR' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,MOTIVOANULACIONPTVALUE
,MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINAR
UNION ALL
SELECT 
'TERMINAREG' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,MOTIVOTERMINACIONEGVALUE
,MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINAREG
UNION ALL
SELECT
'TERMINARSURA' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,MOTIVOTERMINACIONVALUE
,MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARSURA
UNION ALL
SELECT 
'TERMINARVP' AS ESTADO
,STATUS
,STATIC
,PRUEBAFECNACVALUE
,PRUEBAFECNACINPUT
,PK
,MOTIVOTERMINACIONVPVALUE
,MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,FECNACASEGPRINCIPALVALUE
,FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARVP
/*
UNION ALL
SELECT
'TERMINARVLC' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,MOTIVOANULACIONVDLVALUE
,MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.TERMINARVLC
UNION ALL
*/
/*
SELECT 
'REHABTERMINARVLC' AS ESTADO
,STATUS
,STATIC
,NULL AS PRUEBAFECNACVALUE
,NULL AS PRUEBAFECNACINPUT
,PK
,NULL AS MOTIVOTERMINACIONVPVALUE
,NULL AS MOTIVOTERMINACIONVPINPUT
,NULL AS MOTIVOTERMINACIONVEHVALUE
,NULL AS MOTIVOTERMINACIONVEHINPUT
,NULL AS MOTIVOTERMINACIONVALUE
,NULL AS MOTIVOTERMINACIONINPUT
,NULL AS MOTIVOTERMINACIONEGVALUE
,NULL AS MOTIVOTERMINACIONEGINPUT
,NULL AS MOTIVOANULACIONVDLVALUE
,NULL AS MOTIVOANULACIONVDLINPUT
,NULL AS MOTIVOANULACIONPTVALUE
,NULL AS MOTIVOANULACIONPTINPUT
,NULL AS FECNACASEGPRINCIPALVALUE
,NULL AS FECNACASEGPRINCIPALINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
FROM INTERSEGURO.REHABTERMINARVLC
*/
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT

     ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO

      ,COALESCE(BAJ.MOTIVOANULACIONPTINPUT,BAJ.MOTIVOANULACIONVDLINPUT,
      BAJ.MOTIVOTERMINACIONEGINPUT,BAJ.MOTIVOTERMINACIONINPUT,BAJ.MOTIVOTERMINACIONVEHINPUT
      ,BAJ.MOTIVOTERMINACIONVPINPUT) AS  MOTIVO_MOVIMIENTO
      ,BAJ.ESTADO AS MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 --INNER JOIN INTERSEGURO.STATE STA
 --       ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
  --   AND COT.STATUS=2
   --  AND PRE.NUMEROPOLIZAINPUT='29640'
     
      AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');

     --> POLIZA OPERACION REVISAR QUERY 
     
     --POLIZA_OPERACION_EVENT_raw
     --AND EVE.DESCRIPTION='RehabSaldadoEfectivo' 
     --RehabilitarSaldado
     --SolicitarRehabSaldado
     
     
     