WITH TMP_DATA AS (

SELECT
'ENDOSARND' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,TIPOENDOSONDVALUE
,TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARND


UNION ALL 


SELECT
'ENDOSARVCASH' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,PLANVIDAENDOSOVALUE
,PLANVIDAENDOSOINPUT
,PK
,PAGADOHASTAVALUE
,PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NROPERIODOSDIFERIDOSVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROMESESULTIMOPERIODOVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,INICIODIFERIMIENTOVALUE
,INICIODIFERIMIENTOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOACTUALINPUT
,FINDIFERIMIENTOVALUE
,FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAPGPVIDAVALUE
,FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,ENDOSOSSIMPLESSACVCASHVALUE
,ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVCASH


UNION ALL


SELECT 
'EXCLUIRCOBENDOSO' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.EXCLUIRCOBENDOSO


UNION ALL


SELECT 
'ENDOSARAPLAZADO' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,MESESAPLAZOPROPVALUE
,MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,FECHAFINAPLAZOENDOSOVALUE
,FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,APLAZARENDOSOVALUE
,APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARAPLAZADO


UNION ALL


SELECT
'ENDOSARRECHAZADO' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,RECHAZARENDOSOVALUE
,RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,MOTIVORECHAZARENDOSOVALUE
,MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARRECHAZADO


UNION ALL


SELECT
'ENDOSAR' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,TIPOENDOSOINPUT
,TIPOENDOSODESGINDVALUE
,TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,PRODUCTDESGINDVALUE
,PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,OBJETODELENDOSOVALUE
,OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSAR


UNION ALL


SELECT 
'ENDOSARVIDA' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,PLANVIDAENDOSOVALUE
,PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NROPERIODOSDIFERIDOSVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROMESESULTIMOPERIODOVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,INICIODIFERIMIENTOVALUE
,INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAPGPVIDAVALUE
,FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINDIFERIMIENTOVALUE
,FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVIDA


UNION ALL 


SELECT 
'ENDOSARINSPECCIONVEH' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARINSPECCIONVEH


UNION ALL


SELECT 
'ENDOSARVP' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,ENDOSOSSIMPLEACCVALUE
,ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,ENDOSOSCOMACCVALUE
,ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVP


UNION ALL 


SELECT 
'ENDOSARSALPROSURA' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,PLANVIDAENDOSOVALUE
,PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,ENDOSOSSALPROSURAVALUE
,ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARSALPROSURA


UNION ALL


SELECT 
'ENDOSARFLEX' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,PLANVIDAVALUE
,PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,PAGADOHASTAVALUE
,PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NUMEROSOLICITUDVALUE
,NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NUMEROPOLIZAFLEXVALUE
,NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,ENDOSOSSIMPLESSACFLEXVALUE
,ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,ENDOSOSCOMPLEJOSOPFLEXVALUE
,ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARFLEX


UNION ALL


SELECT 
'ENDOSARVEH' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,ENDOSOSVEHVALUE
,ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVEH


UNION ALL


SELECT
'ENDOSARPROPRAPIDA' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,TIPOENDOSOPROPRAPIDAVALUE
,TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPRAPIDA


UNION ALL


SELECT 
'ENDOSOCAMBIOFONDOFLEX' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSOCAMBIOFONDOFLEX


UNION ALL


SELECT 
'ENDOSARACC' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARACC


UNION ALL


SELECT 
'ENDOSARPROPUESTA' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,TIPOENDOSOPROPUESTAVALUE
,TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPUESTA


UNION ALL


SELECT 
'ENDOSARDESISTIDO' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,OBSERVACIONVALUE
,OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,MOTIVODESISTIRENDOSOVALUE
,MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,DESISTIRENDOSOVALUE
,DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARDESISTIDO


UNION ALL


SELECT 
'ENDOSARVF' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,PLANVIDAENDOSOVALUE
,PLANVIDAENDOSOINPUT
,PK
,PAGADOHASTAVALUE
,PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NROPERIODOSDIFERIDOSVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROMESESULTIMOPERIODOVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,INICIODIFERIMIENTOVALUE
,INICIODIFERIMIENTOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOACTUALINPUT
,FINDIFERIMIENTOVALUE
,FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAPGPVIDAVALUE
,FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,ENDOSOSSIMPLESSACVFVALUE
,ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,ENDOSOSCOMPLEJOSOPVFVALUE
,ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVF


UNION ALL


SELECT
'ENDOSARVLC' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,ENDOSOSSIMPLESSACVLCVALUE
,ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARVLC


UNION ALL


SELECT 
'ENDOSARRH' AS ESTADO
,NULL AS TIPOVIGENCIAENDOSOVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,TIPOENDOSORHVALUE
,TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,NULL AS RESPONSABLEATENCIONVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARRH


UNION ALL


SELECT 
'ENDOSARSURA' AS ESTADO
,TIPOVIGENCIAENDOSOVALUE
,TIPOVIGENCIAENDOSOINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPOLVALUE
,TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSODESGINDINPUT
,STATUS
,STATIC
,RESPONSABLEATENCIONVALUE
,RESPONSABLEATENCIONINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RECHAZARENDOSOINPUT
,PRODUCTOSVIDAVALUE
,PRODUCTOSVIDAINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PLANVIDAINPUT
,PLANVIDAENDOSOVALUE
,PLANVIDAENDOSOINPUT
,PK
,NULL AS PAGADOHASTAVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAENDOSOINPUT
,NROPERIODOSDIFERIDOSVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROMESESULTIMOPERIODOVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NOMBREUSUARIOVALUE
,NOMBREUSUARIOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MESESAPLAZOPROPINPUT
,LOGINUSUARIOVALUE
,LOGINUSUARIOINPUT
,INICIOVIGENCIAENDOSOVALUE
,INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,INICIODIFERIMIENTOVALUE
,INICIODIFERIMIENTOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOACTUALINPUT
,FINDIFERIMIENTOVALUE
,FINDIFERIMIENTOINPUT
,FECHASOLICITUDVALUE
,FECHASOLICITUDINPUT
,FECHAPGPVIDAVALUE
,FECHAPGPVIDAINPUT
,FECHAMOVIMIENTOVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAFINPOLIZAVALUE
,FECHAFINPOLIZAINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,FECHAEFECTIVAVALUE
,FECHAEFECTIVAINPUT
,FECHACLIENTEVALUE
,FECHACLIENTEINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVALUE
,ENDOSOSSIMPLESSACSURAVALUE
,ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,ENDOSOSCOMPLEJOSOPSURAVALUE
,ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMACCINPUT
,ENDOSOMODIFPRIMAVALUE
,ENDOSOMODIFPRIMAINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS DESISTIRENDOSOINPUT
,CONTOIPENDVALUE
,CONTOIPENDINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS APLAZARENDOSOINPUT
FROM INTERSEGURO.ENDOSARSURA
),


ENDOSOS_VEHICULAR_VALUES AS (
SELECT DISTINCT P.Simbolo, F.Value, F.Description, X.TTL_VALUE as Display--, PlPr.Idproducto
,CASE WHEN SUBSTR(F.Description,0,3)='TES' THEN 'Simple' Else 'Complejo' END AS TipoEndoso
FROM Interseguro.Property P
INNER JOIN Interseguro.Transformadorfila F On F.Propertyid = P.Propertyid
LEFT JOIN Interseguro_Gu.Cdtr_Propertytranslation Pp ON P.Simbolo = Pp.Ptl_Name AND Pp.Ptl_Language IN ('es','(d)')
LEFT JOIN Interseguro_Gu.cdtr_propertytloptional ppp ON pp.ptl_name = ppp.ptlo_name AND pp.ptl_language = ppp.ptlo_language
LEFT JOIN Interseguro.Cdtr_Transformertranslation X ON F.Transformadorfilaid = X.Trf_Id AND F.Description = X.Ttl_Name AND X.Ttl_Language = Pp.Ptl_Language
WHERE X.TTL_VALUE IS NOT NULL AND LENGTH(X.TTL_VALUE) > 6
AND SUBSTR(F.Description,0,3) IN ('TEC', 'TES')
AND P.Simbolo = 'EndososVeh' 
)


SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    ,BAJ.FECHASOLICITUDINPUT AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
  --  ,BAJ.FECHASOLANULACIONINPUT AS FECHA_ANULACION
    ,BAJ.FECHAEFECTIVAINPUT AS FECHA_EFECTIVA
    ,CASE WHEN AGR.PRODUCTID IN (73989, 77849) THEN EVV.DISPLAY 
    ELSE BAJ.TIPOENDOSOPOLINPUT
    END AS TIPO_ENDOSO
    ,BAJ.LOGINUSUARIOINPUT AS USUARIO_SOLICITUD
    ,COALESCE(PRE.NUMEROSOLICITUDINPUT,BAJ.NUMEROSOLICITUDINPUT) AS NUMERO_SOLICITUD
    ,BAJ.NROMESESDIFERIDOSTOTALINPUT AS MESES_DIFERIDOS
  --  ,BAJ.FRECUENCIAPAGOENDOSOINPUT AS FRECUENCIA_PAGO_ENDOSO
  --  ,BAJ.PERIODODEVTOTALCANCINPUT AS PERIODO_TOTAL_CANCELACION
  --  ,BAJ.FECHARECEPCARTAINPUT AS FECHA_RECEPCION
   -- ,BAJ.OBSERVACIONANULACIONINPUT AS OBSERVACION
   -- ,BAJ.
    --,COALESCE(BAJ.MOTIVOANULACIONPTINPUT,BAJ.MOTIVOANULACIONVEHINPUT) AS  MOTIVO_MOVIMIENTO
  --  ,BAJ.GASTOSADMININPUT AS GASTOS_ADMINISTRATIVOS
 --   ,BAJ.CANCELREASONBANINPUT
    ,BAJ.ESTADO AS MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 --VEHICULAR
 LEFT JOIN ENDOSOS_VEHICULAR_VALUES EVV
    ON EVV.DESCRIPTION = BAJ.ENDOSOSVEHINPUT
 --INNER JOIN INTERSEGURO.STATE STA
 --       ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
     AND COT.STATUS <> 3
  --   AND COT.STATUS=2
   --  AND PRE.NUMEROPOLIZAINPUT='144632'
     AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
   

     
     