SELECT
    PRE.NUMEROPOLIZAINPUT AS NUMERO_POLIZA,
    PLO.OPERATIONPK AS NUMERO_OPERACION,
    TO_CHAR(COT.AUDITDATE, 'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE,
    AGR.PRODUCTID AS ID_PRODUCTO,
    TRIM(UPPER(POR.DESCRIPTION)) AS NOMBRE_PRODUCTO,
    CASE
        WHEN COT.STATUS = 1 THEN 'Not applied operation'
        WHEN COT.STATUS = 2 THEN 'Applied operation'
        ELSE '' || COT.STATUS
    END AS STATUS_OPERATION,
    -- Datos de la POLIZA
    POLL.NUMEROCERTIFICADOSOATINPUT AS NUMERO_CERTIFICADO,
    POLL.NUMEROPROPUESTAINPUT AS NUMERO_PROPUESTA,
    POLL.FECHAEMISIONSOATINPUT AS FECHA_EMISION_SOAT,
    POLL.CANALOPERACIONESSOATINPUT AS CANAL_OPERACIONES_SOAT,
    POLL.FECHAVENTAINPUT AS FECHA_VENTA,
    POLL.HORAVENTAINPUT AS HORA_VENTA,
    POLL.FECHAREFRENDOINPUT,
    POLL.ORIGENVENTAINPUT AS ORIGEN_VENTA,
    POLL.TIPOEMISIONINPUT AS TIPO_EMISION,
    POLL.CODIGOCOLABORARDORINPUT AS CODIGO_COLABORADOR,
    POLL.CODAGENTIENOFIINPUT,
    POLL.NUMEROVENDEDORSOATINPUT AS NUMERO_VENDEDOR_SOAT,
    POLL.NROTARJETACTAINPUT AS NUMERO_TARJETA,
    POLL.FORMAPAGOINPUT AS FORMAT_PAGO,
    POLL.MODALIDADREGISTROINPUT AS MODALIDAD_REGISTRO,
    POLL.PRIMASOATINPUT AS PRIMA_SOAT,
    POLL.MONEDASOATINPUT AS MONEDA_SOAT,
    POLL.PROVEEDORDIGITINPUT AS PROVEEDOR_DIGITAL,
    POLL.PLACAINPUT AS PLACA,
    POLL.USOINPUT AS USO_VEHICULO,
    POLL.CLASEINPUT AS CLASE_VEHICULO,
    POLL.ZONAINPUT AS ZONA,
    POLL.MARCAINPUT AS MARCA_VEHICULO,
    POLL.MODELOINPUT AS MODELO_VEHICULO,
    POLL.FECHAFABRICACIONINPUT AS FECHA_FABRICACION,
    POLL.COLORINPUT AS COLOR_VEHICULO,
    POLL.NUMEROMOTORINPUT AS NUMERO_MOTOR,
    POLL.NUMEROASIENTOSINPUT AS NUMERO_ASIENTOS_VEHICULO,
    POLL.PRIMACALCULADAINPUT AS PRIMA_CALCULADA,
    POLL.NUMEROLOTEINPUT AS NUMERO_LOTE,
    POLL.ANEXOSOATINPUT AS ANEXO_SOAT,
    POLL.DNISOATINPUT AS DNI_SOAT,
    POLL.APEPATERNOPROPSOATINPUT,
    POLL.APEMATERNOPROPSOATINPUT,
    POLL.NOMBREPROPSOATINPUT,
    POLL.NIVELAGRUPREASEGINPUT,
    POLL.RPRIMASOATINPUT,
    POLL.SIMBOLOMONEDASININPUT,
    POLL.MONTOUITSININPUT,
    POLL.RMVSININPUT,
    POLL.SIMBOLOMONEDAPLSININPUT,
    POLL.CODDEPARTCARTAINPUT AS CODIGO_DEPARTAMENTO,
    POLL.CODPROVINCARTAINPUT AS CODIGO_PROVINCIA,
    POLL.CODDISTRICARTAINPUT AS CODIGO_DISTRITO,
    POLL.DELIVERYINPUT AS DEVIVERY,
    POLL.MEDIOPAGOINPUT AS MEDIO_PAGO,
    POLL.FECHAENTREGAINPUT AS FECHA_ENTREGA,
    PRE.canalventavalue AS CODIGO_CANAL,
    POLL.CODAGENTIENOFIVALUE AS CODIGO_AGENCIA,
    POLL.CLASEVALUE AS CODIGO_CLASE,
    POLL.USOVALUE AS CODIGO_USO
FROM
    INTERSEGURO.PREPOLICY PRE
INNER JOIN
    INTERSEGURO.POLICYDCO PLO ON PLO.DCOID = PRE.PK
INNER JOIN
    INTERSEGURO.CONTEXTOPERATION COT ON COT.ID = PLO.OPERATIONPK
INNER JOIN
    INTERSEGURO.AGREGATEDPOLICY AGR ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
INNER JOIN
    INTERSEGURO.PRODUCT POR ON POR.PRODUCTID = AGR.PRODUCTID
    AND AGR.PRODUCTID IN (35448, 73989, 77849)
-- DATOS DE LA POLIZA
INNER JOIN
    interseguro.polsoat POLL ON POLL.PK = PRE.PK
WHERE
    PRE.NUMEROPOLIZAINPUT IS NOT NULL
    --AND EXTRACT(YEAR FROM COT.AUDITDATE) < 2016
    -- AND COT.AUDITDATE >= (CURRENT_DATE-250)
    AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
