WITH TMP_POL_TABLA AS 
(
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,'' AS FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,'' AS RECARGOACEPTADOINPUT
,'' AS TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDATOTALPROTEGIDA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,'' AS FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,'' AS RECARGOACEPTADOINPUT
,'' AS TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLSIEMPRESEGURO
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,'' AS FECHAPROXGENPRIMAVIDAINPUT
,'' AS PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,'' AS TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLSEGUROACCIDENTES
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,'' AS FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,'' AS RECARGOACEPTADOINPUT
,'' AS TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAPROTEGIDA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,'' AS PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAENTERA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,'' AS PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,'' AS TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALSIMPLE
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,'' AS PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDATEMPORAL
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,'' AS CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLPLANGARANTIZADO
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,'' AS CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLEDUCGARANTIZADAPLUSNEW
UNION ALL
SELECT
PK
,'' AS NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,'' AS FECHAPROXGENREASEGAUXINPUT
,'' AS FECHAPROXIMAGENREASEGINPUT
,'' AS INDEXCLUSIONESVIDAINPUT
,'' AS CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLEDUCGARANTIZADA
UNION ALL
SELECT
PK
,'' AS NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,'' AS FECHAPROXGENREASEGAUXINPUT
,'' AS FECHAPROXIMAGENREASEGINPUT
,'' AS INDEXCLUSIONESVIDAINPUT
,'' AS CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,'' AS TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLEDUCGARANTIZADAPLUS
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAFREE
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,'' AS RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDACASH
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,'' AS RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,'' AS POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDACASHSTOCK
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,'' AS PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,'' AS IGNORARVALIDACIONSAINPUT
,'' AS SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,TIPOPAGOINPUT
,FECHARECEPCIONGDCINPUT
,FLAGNVACOTIZACIONINPUT
,FLAGVALVIADEPAGOINPUT
,INDAFINPUT
,MONEDAPRIMAINPUT
,MONEDATRANSACCIONINPUT
,MONTOPRIMAINPUT
,MONTOTRANSACCIONINPUT
,NUMOPERACIONINPUT
,TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLTEMDEVPRIMA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALTRIPLECREC
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOSURAINPUT AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALTRIPLEPROTEC
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOSURAINPUT AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLTEMPGARANTIZADO75
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALDOBLECREC
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALDOBLEPROTEC
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALSIMPLESURA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOSURAINPUT AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLEDUCACIONALSURA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLSEGUNDOASEGURADOSURA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLTEMPGARANTIZADO100
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLTEMPORALSURA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAENTERABENEFANT
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,FECHAEFECTIVADIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOINPUT
,FECHAINIDIFERIMIENTOINPUT
,FRECUENCIAPAGOORIGENINPUT
,MESESDIFERIDOSTOTALINPUT
,PERIODOPAGODIFERIDOSINPUT
,RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAENTERASURA
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,FECHASALDACIONDESDEINPUT
,FECHASALDACIONINPUT
,'' AS INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,CUOTAPRESTAMOSURAINPUT
,FECHAINIPRESTAMOSURAINPUT
,MONTOPRESTAMOSURAINPUT
,TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,'' AS INDPRESTAMOINPUT
FROM INTERSEGURO.POLDOTALDOBLECAPITAL
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOINPUT
FROM INTERSEGURO.POLFLEX65
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOINPUT
FROM INTERSEGURO.POLFLEX80
UNION ALL
SELECT
PK
,NIVELAGRUPREASEGINPUT
,NUMERODOCUMENTOINPUT
,TIPODOCUMENTOINPUT
,'' AS SIMBOLOMONEDASININPUT
,POLIZAELECTRONICAINPUT
,'' AS SIMBOLOMONEDAPLSININPUT
,FRECUENCIAPAGOANTINPUT
,AGENCIAFINALINPUT
,AGENCIAINICIALINPUT
,CANALVENTAVIDAINPUT
,CODAGENTEFINALINPUT
,CODAGENTEINICIALINPUT
,COMUNICACIONENDOSOINPUT
,COMUNICACIONGENCONTINPUT
,COMUNICACIONPOLIZAINPUT
,CORREOAGENTEFINALINPUT
,CORREOAGENTEINICIALINPUT
,CORREOICONTRATANTEINPUT
,CORREOIICONTRATANTEINPUT
,CORREOIIICONTRATANTEINPUT
,DIRECCIONCONTRATANTEINPUT
,EMAILENVIOENDOSOINPUT
,FECHACOTIZACIONINPUT
,FECHAFIRMAPROPINPUT
,FECHAPROPINPUT
,INDCAMBIOPROPINPUT
,MODOPAGOCONTRATANTEINPUT
,MONEDAANTINPUT
,NOMAGENTEDEFINITIVOINPUT
,NOMAGENTEFINALINPUT
,NOMAGENTEINICIALINPUT
,NOMBRECONTRATANTEINPUT
,NUMPROPORIGINALINPUT
,PLANVIDAINPUT
,PLANVIDAVALUE
,POLIZAELECTRONICAENINPUT
,PRIMAVIDAINPUT
,PRODUCTOSVIDAINPUT
,TELEFONOICONTRATANTEINPUT
,TELEFONOIICONTRATANTEINPUT
,TELEFONOIIICONTRATANTEINPUT
,'' AS CODINTERMEDIARIOINPUT
,FECHAPROXGENREASEGAUXINPUT
,FECHAPROXIMAGENREASEGINPUT
,INDEXCLUSIONESVIDAINPUT
,CORREOAGENTEDEFINITIVOINPUT
,FECHAPROXGENPRIMAVIDAINPUT
,PLANVIDAANTINPUT
,RECARGOACEPTADOINPUT
,TIPOPERSONAINPUT
,IGNORARVALIDACIONSAINPUT
,SUMAASEGURADAINPUT
,TIPODESCUENTOINPUT
,'' AS FECHAEFECTIVADIFERIMIENTOINPUT
,'' AS FECHAFINDIFERIMIENTOINPUT
,'' AS FECHAINIDIFERIMIENTOINPUT
,'' AS FRECUENCIAPAGOORIGENINPUT
,'' AS MESESDIFERIDOSTOTALINPUT
,'' AS PERIODOPAGODIFERIDOSINPUT
,'' AS RESPUESTAAPIENDOSODIFINPUT
,POLIZACESIONADAVEINPUT
,'' AS FECHASALDACIONDESDEINPUT
,'' AS FECHASALDACIONINPUT
,INDDPSINPUT
,'' AS TIPOPAGOINPUT
,'' AS FECHARECEPCIONGDCINPUT
,'' AS FLAGNVACOTIZACIONINPUT
,'' AS FLAGVALVIADEPAGOINPUT
,'' AS INDAFINPUT
,'' AS MONEDAPRIMAINPUT
,'' AS MONEDATRANSACCIONINPUT
,'' AS MONTOPRIMAINPUT
,'' AS MONTOTRANSACCIONINPUT
,'' AS NUMOPERACIONINPUT
,'' AS TASACOSTOEFECTIVOANUALINPUT
,'' AS CUOTAPRESTAMOSURAINPUT
,'' AS FECHAINIPRESTAMOSURAINPUT
,'' AS MONTOPRESTAMOSURAINPUT
,'' AS TCEASURAINPUT
,'' AS TIPOENDOSOPOLSOLINPUT
,'' AS FECHAPACTADAINPUT
,'' AS PRIMACOTINVINPUT
,'' AS PLANCOMERCIALVIDAINPUT
,'' AS OPCIONVIDAINPUT
,INDPRESTAMOINPUT
FROM INTERSEGURO.POLVIDAINVERSION
)

SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
      ,TO_CHAR(COT.TIME_STAMP,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,AGR.PRODUCTID                    AS ID_PRODUCTO
      ,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
      ,(CASE WHEN COT.STATUS = 1
             THEN 'Not applied operation' 
             WHEN COT.STATUS = 2 
             THEN 'Applied operation'
             ELSE ''||COT.STATUS
      END ) AS STATUS_OPERATION
      ,POLL.*
       FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
         AND AGR.OPERATIONPK      = PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
-- DATOS DE LA POLIZA
 INNER JOIN TMP_POL_TABLA POLL
         ON POLL.PK = PRE.PK
 WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
 AND COT.STATUS = 2 