WITH TMP_DATA AS (
SELECT DISTINCT PRE.NUMEROPOLIZAINPUT, PRE.STATIC ,AGR.PRODUCTID--,AGR.TipoFinOpenitem
          FROM INTERSEGURO.PREPOLICY PRE
          INNER JOIN INTERSEGURO.POLICYDCO DCO
                  ON PRE.PK = DCO.DCOID
          INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
                 ON COT.ID     = DCO.OPERATIONPK
          INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
                 ON AGR.AGREGATEDPOLICYID = DCO.AGREGATEDOBJECTID
          INNER JOIN INTERSEGURO.PRODUCT POR
                 ON POR.PRODUCTID = AGR.PRODUCTID
          WHERE POR.PRODUCTID IN (24917,69141,69545,77869,48779,26437,44739,28837,24877,77929,68939,30437,35440,29637,27237,28037,56757,35448,27277,77989,39480,39482)
          AND NULLIF(nullif(TRIM(NUMEROPOLIZAINPUT),''),'-') is not null
)
--,MAX(NVL(OP.DATEUSERECIPENT,OP.OPENITEMDATE)) AS FECHA_PAGADO_HASTA
SELECT  --COUNT(1) AS CANTIDAD_OPENITEM
       K.NUMEROPOLIZAINPUT AS NUMERO_POLIZA 
       ,K.PRODUCTID        AS ID_PRODUCTO
       ,STCA.OPMI_DESC     AS COMPROBANTE
       ,OP.DOCDATE         AS FECHA_PAGO_INICIAL
       ,OP.AMOUNT          AS MONTO_PRIMA_PAGO
       ,OP.DATEUSERECIPENT AS FECHA_PAGADO_HASTA
     --,OP.STATUS
       --,MAX(NVL(OP.DATEUSERECIPENT,OP.OPENITEMDATE)) AS FECHA_PAGADO_HASTA
      -- ,CURRENT_DATE AS FECHA_PROCESO	
  FROM INTERSEGURO.OPENITEM  OP
  INNER JOIN INTERSEGURO.OPENITEMREFERENCE RE
        ON RE.OPENITEMID = OP.OPENITEMID
  LEFT JOIN INTERSEGURO.STCA_OPENITEMINFO STCA
        ON STCA.OPM_ID = OP.OPENITEMID 
  INNER JOIN TMP_DATA K ON RE.POLICYID = K.STATIC
 -- where DTY_ID=7572
  --WHERE OP.DTY_ID IN (7572,45052,45053)
  WHERE OP.STATUS IN ('applied','deferred')
 -- AND TIP.DTY_DESCRIPTION in ('PrimaEmitida','TraspasoCAV','TraspasoCP')
--AND OP.STATUS IN ('applied','deferred')
-- AND K.NUMEROPOLIZAINPUT ='6900004171'
--GROUP BY K.NUMEROPOLIZAINPUT ,K.PRODUCTID
  
 
  
  
  