WITH TMP_AGG AS (
SELECT  COUNT(1) AS CANTIDAD_OPENITEM
       ,SUM(AMOUNT) AS MONTO
       ,SUM(BALANCE)  AS MONTO_BALANCE
       ,OPM_MASTEROPENITEMID
  from interseguro.OPENITEM  
  where DTY_ID=7572
  GROUP BY OPM_MASTEROPENITEMID
)
SELECT DISTINCT 
 --REF.OPR_POLICYNUMBER AS NUMERO_POLIZA
OPE.OPENITEMID
--,OPE.OPERATIONPK AS NUMERO_OPERACION
--,OPE.APPLIEDTO AS OPENITEMID_APLICADO
--,OPE.THIRDPARTYID
,OPE.DTY_ID AS ID_TIPO_OPENITEM
,UPPER(TRIM(STC.DTY_DESCRIPTION)) AS TIPO_OPENITEM
,TO_CHAR(OPE.OPENITEMDATE,'YYYY-MM-DD') AS FECHA_INICIO_OPENITEM
,TO_CHAR(OPE.DOCDATE,'YYYY-MM-DD') AS FECHA_DOCUMENTO 
,TO_CHAR(OPE.DATEUSERECIPENT,'YYYY-MM-DD') AS FECHA_USO_RECIBIDO
,TO_CHAR(OPE.DUEDATE,'YYYY-MM-DD') AS FECHA_VENCIMIENTO
-- ,OPE.CURRENCYID
,OPE.AMOUNT           AS MONTO
,OPE.BALANCE          AS MONTO_BALANCE
,(CASE WHEN TRIM(LOWER(OPE.STATUS))='active' 
       THEN 'ACTIVO' 
       WHEN TRIM(LOWER(OPE.STATUS))='applied' 
       THEN 'APLICADO' 
       WHEN TRIM(LOWER(OPE.STATUS))='canceled' 
       THEN 'CANCELADO'
       ELSE 
           TRIM(UPPER(OPE.STATUS))
  END)        AS ESTADO_OPENITEM
--,TRIM(LOWER(OPE.OPM_SUBSTATUS)) AS SUBESTADO
--,OPE.REFERENCETYPE
--,OPE.SAPCURRENCYID
,MON.CCY_ISOCODE AS MONEDA_ISO
--,MON.DESCRIPTION AS MONEDA
--,OPE.ROL_ID
--,DATE(REF.OPENITEMDATE,'America/Lima') AS OPENITEMDATE
--,REF.OPENITEMREFERENCEID
--,REF.OPENITEMID
--,REF.POLICYID
--,REF.REFERENCE
--,REF.ADDITIONALREFERENCE
--,REF.PAYMENTSEQUENCE
--,REF.OPR_PRODUCTPK
,PRO.PRODUCTID  AS ID_PRODUCTO
,TRIM(UPPER(PRO.DESCRIPTION)) AS PRODUCTO
,COALESCE(AGG.CANTIDAD_OPENITEM,0) AS CANTIDAD_OPENITEM
--,AGG.
--,CURRENT_DATE('America/Lima') AS FECHA_PROCESO
      FROM INTERSEGURO.OPENITEM OPE
INNER JOIN INTERSEGURO.OPENITEMREFERENCE REF
        ON REF.OPENITEMID = OPE.OPENITEMID
INNER JOIN INTERSEGURO.STCA_DOCTYPE   STC
        ON STC.DTY_ID = OPE.DTY_ID
INNER JOIN INTERSEGURO.CURRENCY  MON
        ON MON.CURRENCYID = OPE.CURRENCYID
 LEFT JOIN INTERSEGURO.PRODUCT  PRO
        ON PRO.PRODUCTID  = REF.OPR_PRODUCTPK
LEFT JOIN TMP_AGG AGG
       ON AGG.OPM_MASTEROPENITEMID = OPE.OPENITEMID
     WHERE OPE.DTY_ID in (8132)
