WITH TMP_POL_TABLA AS (
	SELECT 
	PLANSEGVEHMODULARINPUT AS PLAN_VEHICULAR
	,CODDEPARTAMENTOINPUT AS CODIGO_DEPARTAMENTO
	,CODDISTRITOINPUT AS CODIGO_DISTRITO
	,CODPROVINCIAINPUT AS CODIGO_PROVINCIA
	,DIRECCIONINPUT AS DIRECCION
	,EMAILINPUT AS CORREO
	,FECHAACUSERECIBOINPUT AS FECHA_ACUSE_RECIBO
	,FECHAANULACIONINPUT AS FECHA_ANULACION
	,FECHALIBERACIONINPUT AS FECHA_LIBERACION
	,FECHASUSPENSIONINPUT AS FECHA_SUSPENSION
	,FECHAVENTAINPUT AS FECHA_VENTA
	,FRECUENCIAPAGOANTINPUT AS FRECUENCIA_PAGO_ANT
	,INDRENOVACIONINPUT AS INDICADOR_RENOVACION
	,NUMEROPOLIZARENOVADAINPUT AS NUMERO_POLIZA_RENOVACION
	,PK 
	,REQUIEREGPSINPUT AS REQUIERE_GPS
	,STATIC
	,STATUS
	,TELEFONOCELULARINPUT AS TELEFONO_CELULAR
	,TIPOPAGOINPUT AS TIPO_PAGO
	,VEHCEROKMINPUT AS VEHICULO_CERO_KM
	FROM INTERSEGURO.POLSEGVEHICULARMODULAR

	UNION ALL

	SELECT 
	PLANVEHICULARINPUT
	,CODDEPARTAMENTOINPUT
	,CODDISTRITOINPUT
	,CODPROVINCIAINPUT
	,DIRECCIONINPUT
	,EMAILINPUT
	,FECHAACUSERECIBOINPUT
	,FECHAANULACIONINPUT
	,FECHALIBERACIONINPUT
	,FECHASUSPENSIONINPUT
	,FECHAVENTAINPUT
	,FRECUENCIAPAGOANTINPUT
	,INDRENOVACIONINPUT
	,NUMEROPOLIZARENOVADAINPUT
	,PK
	,REQUIEREGPSINPUT
	,STATIC
	,STATUS
	,TELEFONOCELULARINPUT
	,TIPOPAGOINPUT
	,VEHCEROKMINPUT
	FROM INTERSEGURO.POLVEHICULAR
),


TEMP_URV AS (
	SELECT DISTINCT B1.OPERATIONPK
	,B1.DCOID
	,B2.SUMAASEGURADAVEHICULARINPUT  AS SUMA_ASEGURADA
	FROM INTERSEGURO.RISKUNITDCO B1
	INNER JOIN INTERSEGURO.URVEHICULAR B2 ON B2.PK = B1.DCOID

	UNION ALL

	SELECT DISTINCT B1.OPERATIONPK
	,B1.DCOID
	,B2.SUMAASEGURADAVEHICULARINPUT  
	FROM INTERSEGURO.RISKUNITDCO B1
    INNER JOIN INTERSEGURO.URSEGVEHICULARMODULAR B2 ON B2.PK = B1.DCOID
),


TMP_OA_TABLA AS (
	SELECT 
	ANOVEHICULOINPUT AS ANIO_VEHICULO
	,ASEGAPELLIDOMATERNOVEHINPUT AS ASEGURADO_APELLIDO_MATERNO
	,ASEGAPELLIDOVEHINPUT AS ASEGURADO_APELLIDO
	,ASEGFECHANACIMIENTOVEHINPUT AS ASEGURADO_FECHA_NACIMIENTO
	,ASEGNOMBREVEHINPUT AS ASEGURADO_NOMBRE
	,ASEGRAZONSOCIALVEHINPUT AS ASEGURADO_RAZON_SOCIAL
	,ASEGSEGUNDONOMBREVEHINPUT AS ASEGURADO_SEGUNDO_NOMBRE
	,ASEGSEXOVEHINPUT AS ASEGURADO_SEXO
	,COLORINPUT AS COLOR_VEHICULO
	,CORREOENDOSATARIOVEHINPUT AS CORREO_ENDOSATARIO
	,MARCAVEHICULOINPUT AS MARCA_VEHICULO
	,MODELOVEHICULOINPUT AS MODELO_VEHICULO
	,NOMBREENDOSATARIOVEHINPUT AS NOMBRE_ENDOSATARIO
	,NRODOCENDOSATARIOVEHINPUT AS NUMERO_DOCUMENTO_ENDOSATARIO
	,NUMDOCANTVEHINPUT AS NUMERO_DOCUMENTO_ANT
	,NUMDOCUMENTOIDINPUT AS NUMERO_DOCUMENTO
	,NUMDOCUMENTOIDRENOVINPUT AS NUMERO_DOCUMENTO_IND_RENOVACION
	,PK 
	,PLACAANTVEHINPUT AS PLACA_ANT
	,PLACAINPUT AS PLACA
	,PLACARENOVINPUT
	,POLIZACESIONADAVEHINPUT AS POLIZA_CESIONADA
	,STATIC
	,STATUS
	,TIPODOCANTVEHINPUT AS TIPO_DOCUMENTO_ANT
	,TIPODOCENDOSATARIOVEHINPUT AS TIPO_DOCUMENTO_ENDOSATARIO
	,TIPODOCUMENTOINPUT AS TIPO_DOCUMENTO
	,TIPODOCUMENTORENOVINPUT AS TIPO_DOCUMENTO_RENOVACION
	,USOVEHICULOINPUT AS USO_VENICULO
	,VINVEHICULOINPUT AS VIN_VEHICULO
	FROM INTERSEGURO.OASEGVEHICULARMODULAR

	UNION ALL 

	SELECT 
	ANOVEHICULOINPUT
	,ASEGAPELLIDOMATERNOVEHINPUT
	,ASEGAPELLIDOVEHINPUT
	,ASEGFECHANACIMIENTOVEHINPUT
	,ASEGNOMBREVEHINPUT
	,ASEGRAZONSOCIALVEHINPUT
	,ASEGSEGUNDONOMBREVEHINPUT
	,ASEGSEXOVEHINPUT
	,COLORINPUT
	,CORREOENDOSATARIOVEHINPUT
	,MARCAVEHICULOINPUT
	,MODELOVEHICULOINPUT
	,NOMBREENDOSATARIOVEHINPUT
	,NRODOCENDOSATARIOVEHINPUT
	,NUMDOCANTVEHINPUT
	,NUMDOCUMENTOIDINPUT
	,NUMDOCUMENTOIDRENOVINPUT
	,PK
	,PLACAANTVEHINPUT
	,PLACAINPUT AS PLACA
	,PLACARENOVINPUT AS PLACA_RENOVACION
	,POLIZACESIONADAVEHINPUT AS POLIZA_CESIONADA
	,STATIC
	,STATUS
	,TIPODOCANTVEHINPUT AS TIPO_DOCUMENTO_ANT
	,TIPODOCENDOSATARIOVEHINPUT AS TIPO_DOCUMENTO_ENDOSATARIO
	,TIPODOCUMENTOINPUT AS TIPO_DOCUMENTO
	,TIPODOCUMENTORENOVINPUT AS TIPO_DOCUMENTO_RENOVACION
	,USOVEHICULOINPUT AS USO_VEHICULO
	,VINVEHICULOINPUT AS VIN_VEHICULO
	FROM INTERSEGURO.OAVEHICULAR
)


SELECT   /*+ PARALLEL(2) */
	PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
	,PLO.OPERATIONPK                  AS NUMERO_OPERACION
	,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
	,AGR.PRODUCTID                    AS ID_PRODUCTO
	,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
	,CASE 
		WHEN COT.STATUS = 1 THEN 'Not applied operation' 
		WHEN COT.STATUS = 2 THEN 'Applied operation'
		ELSE ''||COT.STATUS
	END AS STATUS_OPERATION
	,POLL.PLAN_VEHICULAR
	,POLL.CODIGO_DEPARTAMENTO
	,POLL.CODIGO_DISTRITO
	,POLL.CODIGO_PROVINCIA
	,POLL.DIRECCION
	,POLL.CORREO
	,POLL.FECHA_ACUSE_RECIBO
	,POLL.FECHA_ANULACION
	,POLL.FECHA_LIBERACION
	,POLL.FECHA_SUSPENSION
	,POLL.FECHA_VENTA
	,POLL.FRECUENCIA_PAGO_ANT
	,POLL.INDICADOR_RENOVACION
	,POLL.NUMERO_POLIZA_RENOVACION
	,POLL.REQUIERE_GPS
	,POLL.TELEFONO_CELULAR
	,POLL.TIPO_PAGO
	,POLL.VEHICULO_CERO_KM	
	,OAS.ANIO_VEHICULO
	,OAS.ASEGURADO_APELLIDO_MATERNO
	,OAS.ASEGURADO_APELLIDO
	,OAS.ASEGURADO_FECHA_NACIMIENTO
	,OAS.ASEGURADO_NOMBRE
	,OAS.ASEGURADO_RAZON_SOCIAL
	,OAS.ASEGURADO_SEGUNDO_NOMBRE
	,OAS.ASEGURADO_SEXO
	,OAS.COLOR_VEHICULO
	,OAS.CORREO_ENDOSATARIO
	,OAS.MARCA_VEHICULO
	,OAS.MODELO_VEHICULO
	,OAS.NOMBRE_ENDOSATARIO
	,OAS.NUMERO_DOCUMENTO_ENDOSATARIO
	,OAS.NUMERO_DOCUMENTO_ANT
	,OAS.NUMERO_DOCUMENTO
	,OAS.NUMERO_DOCUMENTO_IND_RENOVACION
	,OAS.PLACA_ANT
	,OAS.PLACA
	,OAS.PLACARENOVINPUT
	,OAS.POLIZA_CESIONADA
	,OAS.TIPO_DOCUMENTO_ANT
	,OAS.TIPO_DOCUMENTO_ENDOSATARIO
	,OAS.TIPO_DOCUMENTO
	,OAS.TIPO_DOCUMENTO_RENOVACION
	,OAS.USO_VENICULO
	,OAS.VIN_VEHICULO
	,URV.SUMA_ASEGURADA
FROM INTERSEGURO.PREPOLICY PRE
INNER JOIN INTERSEGURO.POLICYDCO PLO ON PLO.DCOID = PRE.PK
INNER JOIN INTERSEGURO.CONTEXTOPERATION COT ON COT.ID = PLO.OPERATIONPK
INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT POR ON POR.PRODUCTID = AGR.PRODUCTID AND AGR.PRODUCTID IN (73989,77849)
-- DATOS DE LA POLIZA
INNER JOIN TMP_POL_TABLA POLL ON POLL.PK = PRE.PK
-- OBJETO ASEGURADO
INNER JOIN INTERSEGURO.INSURANCEOBJECTDCO IDC ON IDC.OPERATIONPK = COT.ID
INNER JOIN TMP_OA_TABLA OAS ON OAS.PK = IDC.DCOID
-- VALOR COMERCIAL
LEFT JOIN TEMP_URV URV ON URV.OPERATIONPK = PLO.OPERATIONPK
-- WHERE
WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
--AND EXTRACT(YEAR FROM COT.AUDITDATE) = 2022
--AND COT.AUDITDATE >= (CURRENT_DATE - INTERVAL '4 day')
AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN DATE_TRUNC('day', '${v_FechaInicioYYYYMMDD}'::date) AND DATE_TRUNC('day', '${v_FechaFinYYYYMMDD}'::date);
