WITH TMP_OA_TABLA AS (
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,NULL AS EDADINPUT
,PK
,STATIC
,NULL AS EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OASOAT
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAVEAVIDA
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAEXTRACASHFUNO
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAVEAACCIDENTES
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPTINDIVIDUALIBK
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,NULL AS EDADINPUT
,PK
,STATIC
,NULL AS EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OATARJETADEDEBITO
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTECCIONDEBITO
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,TARIFESPMIGRVALUE
,OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,EDADASEGVALUE
,TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,NULL AS EDADINPUT
,PK
,STATIC
,NULL AS EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OATARJETADECREDITO
UNION ALL
/*
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
FROM INTERSEGURO.OARENTAHOSPITALARIA
UNION ALL
*/
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,TARIFESPMIGRPBINPUT
,TARIFESPMIGRPBVALUE
,OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTECCIONBLINDAJE
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTECCIONCREDITOS
UNION ALL
SELECT
FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,OPCIONPLANIAVALUE
,FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NULL AS NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NULL AS NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAINTERBANKACCIDENTES
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL AS EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,NULL AS EDADMINIMAASEGMASIVOINPUT
,NULL AS EDADPERMANASEGMASIVOINPUT
,NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,NULL AS EDADMAXIMAASEGMASIVOINPUT
,NULL AS EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,NULL AS EDADMINIMAASEGMASIVOVALUE
,NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTBLINDAJEINDPLUS
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL AS OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,FECHANACIMIENTOMASIVOVALUE
,EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,EDADALCAFINPOLMASIVOSINPUT
,NULL AS OPCIONPBVALUE
,FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,NULL AS EXTRACTOANUALINPUT
,NULL AS EXTRACTOFNVALUE
,NULL AS EDADMAXPERCONEXTRACTOVALUE
,NULL AS FMOVIMIENTOINPUT
,NULL AS EDADCONEXTRACTOVALUE
,NULL AS FECHAEXTRACTOINPUT
,NULL AS FECHAEXTRACTOVALUE
,NULL AS EXTRACTOFNINPUT
,NULL AS EXTRACTOANUALVALUE
,NULL AS EDADMAXPERCONEXTRACTOINPUT
,NULL AS FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NUMPLANINTERLOCBINPUT
,NULL AS EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,NULL AS FMOVIMIENTOVALUE
,NULL AS FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTBLININDPLUSFUNO
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,NULL AS SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,EDADPERMANASEGMASIVOVALUE
,EXTRACTOANUALINPUT
,EXTRACTOFNVALUE
,EDADMAXPERCONEXTRACTOVALUE
,FMOVIMIENTOINPUT
,EDADCONEXTRACTOVALUE
,FECHAEXTRACTOINPUT
,FECHAEXTRACTOVALUE
,EXTRACTOFNINPUT
,EXTRACTOANUALVALUE
,EDADMAXPERCONEXTRACTOINPUT
,FECHANACIMIENTOSININPUT
,EDADMINIMAASEGMASIVOINPUT
,EDADPERMANASEGMASIVOINPUT
,NUMPLANINTERLOCBINPUT
,EDADCONEXTRACTOINPUT
,EDADMAXIMAASEGMASIVOINPUT
,EDADMAXIMAASEGMASIVOVALUE
,FMOVIMIENTOVALUE
,FECHANACIMIENTOSINVALUE
,EDADMINIMAASEGMASIVOVALUE
,NUMPLANINTERLOCBVALUE
,STATUS
,EDADINPUT
,PK
,STATIC
,EDADVALUE
--INI 18/12/2023 (ML) 
,NULL TIPODOCTRAMAINPUT
,NULL NUMERODOCTRAMAINPUT
,NULL NOMBREUNOASEGINPUT
,NULL NOMBREDOSASEGINPUT
,NULL APELLIDOPATERNOASEGINPUT
,NULL APELLIDOMATERNOASEGINPUT
,NULL VALORFECNACINPUT
,NULL DIRECCIONTITINPUT
,NULL DISTRITOTITINPUT
,NULL PROVINCIATITINPUT
,NULL DEPARTAMENTOTITINPUT
,NULL TELEFONODESGINPUT
,NULL SOBREPRIMADPSVALUE
,NULL EXTRAPRIMADPSVALUE
--FIN 18/12/2023 (ML) 
FROM INTERSEGURO.OAPROTECCIONBLINDAJEPLUS
--INI 18/12/2023 (ML) 
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL EDADPERMANASEGMASIVOVALUE
,NULL EXTRACTOANUALINPUT
,NULL EXTRACTOFNVALUE
,NULL EDADMAXPERCONEXTRACTOVALUE
,NULL FMOVIMIENTOINPUT
,NULL EDADCONEXTRACTOVALUE
,NULL FECHAEXTRACTOINPUT
,NULL FECHAEXTRACTOVALUE
,NULL EXTRACTOFNINPUT
,NULL EXTRACTOANUALVALUE
,NULL EDADMAXPERCONEXTRACTOINPUT
,NULL FECHANACIMIENTOSININPUT
,NULL EDADMINIMAASEGMASIVOINPUT
,NULL EDADPERMANASEGMASIVOINPUT
,NULL NUMPLANINTERLOCBINPUT
,NULL EDADCONEXTRACTOINPUT
,NULL EDADMAXIMAASEGMASIVOINPUT
,NULL EDADMAXIMAASEGMASIVOVALUE
,NULL FMOVIMIENTOVALUE
,NULL FECHANACIMIENTOSINVALUE
,NULL EDADMINIMAASEGMASIVOVALUE
,NULL NUMPLANINTERLOCBVALUE
,STATUS
,NULL EDADINPUT
,PK
,STATIC
,NULL EDADVALUE
--
,TIPODOCTRAMAINPUT
,NUMERODOCTRAMAINPUT
,NOMBREUNOASEGINPUT
,NOMBREDOSASEGINPUT
,APELLIDOPATERNOASEGINPUT
,APELLIDOMATERNOASEGINPUT
,VALORFECNACINPUT
,DIRECCIONTITINPUT
,DISTRITOTITINPUT
,PROVINCIATITINPUT
,DEPARTAMENTOTITINPUT
,TELEFONODESGINPUT
,SOBREPRIMATRAMAVALUE SOBREPRIMADPSVALUE
,EXTRAPRIMATRAMAVALUE EXTRAPRIMADPSVALUE
FROM INTERSEGURO.OADESGHIPOTECARIOIND
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL EDADPERMANASEGMASIVOVALUE
,NULL EXTRACTOANUALINPUT
,NULL EXTRACTOFNVALUE
,NULL EDADMAXPERCONEXTRACTOVALUE
,NULL FMOVIMIENTOINPUT
,NULL EDADCONEXTRACTOVALUE
,NULL FECHAEXTRACTOINPUT
,NULL FECHAEXTRACTOVALUE
,NULL EXTRACTOFNINPUT
,NULL EXTRACTOANUALVALUE
,NULL EDADMAXPERCONEXTRACTOINPUT
,NULL FECHANACIMIENTOSININPUT
,NULL EDADMINIMAASEGMASIVOINPUT
,NULL EDADPERMANASEGMASIVOINPUT
,NULL NUMPLANINTERLOCBINPUT
,NULL EDADCONEXTRACTOINPUT
,NULL EDADMAXIMAASEGMASIVOINPUT
,NULL EDADMAXIMAASEGMASIVOVALUE
,NULL FMOVIMIENTOVALUE
,NULL FECHANACIMIENTOSINVALUE
,NULL EDADMINIMAASEGMASIVOVALUE
,NULL NUMPLANINTERLOCBVALUE
,STATUS
,NULL EDADINPUT
,PK
,STATIC
,NULL EDADVALUE
--
,TIPODOCTRAMAINPUT
,NUMERODOCTRAMAINPUT
,NOMBREUNOASEGINPUT
,NOMBREDOSASEGINPUT
,APELLIDOPATERNOASEGINPUT
,APELLIDOMATERNOASEGINPUT
,VALORFECNACINPUT
,DIRECCIONTITINPUT
,DISTRITOTITINPUT
,PROVINCIATITINPUT
,DEPARTAMENTOTITINPUT
,TELEFONODESGINPUT
,SOBREPRIMATRAMAVALUE SOBREPRIMADPSVALUE
,EXTRAPRIMATRAMAVALUE EXTRAPRIMADPSVALUE
FROM INTERSEGURO.OADESGPERSONALIND
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL EDADPERMANASEGMASIVOVALUE
,NULL EXTRACTOANUALINPUT
,NULL EXTRACTOFNVALUE
,NULL EDADMAXPERCONEXTRACTOVALUE
,NULL FMOVIMIENTOINPUT
,NULL EDADCONEXTRACTOVALUE
,NULL FECHAEXTRACTOINPUT
,NULL FECHAEXTRACTOVALUE
,NULL EXTRACTOFNINPUT
,NULL EXTRACTOANUALVALUE
,NULL EDADMAXPERCONEXTRACTOINPUT
,NULL FECHANACIMIENTOSININPUT
,NULL EDADMINIMAASEGMASIVOINPUT
,NULL EDADPERMANASEGMASIVOINPUT
,NULL NUMPLANINTERLOCBINPUT
,NULL EDADCONEXTRACTOINPUT
,NULL EDADMAXIMAASEGMASIVOINPUT
,NULL EDADMAXIMAASEGMASIVOVALUE
,NULL FMOVIMIENTOVALUE
,NULL FECHANACIMIENTOSINVALUE
,NULL EDADMINIMAASEGMASIVOVALUE
,NULL NUMPLANINTERLOCBVALUE
,STATUS
,NULL EDADINPUT
,PK
,STATIC
,NULL EDADVALUE
--
,TIPODOCTRAMAINPUT
,NUMERODOCTRAMAINPUT
,NOMBREUNOASEGINPUT
,NOMBREDOSASEGINPUT
,APELLIDOPATERNOASEGINPUT
,APELLIDOMATERNOASEGINPUT
,VALORFECNACINPUT
,DIRECCIONTITINPUT
,DISTRITOTITINPUT
,PROVINCIATITINPUT
,DEPARTAMENTOTITINPUT
,TELEFONODESGINPUT
,SOBREPRIMATRAMAVALUE SOBREPRIMADPSVALUE
,EXTRAPRIMATRAMAVALUE EXTRAPRIMADPSVALUE
FROM INTERSEGURO.OADESGVEHICULARIND
UNION ALL
SELECT
NULL AS FECHALIMITEEDADVALUE
,NULL AS TARIFESPMIGRVALUE
,NULL AS OPCIONPLANVALUE
,NULL AS NUMPLANINTERLOCVALUE
,NULL AS PLACAOAVALUE
,NULL AS EDADASEGINPUT
,NULL AS TARIFESPMIGRPBINPUT
,NULL AS TARIFESPMIGRPBVALUE
,NULL OPCIONPBINPUT
,NULL AS TARIFESPMIGRPDVALUE
,NULL AS FECHANACIMIENTOMASIVOVALUE
,NULL AS EDADALCAFINPOLMASIVOSVALUE
,NULL AS PLACAOAINPUT
,SEXOINPUT
,NULL AS OPCIONPLANIAINPUT
,NULL AS NUMPLANINTERLOCINPUT
,NULL AS SEXOVALUE
,NULL AS OPCIONPLANIAVALUE
,NULL AS FECHALIMITEEDADINPUT
,NULL AS EDADALCAFINPOLMASIVOSINPUT
,NULL OPCIONPBVALUE
,NULL AS FECHANACIMIENTOMASIVOINPUT
,NULL AS EDADASEGVALUE
,NULL AS TARIFESPMIGRINPUT
,NULL AS TARIFESPMIGRPDINPUT
,NULL AS OPCIONPLANINPUT
,NULL EDADPERMANASEGMASIVOVALUE
,NULL EXTRACTOANUALINPUT
,NULL EXTRACTOFNVALUE
,NULL EDADMAXPERCONEXTRACTOVALUE
,NULL FMOVIMIENTOINPUT
,NULL EDADCONEXTRACTOVALUE
,NULL FECHAEXTRACTOINPUT
,NULL FECHAEXTRACTOVALUE
,NULL EXTRACTOFNINPUT
,NULL EXTRACTOANUALVALUE
,NULL EDADMAXPERCONEXTRACTOINPUT
,NULL FECHANACIMIENTOSININPUT
,NULL EDADMINIMAASEGMASIVOINPUT
,NULL EDADPERMANASEGMASIVOINPUT
,NULL NUMPLANINTERLOCBINPUT
,NULL EDADCONEXTRACTOINPUT
,NULL EDADMAXIMAASEGMASIVOINPUT
,NULL EDADMAXIMAASEGMASIVOVALUE
,NULL FMOVIMIENTOVALUE
,NULL FECHANACIMIENTOSINVALUE
,NULL EDADMINIMAASEGMASIVOVALUE
,NULL NUMPLANINTERLOCBVALUE
,STATUS
,NULL EDADINPUT
,PK
,STATIC
,NULL EDADVALUE
--
,TIPODOCTRAMAINPUT
,NUMERODOCTRAMAINPUT
,NOMBREUNOASEGINPUT
,NOMBREDOSASEGINPUT
,APELLIDOPATERNOASEGINPUT
,APELLIDOMATERNOASEGINPUT
,VALORFECNACINPUT
,DIRECCIONTITINPUT
,DISTRITOTITINPUT
,PROVINCIATITINPUT
,DEPARTAMENTOTITINPUT
,TELEFONODESGINPUT
,SOBREPRIMATRAMAVALUE SOBREPRIMADPSVALUE
,EXTRAPRIMATRAMAVALUE EXTRAPRIMADPSVALUE
FROM INTERSEGURO.OAREFINANCIADOIND
--FIN 18/12/2023 (ML) 
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
      ,TO_CHAR(COT.TIME_STAMP,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,AGR.PRODUCTID                    AS ID_PRODUCTO
      ,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
      ,(CASE WHEN COT.STATUS = 1
             THEN 'Not applied operation' 
             WHEN COT.STATUS = 2 
             THEN 'Applied operation'
             ELSE ''||COT.STATUS
      END ) AS STATUS_OPERATION
      ,PL.PLANID AS ID_PLAN
      ,PL.DESCRIPTION AS DESCRIPCION_PLAN
      ,OAS.*
      --INI 18/12/2023 (ML) 
      ,PREI.NUMEROOBJETOASEGINPUT
      --FIN 18/12/2023 (ML)          
       FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.INSURANCEOBJECTDCO IDC 
                 ON IDC.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_OA_TABLA OAS
         ON OAS.PK = IDC.DCOID
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PRE.STATIC
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 LEFT JOIN INTERSEGURO.PLAN PL
        ON IDC.PLANID =PL.PLANID 
 --INI 18/12/2023 (ML) 
 INNER JOIN INTERSEGURO.PREINSUREDOBJECT PREI
        ON IDC.DCOID = PREI.PK
 --FIN 18/12/2023 (ML)                   
 WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
         --AND PRE.NUMEROPOLIZAINPUT ='5000001-002749907'
                 --- AND COT.AUDITDATE >= (CURRENT_DATE-60)
         AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');