SELECT DISTINCT
   OPE.OPENITEMID
  ,OPE.THIRDPARTYID
  ,OPE.DTY_ID
  ,OPE.OPENITEMDATE
  ,OPE.DOCDATE
  ,OPE.DATEUSERECIPENT
  ,OPE.DUEDATE
  ,OPE.APPLIEDTO
  ,OPE.PARENTOPENITEMID
  ,OPE.CURRENCYID
  ,OPE.AMOUNT
  ,OPE.BALANCE
  ,OPE.STATUS
  ,OPE.OPERATIONPK
  ,OPE.REFERENCETYPE
  ,OPE.SAPCURRENCYID
  ,OPE.OPM_SUBSTATUS
  ,OPE.OPM_MASTEROPENITEMID
  ,OPE.ROL_ID
  ,DOO.DTY_DESCRIPTION
  ,REE.OPENITEMREFERENCEID
  ,REE.POLICYID
  ,REE.RISKUNITID
  ,REE.REFERENCE
  ,REE.ADDITIONALREFERENCE
  ,REE.PAYMENTSEQUENCE
  ,REE.OPR_POLICYNUMBER
  ,REE.OPR_RISKUNITNUMBER
  ,REE.OPR_CLAIMNUMBER
  ,REE.OPR_RECOVERYNUMBER
  ,REE.PGC_CATEGORY
  ,REE.OPR_PRODUCTPK
  ,REE.CIOP_ID
  ,REE.OPR_COMPONENTID
  ,REE.AGV_ID
  ,REE.OPR_RCIN_ID
  ,REE.RCO_ID
  ,REE.ROP_ID
FROM INTERSEGURO.OPENITEM OPE
INNER JOIN INTERSEGURO.STCA_DOCTYPE DOO
        ON OPE.DTY_ID = DOO.DTY_ID
INNER JOIN INTERSEGURO.OPENITEMREFERENCE REE
        ON REE.OPENITEMID = OPE.OPENITEMID
INNER JOIN INTERSEGURO.STCA_OPENITEMHISTORY OH
	    ON OPE.OPENITEMID = OH.OPM_ID  
WHERE OPE.DOCDATE <= '1999-12-31'
