WITH TMP_UNIDAD_RIESGO AS (
    SELECT 
        'URVIDAFREE' AS TABLA_FUENTE,
        PK,
        PERIODOPAGOPRIMAINPUT,
        CAPITALASEGURADOINPUT,
        CAPITALASEGANTVFINPUT,
        PORCDEVPRIMASFINALINPUT,
        SUMAASEGURADASEGTRAMOINPUT,
        URPRIMAANUALINPUT,
        URPRIMAFPINPUT
    FROM INTERSEGURO.URVIDAFREE
    UNION ALL
    SELECT 
        'URVIDACASH' AS TABLA_FUENTE,
        PK,
        PERIODOPAGOPRIMAINPUT,
        CAPITALASEGURADOINPUT,
        '' AS CAPITALASEGANTVFINPUT,
        PORCDEVPRIMASFINALINPUT,
        SUMAASEGURADASEGTRAMOINPUT,
        URPRIMAANUALINPUT,
        URPRIMAFPINPUT
    FROM INTERSEGURO.URVIDACASH
    UNION ALL
    SELECT 
        'URVIDACASHSTOCK' AS TABLA_FUENTE,
        PK,
        PERIODOPAGOPRIMAINPUT,
        CAPITALASEGURADOINPUT,
        '' AS CAPITALASEGANTVFINPUT,
        PORCDEVPRIMASFINALINPUT,
        SUMAASEGURADASEGTRAMOINPUT,
        URPRIMAANUALINPUT,
        URPRIMAFPINPUT
    FROM INTERSEGURO.URVIDACASHSTOCK
)
SELECT 
    /*+ PARALLEL(2) */
    PRE.NUMEROPOLIZAINPUT AS NUMERO_POLIZA,
    PLO.OPERATIONPK AS NUMERO_OPERACION,
    TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE,
    AGR.PRODUCTID AS ID_PRODUCTO,
    TRIM(UPPER(POR.DESCRIPTION)) AS NOMBRE_PRODUCTO,
    CASE 
        WHEN COT.STATUS = 1 THEN 'Not applied operation' 
        WHEN COT.STATUS = 2 THEN 'Applied operation'
        ELSE ''||COT.STATUS
    END AS STATUS_OPERATION,
    RIS.AGREGATEDOBJECTID,
    RIS.STATEID,
    SAA.DESCRIPTION AS ESTADO_UND_RIESGO,
    TO_CHAR(RIS.INITIALDATE,'YYYY-MM-DD') AS INITIALDATE,
    TO_CHAR(RIS.FINISHDATE,'YYYY-MM-DD') AS FINISHDATE,
    TO_CHAR(RIS.TIME_STAMP,'YYYY-MM-DD') AS TIME_STAMP,
    TO_CHAR(RIS.AUDITDATE,'YYYY-MM-DD') AS AUDITDATE,
    RIS.IDDCOEVENT,
    RIS.AGREGATEDPARENTID,
    RIS.STATUS,
    RIS.RUD_VALIDITY,
    URR.TABLA_FUENTE,
    URR.PERIODOPAGOPRIMAINPUT,
    URR.CAPITALASEGURADOINPUT,
    URR.CAPITALASEGANTVFINPUT,
    URR.PORCDEVPRIMASFINALINPUT,
    URR.SUMAASEGURADASEGTRAMOINPUT,
    URR.URPRIMAANUALINPUT,
    URR.URPRIMAFPINPUT
FROM 
    INTERSEGURO.PREPOLICY PRE
INNER JOIN 
    INTERSEGURO.POLICYDCO PLO ON PLO.DCOID = PRE.PK
INNER JOIN 
    INTERSEGURO.CONTEXTOPERATION COT ON COT.ID = PLO.OPERATIONPK
INNER JOIN 
    INTERSEGURO.AGREGATEDPOLICY AGR ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
INNER JOIN 
    INTERSEGURO.PRODUCT POR ON POR.PRODUCTID = AGR.PRODUCTID
INNER JOIN 
    INTERSEGURO.RISKUNITDCO RIS ON RIS.OPERATIONPK = COT.ID --PLO.OPERATIONPK
INNER JOIN 
    TMP_UNIDAD_RIESGO URR ON URR.PK = RIS.DCOID
INNER JOIN 
    INTERSEGURO.STATE SAA ON SAA.STATEID = RIS.STATEID
WHERE 
    PRE.NUMEROPOLIZAINPUT IS NOT NULL
    AND AGR.PRODUCTID IN (77909,77969,77949);
