SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
      ,AGR.PRODUCTID                    AS ID_PRODUCTO
      ,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
,CLA.CLAIMNUMBER AS NUMERO_SINIESTRO
,TRIM(UPPER(EC.DESCRIPTION))  AS CAUSA_SINIESTRO
,TO_CHAR(CLA.POLICYDATE,'YYYY-MM-DD HH24:MI:SS') AS FECHA_SINIESTRO
,TO_CHAR(CLA.CLAIMDATE,'YYYY-MM-DD HH24:MI:SS')  AS FECHA_CREACION_SINIESTRO
,CLA.CLAIMID
--,COJ.DAMAGEDCOID
--,UPPER(TYP.DESCRIPTION) AS DESCRIPCION_ADICIONAL_SINIESTRO
--,PAY.BENEFICIARY AS NOMBRE_BENEFICIARIO_SINIESTRADO
,CLA.STATE  AS ESTADO_SINIESTRO
,(CASE CLA.STATE WHEN 0 THEN 'ABIERTO'
                 WHEN 1 THEN 'CERRADO' 
                 WHEN 2 THEN 'RECHAZADO' 
                 WHEN 3 THEN 'CANCELADO'
                 WHEN 4 THEN 'REABIERTO' 
                 WHEN 5 THEN 'PENDIENTE' 
                 WHEN 6 THEN 'PAGADO'
                 WHEN 7 THEN 'APROBACIONPENDIENTE'
                 ELSE 'NO DEFINIDO' END) AS ESTADO_SINIESTRO_GLOSA
,POR.PAYMENTORDERID
,POR.DONEBY
,POR.BENEFICIARY AS NOMBRE_BENEFICIARIO
,OI.OPENITEMID 
,LIQ.POR_ID
,TO_CHAR(OI.OPENITEMDATE ,'YYYY-MM-DD HH24:MI:SS') AS OPENITEMDATE
,POR.DATEPAYMENTORDER
,POR.AMOUNT AS MONTO_PAGO
,POR.COVERAGEDESC AS COBERTURA
,POR.THIRDPARTYID 
,TO_CHAR(OI.DUEDATE,'YYYY-MM-DD HH24:MI:SS')  AS FECHA_PAGO
,OI.STATUS
,POR.FKRESERVE AS ID_RESERVA
--,TMP.*
       FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
        AND COT.STATUS=2
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.CLAIM CLA
         ON CLA.POLICYID = AGR.AGREGATEDPOLICYID 
 INNER JOIN INTERSEGURO.CLAIMPAYMENT CP 
         ON CP.CLAIMID = CLA.CLAIMID
 INNER JOIN INTERSEGURO.PAYMENTORDER POR
         ON CP.CLAIMPAYMENTID = POR.CPY_ID
 LEFT JOIN INTERSEGURO.STCL_PAYMENTLIQUIDATION LIQ 
         ON POR.PAYMENTORDERID = LIQ.POR_ID
 LEFT JOIN INTERSEGURO.OPENITEM OI 
         ON LIQ.OPM_ID = OI.OPENITEMID        
 LEFT JOIN INTERSEGURO.EVENTCLAIM EC
         ON EC.PK = CLA.EVENTCLAIMID
  --LEFT JOIN TMP_DATA TMP
  --       ON TMP.CLAIM_ID = CLA.CLAIMID
  --       ON TMP.PK = COJ.DAMAGEDCOID
WHERE PRE.NUMEROPOLIZAINPUT  IS NOT NULL