SELECT 
REPLACE(TDC.PRODUCCTORRCVALUE,'.0','') AS ID_PRODUCTO
,UPPER(TDC.PRODUCCTORRCINPUT) AS NOMBRE_PRODUCTO
,TDC.CANALVENTARRCINPUT AS ID_CANAL
,TDC.CENTROCOSTORRCINPUT AS CENTRO_COSTO
,UPPER(TDC.MONEDATDINPUT ) AS MONEDA
,TO_NUMBER(TDC.MONEDATDVALUE,'999999.999') ID_MONEDA
,TDC.*
FROM INTERSEGURO.TDMAESTRORRC TDC
WHERE TDC.dcrrcinput = 'C'