WITH TMP_POL_TABLA AS (
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,POLD.FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,POLD.SUBPRODUCTOPLANINPUT
        ,POLD.TIPOPOLIZAHIPINPUT
        ,POLD.TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,POLD.PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,POLD.NOMBREUNOTRAMAINPUT
        ,POLD.NOMBREDOSTRAMAINPUT
        ,POLD.APELLIDOUNOTRAMAINPUT
        ,POLD.APELLIDODOSTRAMAINPUT
        ,POLD.TIPODOCTRAMAINPUT
        ,POLD.NUMERODOCTRAMAINPUT
        ,POLD.FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,POLD.DIRECCIONTRAMAINPUT
        ,POLD.TIPODOCDESGTRAMAINPUT
        --
        ,NULL PRESTAMOINICIALTRAMAVALUE
        ,NULL PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,NULL TASATRAMAVALUE
        ,NULL SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGTARJETASIND POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,POLD.POLIZAELECTRONICAINPUT
        ,POLD.TIPOCREDITOINDINPUT
        ,POLD.SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGPERSONALIND POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,POLD.POLIZAELECTRONICAINPUT
        ,POLD.TIPOCREDITOINDINPUT
        ,POLD.SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGVEHICULARIND POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,POLD.POLIZAELECTRONICAINPUT
        ,POLD.TIPOCREDITOINDINPUT
        ,POLD.SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLREFINANCIADOIND POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,POLD.POLIZAELECTRONICAINPUT
        ,POLD.TIPOCREDITOINDINPUT
        ,POLD.SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGHIPOTECARIOIND POLD
------<INI 23/02/2024 ML>
UNION ALL  
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGHIPOTECARIO POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGPERSONAL POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLDESGVEHICULAR POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLREFINANCIADOIND POLD
UNION ALL
SELECT POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,NULL FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,NULL SUBPRODUCTOPLANINPUT
        ,NULL TIPOPOLIZAHIPINPUT
        ,NULL TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,NULL PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,NULL NOMBREUNOTRAMAINPUT
        ,NULL NOMBREDOSTRAMAINPUT
        ,NULL APELLIDOUNOTRAMAINPUT
        ,NULL APELLIDODOSTRAMAINPUT
        ,NULL TIPODOCTRAMAINPUT
        ,NULL NUMERODOCTRAMAINPUT
        ,NULL FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,NULL DIRECCIONTRAMAINPUT
        ,NULL TIPODOCDESGTRAMAINPUT
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,NULL POLIZAELECTRONICAINPUT
        ,NULL TIPOCREDITOINDINPUT
        ,NULL SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
FROM INTERSEGURO.POLREFINANCIADOCONV POLD
------<FIN 23/02/2024 ML>
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PDC.OPERATIONPK                  AS NUMERO_OPERACION
      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
      ,TO_CHAR(COT.TIME_STAMP,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,AGE.PRODUCTID                    AS ID_PRODUCTO
      ,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
      ,(CASE WHEN COT.STATUS = 1
             THEN 'Not applied operation' 
             WHEN COT.STATUS = 2 
             THEN 'Applied operation'
             ELSE ''||COT.STATUS
      END ) AS STATUS_OPERATION
        ,POLD.PK
        ,POLD.NIVELAGRUPREASEGINPUT
        ,POLD.SALDOINSOLUTOINPUT
        ,POLD.CODINTERMEDIARIOINPUT
        ,POLD.GASADMINCANPINPUT
        ,POLD.FECHAVENTAINPUT
        ,POLD.CODAGENTIENOFIINPUT
        ,POLD.PROVEEDORDIGITINPUT
        ,POLD.FECHANACIMIENTOASISTINPUT
        ,POLD.FECHAANULFUTUROINPUT
        ,POLD.CODVENDEDORINPUT
        ,POLD.SIMBOLOMONEDASININPUT
        ,POLD.SIMBOLOMONEDAPLSININPUT
        ,POLD.PRODDESGRAVAMENINPUT
        ,POLD.SUBPRODUCTOPLANINPUT
        ,POLD.TIPOPOLIZAHIPINPUT
        ,POLD.TIPOASEGURADOINPUT
        ,POLD.CODIGOUNICOCLIENTEINPUT
        ,POLD.NUMEROCREDITOTRAMAINPUT
        ,POLD.PRESTAMOINICIALTRAMAINPUT
        ,POLD.TASATRAMAINPUT
        ,POLD.PRIMACALCULADADESGINPUT
        ,POLD.NUMEROCUOTATRAMAINPUT
        ,POLD.NOMBREUNOTRAMAINPUT
        ,POLD.NOMBREDOSTRAMAINPUT
        ,POLD.APELLIDOUNOTRAMAINPUT
        ,POLD.APELLIDODOSTRAMAINPUT
        ,POLD.TIPODOCTRAMAINPUT
        ,POLD.NUMERODOCTRAMAINPUT
        ,POLD.FNACTRAMAINPUT
        ,POLD.PERIODOBASEINPUT
        ,POLD.DIRECCIONTRAMAINPUT
        ,POLD.TIPODOCDESGTRAMAINPUT                     
        ,STA.DESCRIPTION AS ESTADO_POLIZA
        --
        ,POLD.PRESTAMOINICIALTRAMAVALUE
        ,POLD.PLAZOTRAMAINPUT
        ,POLD.POLIZAELECTRONICAINPUT
        ,POLD.TIPOCREDITOINDINPUT
        ,POLD.SALDOINSOLUTOANTINPUT
        ,POLD.TASATRAMAVALUE
        ,POLD.SALDOINSOLUTOVALUE
      FROM INTERSEGURO.PREPOLICY PRE
INNER JOIN TMP_POL_TABLA POLD
                ON PRE.PK = POLD.PK
INNER JOIN INTERSEGURO.POLICYDCO PDC
        ON PDC.DCOID  = PRE.PK
INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PDC.OPERATIONPK
INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGE
        ON AGE.AGREGATEDPOLICYID = PDC.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT POR
        ON POR.PRODUCTID = AGE.PRODUCTID
       AND POR.PRODUCTID IN (73585, 61263, 61061, 77827, 60859, 35442, 35450, 35445, 77828)
INNER JOIN INTERSEGURO.STATE STA 
        ON STA.STATEID = PDC.STATEID
     WHERE NULLIF(TRIM(PRE.NUMEROPOLIZAINPUT),'') IS NOT NULL
	AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
