SELECT /*+ PARALLEL(2) */
    PRE.NUMEROPOLIZAINPUT AS NUMERO_POLIZA,
    PDC.OPERATIONPK AS NUMERO_OPERACION,
    TO_CHAR(COT.AUDITDATE, 'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE,
    TO_CHAR(COT.TIME_STAMP, 'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME,
    AGE.PRODUCTID AS ID_PRODUCTO,
    TRIM(UPPER(POR.DESCRIPTION)) AS NOMBRE_PRODUCTO,
    CASE
        WHEN COT.STATUS = 1 THEN 'Not applied operation'
        WHEN COT.STATUS = 2 THEN 'Applied operation'
        ELSE '' || COT.STATUS
    END AS STATUS_OPERATION,
    INS.THIRDPARTYID,
    INS.ROL_ID,
    INS.DESCRIPTION,
    STA.DESCRIPTION AS ESTADO_POLIZA
FROM
    INTERSEGURO.PREPOLICY PRE
INNER JOIN INTERSEGURO.POLICYDCO PDC ON PDC.DCOID = PRE.PK
INNER JOIN INTERSEGURO.CONTEXTOPERATION COT ON COT.ID = PDC.OPERATIONPK
INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGE ON AGE.AGREGATEDPOLICYID = PDC.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT POR ON POR.PRODUCTID = AGE.PRODUCTID
INNER JOIN INTERSEGURO.STATE STA ON STA.STATEID = PDC.STATEID
INNER JOIN INTERSEGURO.STPO_POLICYPARTICIPATION INS ON INS.OPERATIONPK = COT.ID
WHERE
    NULLIF(TRIM(PRE.NUMEROPOLIZAINPUT), '') IS NOT NULL
    AND INS.ROL_ID = 8355
    AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
