SELECT * 
FROM 
(
	SELECT DISTINCT
		PRE.NUMEROPOLIZAINPUT 											AS NUMERO_POLIZA,
		PRE.FECHAEMISIONINPUT											AS FECHA_EMISION,
		TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM')				AS AUDITDATE_SYSTEM_DATE,
		POR.DESCRIPTION													AS PRODUCTO,
		PRE.NUMEROSOLICITUDINPUT										AS NUMERO_SOLICITUD,
		MIN(COT.TIME_STAMP) 											AS FECHA_SOLICITUD,
		MIN(COT.USER_NAME) 												AS USUARIO_SOLICITUD,
		MAX(COT.INITIAL_DATE)											AS FECHA_APROBACION, /* TODO */		
		MAX(COT.USER_NAME)												AS USUARIO_APROBACION, /* TODO */
		MIN(
			COALESCE(
				EAC.FECHAEFECTIVAINPUT,ESU.FECHAEFECTIVAINPUT
				,EFX.FECHAEFECTIVAINPUT,EVC.FECHAEFECTIVAINPUT
				,EFR.FECHAEFECTIVAINPUT,EVI.FECHAEFECTIVAINPUT
					)
			)															AS FECHA_EFECTIVA,	
		MAX(
			COALESCE(
				EAC.TIPOENDOSOPOLINPUT,ESU.TIPOENDOSOPOLINPUT
				,EFX.TIPOENDOSOPOLINPUT,EVC.TIPOENDOSOPOLINPUT
				,EFR.TIPOENDOSOPOLINPUT,EVI.TIPOENDOSOPOLINPUT
					)
			)															AS TIPO_ENDOSO,
		STRING_AGG(X.TTL_VALUE::TEXT, ',')	AS MOTIVO_ENDOSO,
		MAX(
			CASE
				WHEN EVE.DESCRIPTION = 'AprobarEndoso' 		THEN 'Aprobado'
				WHEN EVE.DESCRIPTION = 'DesistirEndoso' 	THEN 'Desistido'
				WHEN EVE.DESCRIPTION = 'EndosarEfectivo'	THEN 'Efectivo'
				WHEN EVE.DESCRIPTION = 'RechazarEndoso'		THEN 'Rechazado'
				WHEN EVE.DESCRIPTION = 'SolicitarEndoso' 	THEN 'Solicitado'
			END
		)																AS ESTADO_ENDOSO,
		MAX(EVE.DESCRIPTION) 											AS EVENTO,
		MAX(COT.AUDITDATE) OVER(ORDER BY COT.AUDITDATE DESC)			AS FECHA_EVENTO,
 	 	MAX(
	 	    COALESCE(ESU.NROMESESDIFERIDOSTOTALINPUT
				,EVC.NROMESESDIFERIDOSTOTALINPUT
				,EFR.NROMESESDIFERIDOSTOTALINPUT,EVI.NROMESESDIFERIDOSTOTALINPUT)
		   ) AS  MESES_DIFERIDOS,
		/*MAX(
			COALESCE(
				EAC.LOGINUSUARIOINPUT,ESU.LOGINUSUARIOINPUT
				,EFX.LOGINUSUARIOINPUT,EVC.LOGINUSUARIOINPUT
				,EFR.LOGINUSUARIOINPUT,EVI.TIPOENDOSOPOLINPUT
					)
			)															AS USUARIO_EVENTO,*/ /* TODO */
		MAX(COT.USER_NAME) 												AS USUARIO_EVENTO,
		MAX(PRE.FRECUENCIAPAGOINPUT)									AS FRECUENCIA_PAGO,
		MAX(THI.AMMOUNT)												AS PRIMA_NETA, 	/* TODO */	
		MAX(TIA.AMMOUNT)												AS PRIMA_TOTAL, 	/* TODO */
		MAX(PRE.NOMCOMASEGURADOPOLINPUT)								AS CONTRATANTE,
		MAX(PLO.FINISHDATE) 											AS FECHA_FIN_ANT,
	--	MAX(PLO.FINISHDATE) + MAX(EVI.NROMESESDIFERIDOSTOTALINPUT)      AS FIN_VIGENCIA,
		MAX(PRE.STATIC)													AS IDPOLIZA,
		MAX(PLO.OPERATIONPK)											AS IDOPERACION,
		ROW_NUMBER () OVER 
			(PARTITION BY PRE.NUMEROSOLICITUDINPUT 
			ORDER BY COT.AUDITDATE DESC) AS rn

	FROM INTERSEGURO.PREPOLICY PRE
	INNER JOIN INTERSEGURO.POLICYDCO PLO
		ON PLO.DCOID = PRE.PK
							
	INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
		ON COT.ID =PLO.OPERATIONPK
	
	INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
		ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
	
	INNER JOIN INTERSEGURO.PRODUCT POR
		ON POR.PRODUCTID = AGR.PRODUCTID
	
	LEFT JOIN INTERSEGURO.EVENTDCO EVD
		ON EVD.OPERATIONPK = PLO.OPERATIONPK
		
	LEFT JOIN INTERSEGURO.EVENTTYPE EVE
		ON EVE.EVENTTYPEID= EVD.EVENTTYPEID

	LEFT JOIN INTERSEGURO.THIRDPARTYMOVEMENTPOLICY THI
		ON THI.OPERATIONPK=PLO.OPERATIONPK
		AND THI.POLICYID =AGR.AGREGATEDPOLICYID
		AND TRIM(THI.CONCEPT) ='PrimaNeta'	

	LEFT JOIN INTERSEGURO.THIRDPARTYMOVEMENTPOLICY TIA
		ON TIA.OPERATIONPK=PLO.OPERATIONPK
		AND TIA.POLICYID =AGR.AGREGATEDPOLICYID
		AND TRIM(TIA.CONCEPT) ='PrimaTotalAnual'
		
	INNER JOIN INTERSEGURO.STATE STA
		ON STA.STATEID = PLO.STATEID

	/* MIR ENDOSOS */

	LEFT JOIN INTERSEGURO.COTPROPERTY Cx
		ON EVE.EVENTFORMTYPEID = Cx.COTPROPERTYID

	INNER JOIN INTERSEGURO.Configurableobjecttype Cco 
		ON Cco.Configurableobjecttypeid = Cx.Cotpropertyid

	INNER JOIN INTERSEGURO.Property Pr 
		ON Pr.Propertyid = Cx.Propertyid 
		--> NO TRAER 
	LEFT JOIN INTERSEGURO.ENDOSARACC EAC
		ON EAC.PK = EVD.IDDCOEVENT

	LEFT JOIN INTERSEGURO.ENDOSARSURA ESU
		ON ESU.PK = EVD.IDDCOEVENT

	LEFT JOIN INTERSEGURO.ENDOSARFLEX EFX
		ON EFX.PK = EVD.IDDCOEVENT
		
	LEFT JOIN INTERSEGURO.ENDOSARVCASH EVC
		ON EVC.PK = EVD.IDDCOEVENT
		
	LEFT JOIN INTERSEGURO.ENDOSARVF EFR
		ON EFR.PK = EVD.IDDCOEVENT
		
	LEFT JOIN INTERSEGURO.ENDOSARVIDA EVI
		ON EVI.PK = EVD.IDDCOEVENT
		--> NO TRAER 
	LEFT JOIN INTERSEGURO.Transformadorfila F
		ON F.Propertyid = Pr.Propertyid
        --Se comento la linea 128 y se agrego la linea 130  (ALLOYDB)
		--AND  INSTR(COALESCE(
        AND  POSITION(COALESCE(
				EAC.ENDOSOSIMPLEACCINPUT,ESU.ENDOSOSSIMPLESSACSURAINPUT,
				EFX.ENDOSOSSIMPLESSACFLEXINPUT,EVC.ENDOSOSSIMPLESSACVCASHINPUT,
				EFR.ENDOSOSSIMPLESSACVFINPUT,EVI.ENDOSOSSIMPLESSACINPUT
                --Se comento la linea 135 y se agrego la linea 136  (ALLOYDB)
				--),F.DESCRIPTION) > 0
                ) IN F.DESCRIPTION) > 0

	LEFT JOIN INTERSEGURO_GU.Cdtr_Propertytranslation Pp
		ON Pr.Simbolo = Pp.Ptl_Name
		AND Pp.Ptl_Language In ('es','(d)')
		
	LEFT JOIN INTERSEGURO_GU.cdtr_propertytloptional ppp
		ON pp.ptl_name = ppp.ptlo_name
		AND pp.ptl_language = ppp.ptlo_language
		
	INNER JOIN INTERSEGURO_GU.Cdtr_Transformertranslation X
		ON F.Transformadorfilaid = X.Trf_Id
		AND F.Description = X.Ttl_Name
		AND X.Ttl_Language = Pp.Ptl_Language
		AND X.TTL_VALUE is not NULL
		AND length(X.TTL_VALUE) > 6
		
	WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
    AND COT.STATUS <> 3
	 --  AND PRE.NUMEROPOLIZAINPUT='130603'
		AND EVE.DESCRIPTION IN ('AprobarEndoso','DesistirEndoso','EndosarEfectivo','RechazarEndoso','SolicitarEndoso')
		--AND (COT.AUDITDATE BETWEEN TRUNC(SYSDATE) - 90 AND TRUNC(SYSDATE))
--> Se comento la linea 155 y se agrego la linea 156
--       AND (TRUNC(COT.AUDITDATE,'DD') BETWEEN TRUNC(TO_DATE('${v_FechaInicioYYYYMMDD}','YYYYMMDD'),'DD') AND TRUNC(TO_DATE('${v_FechaFinYYYYMMDD}','YYYYMMDD'),'DD') )
AND COT.AUDITDATE BETWEEN CAST('${v_FechaInicioYYYYMMDD}'||' 00:00:00' AS timestamp) AND CAST('${v_FechaFinYYYYMMDD}'||' 23:59:59' AS timestamp)
--> ??? --> DONDE CORRE 
	GROUP BY
		PRE.NUMEROPOLIZAINPUT
		,PRE.FECHAEMISIONINPUT
		,COT.AUDITDATE
		,POR.DESCRIPTION
		,PRE.NUMEROSOLICITUDINPUT
) TMP --Se agrego el alias al SELECT (ALLOYDB)
WHERE rn = 1
