SELECT DISTINCT
PRE.NUMEROPOLIZAINPUT             AS NUMERO_POLIZA
,PRE.STATIC                       AS ID_POLIZA
,UPPER(POR.DESCRIPTION )          AS NOMBRE_PRODUCTO
--,TO_CHAR(Q.WQUO_APPLIEDDATE  ,'YYYY-MM-DD') AS FECHA_APLICADA_
--,TO_CHAR(Q.WQUO_SCHEDULEDDATE ,'YYYY-MM-DD HH24:MI:SS') AS FECHA_PROGRAMADA_
,Q.WQUO_NUMQUOTA      AS NUMERO_CUOTA
,Q.WQUO_SCHEDULEDTYPE AS TIPO_PROGRAMACION
,Q.WQUO_APPLIEDDATE   AS FECHA_APLICADA 
,Q.WQUO_SCHEDULEDDATE AS FECHA_PROGRAMADA
FROM INTERSEGURO.STPO_WILDCARDQUOTA Q
INNER JOIN INTERSEGURO.PREPOLICY PRE 
        ON Q.APO_ID=PRE.STATIC
INNER JOIN INTERSEGURO.POLICYDCO PLO
        ON PLO.DCOID = PRE.PK
INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
        ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT POR
        ON POR.PRODUCTID = AGR.PRODUCTID
WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
