SELECT
    NUMERO_POLIZA,
    NUMERO_OPERACION,
    ANIO,
    MES,
    RESCATE,
    SALDO,
    SUMA_ASEGURADA,
    ANIOS_PRORROGADOS,
    MESES_PRORROGADOS,
    BENEFICIO_SUPERVIVENCIA
FROM 
(
    SELECT
        NUMEROPOLIZAINPUT         AS NUMERO_POLIZA,
        OPERATIONPK               AS NUMERO_OPERACION,
        GVTD_YEAR                 AS ANIO,
        GVTD_month                AS MES,
        GVTD_TOTALSURRENDER       AS RESCATE,
        GVTD_REDUCEDPAID          AS SALDO,
        GVTD_EXTENDEDTERM         AS SUMA_ASEGURADA,
        GVTD_EXTENDEDYEARS        AS ANIOS_PRORROGADOS,
        GVTD_EXTENDEDDAYS         AS MESES_PRORROGADOS,
        GVTD_SURVIVALBENEFIT      AS BENEFICIO_SUPERVIVENCIA,
        DENSE_RANK() OVER(PARTITION BY NUMEROPOLIZAINPUT ORDER BY AUDITDATE DESC) AS CORRELATIVO
    FROM 
    (
        SELECT
            B.NUMEROPOLIZAINPUT,
            A.OPERATIONPK,
            VGTDE.GVTD_YEAR,
            VGTDE.GVTD_month,
            VGTDE.GVTD_TOTALSURRENDER,
            VGTDE.GVTD_REDUCEDPAID,
            VGTDE.GVTD_EXTENDEDTERM,
            VGTDE.GVTD_EXTENDEDYEARS,
            VGTDE.GVTD_EXTENDEDDAYS,
            VGTDE.GVTD_SURVIVALBENEFIT,
            CTX.AUDITDATE
        FROM 
            INTERSEGURO.POLICYDCO A
            INNER JOIN INTERSEGURO.PREPOLICY B 
                ON A.DCOID = B.PK
            INNER JOIN INTERSEGURO.CONTEXTOPERATION CTX 
                ON CTX.ID = A.OPERATIONPK
                AND CTX.STATUS = 2
            INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
                ON AGR.AGREGATEDPOLICYID = A.AGREGATEDOBJECTID
                --AND AGR.OPERATIONPK = CTX.ID
            INNER JOIN INTERSEGURO.STPO_GUARANTEEDVALUESTABLE VGT 
                ON VGT.COR_ID = A.OPERATIONPK
            INNER JOIN INTERSEGURO.STPO_GUARANTEEDVALUESDETAIL VGTDE
                ON VGTDE.GVT_ID = VGT.GVT_ID
        WHERE 
            B.NUMEROPOLIZAINPUT IS NOT NULL
    ) AS subquery
) AS outer_query
WHERE 
    CORRELATIVO = 1
