 SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PDC.OPERATIONPK                  AS NUMERO_OPERACION
      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE
      ,TO_CHAR(COT.TIME_STAMP,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,AGE.PRODUCTID                    AS ID_PRODUCTO
      ,TRIM(UPPER(POR.DESCRIPTION))     AS NOMBRE_PRODUCTO
      ,(CASE WHEN COT.STATUS = 1
             THEN 'Not applied operation' 
             WHEN COT.STATUS = 2 
             THEN 'Applied operation'
             ELSE ''||COT.STATUS
      END ) AS STATUS_OPERATION
			,POLG.STATIC
			,POLG.APELLIDOPATERNOASEGINPUT
			,POLG.APELLIDOMATERNOASEGINPUT
			,POLG.NOMBREARTICULOINPUT
			,POLG.NOMBREDOSASEGINPUT
			,POLG.NOMBREUNOASEGINPUT
			,POLG.TIPODOCUMENTOGEINPUT
			,POLG.NUMERODOCUMENTOGEINPUT
			,POLG.COMISIONCOASEGINPUT
			,POLG.FECHACOMPRAINPUT
			,POLG.FRECUENCIAPAGOAUXINPUT
			,POLG.GASTOSCOASEGUROINPUT
			,POLG.NIVELAGRUPREASEGINPUT
			,POLG.NUMEROCERTIFICADOGEINPUT
			,POLG.NUMEROPOLMATRIZGEINPUT
			,POLG.PARTICIPACCARDIFINPUT
			,POLG.PARTICIPACIONINTERSEGINPUT
			,POLG.PLANCONTRATADOINPUT
			,POLG.PLAZOGARANTIAINPUT
			,POLG.PRIMACALCULADAGEINPUT
			,POLG.PRIMARIESGOINPUT
			,POLG.RUCCONTRATANTEINPUT
			,POLG.SEXOASEGGEINPUT
			,POLG.SKUINPUT
			,POLG.TIENDAINPUT
            ,STA.DESCRIPTION AS ESTADO_POLIZA
      FROM INTERSEGURO.PREPOLICY PRE
INNER JOIN INTERSEGURO.POLGARANTIAEXTENDIDA  POLG
		ON PRE.STATIC = CAST(POLG.STATIC AS VARCHAR(50))
INNER JOIN INTERSEGURO.POLICYDCO PDC
        ON PDC.DCOID  = PRE.PK
INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PDC.OPERATIONPK
INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGE
        ON AGE.AGREGATEDPOLICYID = PDC.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT POR
        ON POR.PRODUCTID = AGE.PRODUCTID
        AND POR.PRODUCTID= 39480
INNER JOIN INTERSEGURO.STATE STA 
        ON STA.STATEID = PDC.STATEID
     WHERE NULLIF(TRIM(PRE.NUMEROPOLIZAINPUT),'') IS NOT NULL
      AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
        --AND TRUNC(COT.AUDITDATE,'DD') >= (CURRENT_DATE-7)
