CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.carga_dv_daily_recaudo_samp()
OPTIONS(
  strict_mode=true)
BEGIN
/********************************************************************
* Proyecto		  : iter-data-storage-pv-uat 
* Fecha			  : 23 / 12 / 2020
* Autor			  : Bluetab - Edson Huerta G.                               
* Descripción     : 
*********************************************************************
*                       MODIFICACIONES POSTERIORES                  *
*===================================================================*
*=  Fecha   | Persona |           Modificación Realizada           =*
*===================================================================*                                    
* 2021/01/14|T.Ramirez| Actualización de query. 
* 2021/01/15|T.Ramirez| Se agrega el campo ANIO al data entry PORCENTAJE DE ESTACIONALIDAD.
*********************************************************************/


-- ----------------------------------------------------------------
-- Paso A10: Recaudacion diaria
-- ----------------------------------------------------------------
CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.bi_finanzas.DV_DAILY_RECAUDO_SAMP` as
(
WITH TMP_ESTACIONALIDAD AS
(
    SELECT
        (CASE WHEN TIPO = 'RECAUDO_IS' THEN 'VIDA IS' WHEN TIPO='RECAUDO_SURA' THEN 'VIDA SURA' END) TIPO,
        DIAS,
        DIA_HABIL,
        PORCENTAJE,
        PORCENTAJE_ACUMULADO,
        ANIO
    FROM `iter-data-storage-pv-uat.external_data.DE_ESTACIONALIDAD_VIDA`
    WHERE TIPO IN ('RECAUDO_IS','RECAUDO_SURA')
)
SELECT 
    PAG.PERIODO_COBRANZA, 
    PAG.PERIODO_PAGO, 
    PAG.FECHA_PAGO,
    CAST( PAG.FECHA_REGISTRO_CAJA AS DATE )   AS FECHA_REGISTRO_CAJA,
    CAST( PAG.FECHA_REGISTRO_ABONO AS DATE)   AS FECHA_REGISTRO_ABONO,
    PAG.ID_GRUPO_PRODUCTO, 
    PAG.NOMBRE_GRUPO_PRODUCTO,
    PAG.VISTA_PRODUCTO,
    PAG.VISTA_PRODUCTO_HOMOLOGADO,
    PAG.NOMBRE_GRUPO_PRODUCTO_HOMOLOGADO,
    PAG.ID_PRODUCTO,
    PAG.NOMBRE_PRODUCTO,
    PAG.ID_CANAL_PAGO,
    PAG.CANAL_PAGO,
    PAG.ESTADO_PAGO,
    PAG.METODO_PAGO,
    PAG.COD_CONCEPTO_ABONO,
    PAG.CONCEPTO_DESCRIPCION,
    PAG.TIPO_PAGO,
    PAG.TIPO_DOCUMENTO_PAGO,
    PAG.MONTO_ORIGEN_MONEDA,
    CAST(PAG.VALOR_MONEDA_ORIGEN AS FLOAT64) VALOR_MONEDA_ORIGEN, 
    count(1) CANTIDAD_POLIZA,
    CAST(SUM( PAG.MONTO_ORIGEN_CANTIDAD ) AS FLOAT64) MONTO_PAGADO_ORIGEN,
    CAST(SUM( PAG.VALOR_SALDO_ORIGEN ) AS FLOAT64) VALOR_SALDO_ORIGEN,
    CAST(SUM( PAG.VALOR_SOLES_ABONO ) AS FLOAT64) MONTO_PAGADO_SOLES,
    PAG.PRIMERA_PRIMA,
    PAG.PRESUPUESTO_RECAUDO,
    PAG.REPRESUPUESTO_RECAUDO,
    SUI.PORCENTAJE ESTACIONALIDAD_RECAUDO,
    SUI.PORCENTAJE_ACUMULADO ESTACIONALIDAD_RECAUDO_AC,
    PAG.MONTO_PROM_3_ULTIMOS_MESES,
    PAG.DIA_CALENDARIO, 
    PAG.DIAS_CALENDARIO_TOTAL,
    PAG.DIA_HABIL,
    PAG.DIAS_HABILES_TOTAL,
    PAG.ID_TIPO_INGRESO_ABONO, 
    PAG.TIPO_INGRESO_ABONO,
    CAST(PAG.DIAS_ATRASO AS INT64) DIAS_ATRASO,
    CAST(PAG.TIPO_MORA AS INT64) TIPO_MORA,
    PAG.MONTO_MORA_ORIGEN MONEDA_MORA_ORIGEN,
    PAG.ULTIMA_VIA_PAGO,
    PAG.ID_EMPLEADO, 
    PAG.EMPLEADO, 
    CAST(PAG.FLG_MORA AS INT64) FLG_MORA, 
    CAST(PAG.FLG_PAGO_FISICO AS INT64) FLG_PAGO_FISICO,
    PAG.SISTEMA_ORIGEN SISTEMA_ORIGEN_PAGO
      FROM `iter-data-storage-pv-uat.bi_finanzas.DV_RECAUDO_SAMP` PAG 
 LEFT JOIN `iter-data-storage-pv-uat.config_data.CNF_PRODUCTO_CANAL_VISTA` CPCV 
        ON PAG.NOMBRE_PRODUCTO=CPCV.NOMBRE_PRODUCTO 
       AND CPCV.VISTA_PRODUCTO IN ('VIDA IS','VIDA SURA') 
 LEFT JOIN `iter-data-storage-pv-uat.bi_finanzas.DIM_TIEMPO` TIM 
        ON CAST( PAG.FECHA_APLICACION_PAGO AS DATE )  = TIM.DATE 
 LEFT JOIN TMP_ESTACIONALIDAD SUI 
        ON TIM.working_day_acum_month      = CAST(SUI.DIAS AS INT64)
       AND TIM.working_day_acum_date       = CAST(SUI.DIA_HABIL AS INT64)
       AND CAST(TIM.year_number AS STRING) = SUI.ANIO 
       AND CPCV.VISTA_PRODUCTO        = SUI.TIPO
GROUP BY
    PAG.PERIODO_COBRANZA, 
    PAG.PERIODO_PAGO,
    PAG.FECHA_PAGO,
    PAG.ID_GRUPO_PRODUCTO, 
    PAG.NOMBRE_GRUPO_PRODUCTO,
    PAG.VISTA_PRODUCTO,
    PAG.VISTA_PRODUCTO_HOMOLOGADO,
    PAG.NOMBRE_GRUPO_PRODUCTO_HOMOLOGADO,
    PAG.ID_PRODUCTO,
    PAG.NOMBRE_PRODUCTO,
    PAG.ID_CANAL_PAGO,
    PAG.CANAL_PAGO,
    PAG.ESTADO_PAGO,
    PAG.METODO_PAGO,
    PAG.COD_CONCEPTO_ABONO,
    PAG.CONCEPTO_DESCRIPCION,
    PAG.TIPO_PAGO,
    PAG.TIPO_DOCUMENTO_PAGO,
    PAG.MONTO_ORIGEN_MONEDA,
    PAG.VALOR_MONEDA_ORIGEN,
    PAG.PRIMERA_PRIMA,
    PAG.PRESUPUESTO_RECAUDO,
    PAG.REPRESUPUESTO_RECAUDO,
    SUI.PORCENTAJE,
    SUI.PORCENTAJE_ACUMULADO,
    PAG.MONTO_PROM_3_ULTIMOS_MESES,
    PAG.DIA_CALENDARIO, 
    PAG.DIAS_CALENDARIO_TOTAL,
    PAG.DIA_HABIL,
    PAG.DIAS_HABILES_TOTAL,
    PAG.ID_TIPO_INGRESO_ABONO, 
    PAG.TIPO_INGRESO_ABONO,
    PAG.DIAS_ATRASO,
    PAG.TIPO_MORA,
    PAG.MONTO_MORA_ORIGEN,
    PAG.ULTIMA_VIA_PAGO,
    PAG.FECHA_REGISTRO_CAJA,
    PAG.FECHA_REGISTRO_ABONO,
    PAG.FECHA_APLICACION_PAGO,
    PAG.ID_EMPLEADO, 
    PAG.EMPLEADO, 
    PAG.FLG_MORA, 
    PAG.FLG_PAGO_FISICO,
    PAG.SISTEMA_ORIGEN
);

SELECT 'OK' ESTADO_EJECUCION;

END;