CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.sp_bi_cobranza_hm_poliza_cobro_vehicular(par_periodo INT64)
OPTIONS(
  strict_mode=true)
BEGIN
-- *********************************************************************
-- * Proyecto       : GOLDEN RECORD
-- * Fecha          : 09/08/2021
-- * Autor          : Ramirez Hurtado, Tito Jaime
-- * Tabla Destinos : - 
-- *                : - 
-- * Tablas Fuentes : - 
-- * Descripción    : 
-- *********************************************************************
-- *                       MODIFICACIONES POSTERIORES                  *
-- *===================================================================*
-- *===================================================================*
-- *   Fecha   | Persona |           Modificación Realizada            *
-- *           |         |                                            
-- ********************************************************************* 
DECLARE var_periodo_calendario  INT64;
DECLARE var_periodo_recaudacion INT64;

IF par_periodo IS NULL THEN 

SET var_periodo_calendario  = ( SELECT MAX(PERIODO) FROM  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_CARGO_VEHICULAR` WHERE TIPO_PERIODO='CALENDARIO' );
SET var_periodo_recaudacion = ( SELECT MAX(PERIODO) FROM  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_CARGO_VEHICULAR` WHERE TIPO_PERIODO='RECAUDACION' );

ELSE 

SET var_periodo_calendario  = par_periodo;
SET var_periodo_recaudacion = par_periodo;

END IF
;

-- ----------------------------------------------------------------------
-- Paso A10: 
-- ----------------------------------------------------------------------
DELETE FROM  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_COBRO_VEHICULAR`
WHERE PERIODO = var_periodo_calendario
  AND TIPO_PERIODO='CALENDARIO'  ;

-- ----------------------------------------------------------------------
-- Paso A10: 
-- ----------------------------------------------------------------------
INSERT INTO  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_COBRO_VEHICULAR`
(
 PERIODO
,TIPO_PERIODO
,NUMERO_POLIZA
,PERIODO_DIA_INICIO_4M
,PERIODO_DIA_INICIO
,PERIODO_DIA_FIN
,MONTO_CANTIDAD_ABONO_PEN
,MONTO_CANTIDAD_ABONO_USD
,SALDO_CANTIDAD_PEN
,SALDO_CANTIDAD_USD
,MAX_FECHA_APLICADO_CARGO_ABONO
,NOMBRE_GRUPO_PRODUCTO
,NOMBRE_PRODUCTO
,NUMERO_PLACA
,ESTADO_POLIZA
,CANAL
,PLAN
,MODELO_VEHICULO
,MARCA_VEHICULO
,NUMERO_DOCUMENTO
,TIPO_DOCUMENTO
,NOMBRE_CONTRATANTE
,MOTIVO_RECHAZO
,TIPO_TARJETA
,NUMERO_TARJETA_ENCRYP
,TIPO_ENTIDAD
,NOMBRE_TARJETA
,BIN_TARJETA
,EMISOR
,MONTO_POR_COBRAR_PEN
,MONTO_POR_COBRAR_USD
,INDICADOR_RENOVACION
,FECHA_INICIO_VIGENCIA_POLIZA
,FECHA_FIN_VIGENCIA_POLIZA
,CORREO
,CELULAR
,MONEDA
,VIGENCIA
,NOMBRE_AGENTE
,CODIGO_AGENTE
,CODIGO_AGENCIA
,NOMBRE_SUPERVISOR
,NOMBRE_JEFE
,MORA
,FRECUENCIA_PAGO
,VIA_COBRO
,NUMERO_VIA_PAGO
,ANTIGUEDAD
--,PASARELA
,CORREO_MIR
,CELULAR_MIR
,OPERADOR
,CORREO_VEHICULAR	
,CELULAR_VEHICULAR
,PERFIL_FINANCIERO
,TIPO_MONEDA_TC_PERFIL
,PUNTAJE_SEGMENTO
,SEGMENTO
--SEGMENTO

,F
,M
,R
,SCORE_RFM
,RECENCY
,MONETARY_VALUE
,FREQUENCY
,FECHA_PAGADO_HASTA
)
SELECT 
 TAB.PERIODO
,TAB.TIPO_PERIODO
,TAB.NUMERO_POLIZA
,TAB.PERIODO_DIA_INICIO_4M
,TAB.PERIODO_DIA_INICIO
,TAB.PERIODO_DIA_FIN
,SUM(CASE WHEN ESTADO_CARGO ='ACTIVO' THEN COALESCE(TAB.MONTO_CANTIDAD_ABONO_PEN,0) ELSE 0 END )OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_CANTIDAD_ABONO_PEN
,SUM(CASE WHEN ESTADO_CARGO ='ACTIVO' THEN COALESCE(TAB.MONTO_CANTIDAD_ABONO_USD,0) ELSE 0 END )OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_CANTIDAD_ABONO_USD
,SUM( COALESCE(TAB.SALDO_CANTIDAD_PEN,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS SALDO_CANTIDAD_PEN
,SUM(COALESCE(TAB.SALDO_CANTIDAD_USD,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS SALDO_CANTIDAD_USD
,MAX(TAB.FECHA_APLICADO_CARGO_ABONO)OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA)  AS MAX_FECHA_APLICADO_CARGO_ABONO
,TAB.NOMBRE_GRUPO_PRODUCTO
,TAB.NOMBRE_PRODUCTO
,TAB.NUMERO_PLACA
,TAB.ESTADO_POLIZA
,TAB.CANAL
,TAB.PLAN
,TAB.MODELO_VEHICULO
,TAB.MARCA_VEHICULO
,TAB.NUMERO_DOCUMENTO
,TAB.TIPO_DOCUMENTO
,TAB.NOMBRE_CONTRATANTE
,TAB.MOTIVO_RECHAZO
,TAB.TIPO_TARJETA
,TAB.NUMERO_TARJETA_ENCRYP
,TAB.TIPO_ENTIDAD
,TAB.NOMBRE_TARJETA
,TAB.BIN_TARJETA
,TAB.EMISOR
,SUM( COALESCE(TAB.MONTO_POR_COBRAR_PEN,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_POR_COBRAR_PEN
,SUM( COALESCE(TAB.MONTO_POR_COBRAR_USD,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_POR_COBRAR_USD
,TAB.INDICADOR_RENOVACION
,TAB.FECHA_INICIO_VIGENCIA_POLIZA
,TAB.FECHA_FIN_VIGENCIA_POLIZA
,TAB.CORREO
,TAB.CELULAR
,TAB.MONEDA
,TAB.VIGENCIA
,TAB.NOMBRE_AGENTE
,TAB.CODIGO_AGENTE
,TAB.CODIGO_AGENCIA
,TAB.NOMBRE_SUPERVISOR
,TAB.NOMBRE_JEFE
,SUM(CASE WHEN COALESCE(TAB.MORA,0)>0 THEN 1 ELSE 0 END)OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS MORA
,TAB.FRECUENCIA_PAGO
,TAB.VIA_COBRO
,TAB.NUMERO_VIA_PAGO
,TAB.ANTIGUEDAD
--,TAB.PASARELA
,TAB.CORREO_CONTACTO
,TAB.CELULAR_CONTACTO
,TAB.OPERADOR
,TAB.CORREO_VEHICULAR	
,TAB.CELULAR_VEHICULAR	
--,ROW_NUMBER()OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ORDER BY COALESCE(FECHA_APLICADO_CARGO_ABONO,FECHA_VENCIMIENTO_CUOTA) DESC ) AS CORRELATIVO
,PERFIL_FINANCIERO
,TIPO_MONEDA_TC_PERFIL
,PUNTAJE_SEGMENTO
,SEGMENTO
--SEGMENTO
-- SEGMENTO
,TAB.F
,TAB.M
,TAB.R
,TAB.SCORE_RFM
,TAB.RECENCY
,TAB.MONETARY_VALUE
,TAB.FREQUENCY
,TAB.FECHA_PAGADO_HASTA
FROM `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_CARGO_VEHICULAR` TAB
WHERE PERIODO = var_periodo_calendario
  AND TIPO_PERIODO='CALENDARIO' 
  AND ESTADO_CARGO ='ACTIVO'
QUALIFY (ROW_NUMBER()OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ORDER BY COALESCE(FECHA_APLICADO_CARGO_ABONO,FECHA_VENCIMIENTO_CUOTA) DESC ))=1;


-- ----------------------------------------------------------------------
-- Paso A10: 
-- ----------------------------------------------------------------------
DELETE FROM  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_COBRO_VEHICULAR`
WHERE PERIODO = var_periodo_recaudacion
  AND TIPO_PERIODO='RECAUDACION'  ;

-- ----------------------------------------------------------------------
-- Paso A10: 
-- ----------------------------------------------------------------------
INSERT INTO  `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_COBRO_VEHICULAR`
(
 PERIODO
,TIPO_PERIODO
,NUMERO_POLIZA
,PERIODO_DIA_INICIO_4M
,PERIODO_DIA_INICIO
,PERIODO_DIA_FIN
,MONTO_CANTIDAD_ABONO_PEN
,MONTO_CANTIDAD_ABONO_USD
,SALDO_CANTIDAD_PEN
,SALDO_CANTIDAD_USD
,MAX_FECHA_APLICADO_CARGO_ABONO
,NOMBRE_GRUPO_PRODUCTO
,NOMBRE_PRODUCTO
,NUMERO_PLACA
,ESTADO_POLIZA
,CANAL
,PLAN
,MODELO_VEHICULO
,MARCA_VEHICULO
,NUMERO_DOCUMENTO
,TIPO_DOCUMENTO
,NOMBRE_CONTRATANTE
,MOTIVO_RECHAZO
,TIPO_TARJETA
,NUMERO_TARJETA_ENCRYP
,TIPO_ENTIDAD
,NOMBRE_TARJETA
,BIN_TARJETA
,EMISOR
,MONTO_POR_COBRAR_PEN
,MONTO_POR_COBRAR_USD
,INDICADOR_RENOVACION
,FECHA_INICIO_VIGENCIA_POLIZA
,FECHA_FIN_VIGENCIA_POLIZA
,CORREO
,CELULAR
,MONEDA
,VIGENCIA
,NOMBRE_AGENTE
,CODIGO_AGENTE
,CODIGO_AGENCIA
,NOMBRE_SUPERVISOR
,NOMBRE_JEFE
,MORA
,FRECUENCIA_PAGO
,VIA_COBRO
,NUMERO_VIA_PAGO
,ANTIGUEDAD
--,PASARELA
,CORREO_MIR
,CELULAR_MIR
,OPERADOR
,CORREO_VEHICULAR	
,CELULAR_VEHICULAR	
,PERFIL_FINANCIERO
,TIPO_MONEDA_TC_PERFIL
,PUNTAJE_SEGMENTO
,SEGMENTO
--RFM
,F
,M
,R
,SCORE_RFM
,RECENCY
,MONETARY_VALUE
,FREQUENCY
,FECHA_PAGADO_HASTA
)
SELECT 
 TAB.PERIODO
,TAB.TIPO_PERIODO
,TAB.NUMERO_POLIZA
,TAB.PERIODO_DIA_INICIO_4M
,TAB.PERIODO_DIA_INICIO
,TAB.PERIODO_DIA_FIN
,SUM(CASE WHEN ESTADO_CARGO ='ACTIVO' THEN COALESCE(TAB.MONTO_CANTIDAD_ABONO_PEN,0) ELSE 0 END )OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_CANTIDAD_ABONO_PEN
,SUM(CASE WHEN ESTADO_CARGO ='ACTIVO' THEN COALESCE(TAB.MONTO_CANTIDAD_ABONO_USD,0) ELSE 0 END )OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_CANTIDAD_ABONO_USD
,SUM( COALESCE(TAB.SALDO_CANTIDAD_PEN,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS SALDO_CANTIDAD_PEN
,SUM(COALESCE(TAB.SALDO_CANTIDAD_USD,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS SALDO_CANTIDAD_USD
,MAX(TAB.FECHA_APLICADO_CARGO_ABONO)OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA)  AS MAX_FECHA_APLICADO_CARGO_ABONO
,TAB.NOMBRE_GRUPO_PRODUCTO
,TAB.NOMBRE_PRODUCTO
,TAB.NUMERO_PLACA
,TAB.ESTADO_POLIZA
,TAB.CANAL
,TAB.PLAN
,TAB.MODELO_VEHICULO
,TAB.MARCA_VEHICULO
,TAB.NUMERO_DOCUMENTO
,TAB.TIPO_DOCUMENTO
,TAB.NOMBRE_CONTRATANTE
,TAB.MOTIVO_RECHAZO --> Cambio para tomar el maximo de todos los rechazos efectuados en el periodo
--,MAX(TAB.MOTIVO_RECHAZO) OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MOTIVO_RECHAZO
,TAB.TIPO_TARJETA
,TAB.NUMERO_TARJETA_ENCRYP
,TAB.TIPO_ENTIDAD
,TAB.NOMBRE_TARJETA
,TAB.BIN_TARJETA
,TAB.EMISOR
,SUM( COALESCE(TAB.MONTO_POR_COBRAR_PEN,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_POR_COBRAR_PEN
,SUM( COALESCE(TAB.MONTO_POR_COBRAR_USD,0))OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ) AS MONTO_POR_COBRAR_USD
,TAB.INDICADOR_RENOVACION
,TAB.FECHA_INICIO_VIGENCIA_POLIZA
,TAB.FECHA_FIN_VIGENCIA_POLIZA
,TAB.CORREO
,TAB.CELULAR
,TAB.MONEDA
,TAB.VIGENCIA
,TAB.NOMBRE_AGENTE
,TAB.CODIGO_AGENTE
,TAB.CODIGO_AGENCIA
,TAB.NOMBRE_SUPERVISOR
,TAB.NOMBRE_JEFE
,SUM(CASE WHEN COALESCE(TAB.MORA,0)>0 THEN 1 ELSE 0 END)OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA) AS MORA
,TAB.FRECUENCIA_PAGO
,TAB.VIA_COBRO
,TAB.NUMERO_VIA_PAGO
,TAB.ANTIGUEDAD
--,TAB.PASARELA
,TAB.CORREO_CONTACTO
,TAB.CELULAR_CONTACTO
,TAB.OPERADOR
,TAB.CORREO_VEHICULAR	
,TAB.CELULAR_VEHICULAR	
--,ROW_NUMBER()OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ORDER BY COALESCE(FECHA_APLICADO_CARGO_ABONO,FECHA_VENCIMIENTO_CUOTA) DESC ) AS CORRELATIVO
,PERFIL_FINANCIERO
,TIPO_MONEDA_TC_PERFIL
,PUNTAJE_SEGMENTO
,SEGMENTO
--RFM
,TAB.F
,TAB.M
,TAB.R
,TAB.SCORE_RFM
,TAB.RECENCY
,TAB.MONETARY_VALUE
,TAB.FREQUENCY
,TAB.FECHA_PAGADO_HASTA
FROM `iter-data-storage-pv-uat.bi_cobranza.HM_POLIZA_CARGO_VEHICULAR` TAB
WHERE PERIODO = var_periodo_recaudacion
  AND TIPO_PERIODO='RECAUDACION' 
  AND ESTADO_CARGO ='ACTIVO'
QUALIFY (ROW_NUMBER()OVER(PARTITION BY PERIODO,TIPO_PERIODO,NUMERO_POLIZA ORDER BY COALESCE(FECHA_APLICADO_CARGO_ABONO,FECHA_VENCIMIENTO_CUOTA) DESC ))=1;

END;