CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.carga_dv_daily_emision()
OPTIONS(
  strict_mode=true)
BEGIN

CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.bi_finanzas.DV_DAILY_EMISION` AS(

SELECT
'DAILY' DASHBOARD,
POL.VISTA_DAILY VISTA,
POL.VISTA_PRODUCTO,
POL.VISTA_PRODUCTO_HOMOLOGADO,
POL.NOMBRE_GRUPO_PRODUCTO_HOMOLOGADO,
POL.FECHA_EMISION,
POL.PERIODO_FECHA_EMISION,
POL.ANIO_MES_EMISION,
POL.NRO_MES_EMISION,
POL.MES_LARGO_EMISION,
POL.ID_MONEDA,
POL.MONEDA,
POL.TIPO_CAMBIO,
POL.ID_PRODUCTO,
POL.NOMBRE_PRODUCTO,
POL.ID_GRUPO_PRODUCTO,
POL.NOMBRE_GRUPO_PRODUCTO,
POL.DESC_GRUPO_PRODUCTO,
POL.ESTADO ESTADO_POLIZA,
POL.CANAL_AGRUPADO,
POL.PRESUPUESTO_EMISION,
POL.REPRESUPUESTO_EMISION,
POL.ESTACIONALIDAD_EMISION, 
POL.ESTACIONALIDAD_EMISION_AC,
ROUND(CAST(SUM(POL.PRIMA_NETA_SOLES) AS FLOAT64),5) PRIMERA_PRIMA,
ROUND(CAST(SUM(POL.PRIMA_TOTAL_SOLES) AS FLOAT64),5) PRIMA_TOTAL,
CAST(SUM(POL.PRIMA_TOTAL_ANUAL) AS FLOAT64) PRIMA_TOTAL_ANUAL, 
CAST(SUM(POL.PRIMA_BRUTA_ANUAL) AS FLOAT64) PRIMA_BRUTA_ANUAL,
CAST(SUM(POL.COBERTURA) AS FLOAT64) COBERTURA,
(ROUND(CAST(SUM(IFNULL(POL.PRIMA_TOTAL_SOLES,0)) AS FLOAT64),5) - CAST(SUM(IFNULL(POL.COBERTURA,0)) AS FLOAT64)) AS EMISION_NETA,
COUNT(1) CANTIDAD_POLIZA,
SUM(POL.MONTO_COBERTURA_PRINCIPAL) MONTO_COBERTURA_PRINCIPAL,
POL.FRECUENCIA_PAGO FRECUENCIA_PAGO_INICIAL,
POL.ID_FUENTE,
POL.NOMBRE_FUENTE,
CURRENT_TIMESTAMP FECHA_CREACION_REGISTRO,
SESSION_USER() USUARIO_CREACION
FROM `iter-data-storage-pv-uat.bi_finanzas.DV_EMISION` POL
WHERE 
POL.FLG_V_DAILY=1
GROUP BY
POL.VISTA_DAILY,
POL.VISTA_PRODUCTO,
POL.VISTA_PRODUCTO_HOMOLOGADO,
POL.NOMBRE_GRUPO_PRODUCTO_HOMOLOGADO,
POL.FECHA_EMISION,
POL.PERIODO_FECHA_EMISION,
POL.ANIO_MES_EMISION,
POL.NRO_MES_EMISION,
POL.MES_LARGO_EMISION,
POL.ID_MONEDA,
POL.MONEDA,
POL.TIPO_CAMBIO,
POL.ID_PRODUCTO,
POL.NOMBRE_PRODUCTO,
POL.ID_GRUPO_PRODUCTO,
POL.NOMBRE_GRUPO_PRODUCTO,
POL.DESC_GRUPO_PRODUCTO,
POL.ESTADO,
POL.CANAL_AGRUPADO,
POL.PRESUPUESTO_EMISION,
POL.REPRESUPUESTO_EMISION,
POL.ESTACIONALIDAD_EMISION, 
POL.ESTACIONALIDAD_EMISION_AC,
POL.FRECUENCIA_PAGO,
POL.ID_FUENTE,
POL.NOMBRE_FUENTE

);

SELECT 'OK' ESTADO_EJECUCION;

END;