CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.sp_goldenrecord_colaborador()
OPTIONS(
  strict_mode=true)
BEGIN
-- *******************************************************************
-- * Proyecto : FOTOCHEK 
-- * Fecha : 29/09/2021
-- * Autor : Jayo Escalante, Geraldine Indira
-- * Tabla Destinos : -
-- * : -
-- * Tablas Fuentes : -
-- * Descripción : Tabla que define el rol del colaborador en la compañía
-- *******************************************************************
-- * MODIFICACIONES POSTERIORES *
-- ===================================================================
-- * Fecha | Persona | Modificación Realizada *
-- ===================================================================
-- * | |
-- *******************************************************************

-- ----------------------------------------------------------------------
-- Paso 1: Universo de Colaboradores NUEVOS y MODIFICADOS
-- ----------------------------------------------------------------------
CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO`
AS
(
WITH TMP_NUMERO_HIJOS AS (
SELECT 
CO_TRAB
,SUM(CASE WHEN TRABA.ST_PARI_DEPE ='S' AND TRABA.TI_PARI = 'HIJ' THEN 1 END) AS NUMERO_HIJOS_DEPENDIENTES
,SUM(CASE WHEN TRABA.ST_PARI_DEPE ='N' AND TRABA.TI_PARI = 'HIJ' THEN 1 END) AS NUMERO_HIJOS_NODEPENDIENTES
FROM `iter-data-storage-pv-uat.ofiplan_data.TDPARI_TRAB_raw` TRABA
GROUP BY CO_TRAB
)
SELECT CONCAT('05', '-', CODIGO_TIPO_DOCUMENTO, '-', DOCUMENTO_IDENTIDAD) AS ID_PERSONA,* 
FROM (
SELECT  
RTRIM(TMTRAB_PERS.NO_TRAB) AS NOMBRES,
RTRIM(TMTRAB_PERS.NO_APEL_PATE) AS APELLIDO_PATERNO,
RTRIM(TMTRAB_PERS.NO_APEL_MATE) AS APELLIDO_MATERNO,
CONCAT(RTRIM(TMTRAB_PERS.NO_APEL_PATE), ' ', RTRIM(TMTRAB_PERS.NO_APEL_MATE)) AS APELLIDOS,
TMTRAB_EMPR.CO_PUES_TRAB PUESTO, 
TTPUES_TRAB.DE_PUES_TRAB DESCRIPCION_PUESTO,
TTAREA.CO_AREA AS CODIGO_AREA,
TTAREA.DE_AREA AS DESCRIPCION_AREA,
-- ----------------------------------------------------------------------
-- Se obtiene solo el tipo de documento DNI
-- ----------------------------------------------------------------------
    (
    SELECT EG1.NOMBRE_GLOBAL
    FROM `iter-data-storage-pv-uat.ofiplan_data.TDIDEN_TRAB_raw` TDIDEN_TRAB
    INNER JOIN config_data.CNF_EQUIVALENCIA_GLOBAL EG1 
    ON TDIDEN_TRAB.TI_DOCU_IDEN = EG1.VALOR_ORIGEN AND EG1.ID_FUENTE = '11' AND EG1.CODIGO_TIPO = 'TIPODOC'
    WHERE TDIDEN_TRAB.ST_PRES_REPO = 'S' AND TDIDEN_TRAB.CO_TRAB = TMTRAB_EMPR.CO_TRAB 
    ) AS TIPO_DOCUMENTO, 
    ( 
    SELECT EG1.CODIGO_GLOBAL
    FROM `iter-data-storage-pv-uat.ofiplan_data.TDIDEN_TRAB_raw` TDIDEN_TRAB
    INNER JOIN config_data.CNF_EQUIVALENCIA_GLOBAL EG1 
    ON TDIDEN_TRAB.TI_DOCU_IDEN = EG1.VALOR_ORIGEN AND EG1.ID_FUENTE = '11' AND EG1.CODIGO_TIPO = 'TIPODOC'
    WHERE TDIDEN_TRAB.ST_PRES_REPO = 'S' AND TDIDEN_TRAB.CO_TRAB = TMTRAB_EMPR.CO_TRAB 
    ) AS CODIGO_TIPO_DOCUMENTO, 
    ( 
    SELECT TDIDEN_TRAB.NU_DOCU_IDEN 
    FROM `iter-data-storage-pv-uat.ofiplan_data.TDIDEN_TRAB_raw` TDIDEN_TRAB
    WHERE TDIDEN_TRAB.ST_PRES_REPO = 'S' AND TDIDEN_TRAB.CO_TRAB = TMTRAB_EMPR.CO_TRAB 
    ) AS DOCUMENTO_IDENTIDAD,

TMTRAB_EMPR.CO_TRAB      AS CODIGO_IS,
TMTRAB_EMPR.FE_INGR_EMPR AS FECHA_INGRESO,
TMTRAB_EMPR.FE_CESE_TRAB AS FECHA_CESE,
CASE    WHEN TMTRAB_EMPR.TI_SITU ='ACT' 
        THEN 'ACTIVO' ELSE 'INACTIVO' 
        END      AS ESTADO,
TTDEPA.CO_DEPA   AS CODIGO_VICEPRESIDENCIA, 
TTDEPA.DE_DEPA   AS VICEPRESIDENCIA,
CAST( TMTRAB_PERS.FE_NACI_TRAB AS DATE)           AS FECHA_NACIMIENTO,
TMTRAB_PERS.NU_TLF1                               AS CELULAR,
TMTRAB_PERS.CO_UBIC_GEOG,
TDCOS.CO_CENT_COST                                AS CECO,
TMAUX.NO_AUXI                                     AS DESCRIPCION_CECO,
TMTRAB_EMPR.CO_PLAN                               AS CODIGO_PLANILLA,
TMTRAB_PERS.TI_SITU                               AS SITUACION,
GRUP.DE_GRUP_OCUP                                 AS GRUPO_OCUPACIONAL,
SED.DE_SEDE                                       AS SEDE,
CAST(CAST(REPLACE(INF.TI_INF1,'PL','') AS NUMERIC) AS STRING)     AS COD_UNIDAD,
INF.DE_TIPO_INF1                                  AS UNIDAD,
TMTRAB_PERS.ST_SEXO                               AS GENERO,
CONCAT(COALESCE(PERSL.NO_APEL_PATE,''),' ',COALESCE(PERSL.NO_APEL_MATE,''),' ',COALESCE(PERSL.NO_TRAB,''))    AS NOMBRE_LIDER
,IST.DE_TIPO_INST                                  AS TIPO_INSTRUCCION
,MOT.CO_MOTI_SEPA                                  AS MOT_SEPARACION
,TCA.DE_CATE_TRAB                                  AS CATEGORIA
,TMTRAB_PERS.NO_DIRE_MAI2                          AS EMAIL
,PERSL.NO_DIRE_MAI2                                AS EMAIL_LIDER
,PERSL.CO_TRAB                                     AS CODIGO_IS_LIDER
-- NUEVOS CAMPOS AGREGADOS
,TMTRAB_PERS.NO_DIRE_MAI1                          AS EMAIL_PERSONAL
,TMTRAB_PERS.NU_DOCU_IDEN_AFPS                     AS CUSPP
,SAFE_CAST(TMTRAB_PERS.FE_AFIL_AFPS AS DATE)                          AS FECHA_AFILIACION
,PLA.DE_PLAN                                       AS PLANILLA
,CONT.DE_TIPO_CONT                                 AS TIPO_CONTRATO
,TRAB.DE_CALI_TRAB                                 AS CALIFICACION_TRABAJADOR
,INGR.DE_FORM_INGR                                 AS FORMA_INGRESO
,COO.NO_COOP                                       AS COOPERATIVA
,BAN.DE_BANC                                       AS BANCO_SUELDO
,MON.DE_MONE                                       AS MONEDA_CTS
,BANCTS.DE_BANC                                    AS BANCO_CTS
,CIV.DE_ESTA_CIVI                                  AS ESTADO_CIVIL
,PAI.NO_PAIS                                       AS PAIS_NACIMIENTO
,LUG.NO_UBIC_GEOG                                  AS LUGAR_NACIMIENTO
,PAIN.NO_PAIS                                      AS PAIS_NACIONALIDAD
,RESI.NO_PAIS                                      AS PAIS_RESIDENCIA
,VIA.DE_TIPO_VIAS                                  AS TIPO_VIA
,ZON.DE_TIPO_ZONA                                  AS TIPO_ZONA
,UBIG.NO_UBIC_GEOG                                 AS UBIGEO
,IST.CO_TIPO_INST                                  AS COD_TIPO_INSTRUCCION
,AFP.DE_AFPS                                       AS AFP
,SAFE_CAST(TMTRAB_PERS.FE_MATR AS DATE)                              AS FECHA_MATRIMONIO
,TMTRAB_PERS.NO_DIRE_TRAB                          AS DIRECCION
,TMTRAB_PERS.NU_CASA                               AS NUMERO_CASA                      
,TMTRAB_PERS.NU_INTE                               AS NUMERO_INTERIOR
,TMTRAB_PERS.DE_REFE                               AS REFERENCIA
,TMTRAB_PERS.NU_TLF2                               AS CELULAR_2
,SED.CO_SEDE                                       AS CODIGO_SEDE
,TRABA.NUMERO_HIJOS_DEPENDIENTES
,TRABA.NUMERO_HIJOS_NODEPENDIENTES                 
,TMTRAB_EMPR.FE_INGR_PLAN 						   AS FECHA_INGRESO_PLANILLA		                         
,TMTRAB_EMPR.CO_COOP							   AS CODIGO_COOPERATIVA
,TMTRAB_EMPR.FE_INGR_COOP                 		   AS FECHA_INGRESO_COOPERATIVA
,TMTRAB_EMPR.NU_CNTA_SUEL   					   AS NUMERO_CUENTA_SUELDO
,TMTRAB_EMPR.NU_SUEL							   AS NUMERO_SUELDO
,TMTRAB_EMPR.NU_CNTA_CTSS                          AS NUMERO_CUENTA_CTS
,TTSEC.DE_SECC                              AS SECCION
,SITU.DE_TIPO_SITU                          AS DESCRIPCION_SITUACION
,CONCAT(ZON.DE_TIPO_ZONA ,'-',TMTRAB_PERS.NO_ZONA) AS DESC_TIPO_ZONA
,CASE WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'ABA' THEN 'ABANDONO DE PUESTO'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'DCA' THEN 'DESPIDO POR CAUSAL'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'DIN' THEN 'DESPIDO INTEMPESTIVO'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'DPP' THEN 'DESPIDO PERIODO DE PRUEBA'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'EXT' THEN 'EXTIN.CONTRA.LABORA'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'FAL' THEN 'FALLECIMIENTO'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'JUB' THEN 'JUBILACION'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'MDI' THEN 'MUTUO DISENSO'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'NA' THEN 'NO APLICABLE'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'NIV' THEN 'NO SE INICIO VINCULO LABORAL'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'REN' THEN 'RENUNCIA'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'RET' THEN 'RETIRO'
      WHEN TMTRAB_EMPR.CO_MOTI_SEPA = 'VEN' THEN 'TERMINO CONTRATO'
      ELSE NULL 
      END AS MOTIVO_SEPARACION
--
     FROM `iter-data-storage-pv-uat.ofiplan_data.TMTRAB_EMPR_raw` TMTRAB_EMPR      
INNER JOIN `iter-data-storage-pv-uat.ofiplan_data.TMTRAB_PERS_raw` TMTRAB_PERS 
        ON TMTRAB_PERS.CO_TRAB = TMTRAB_EMPR.CO_TRAB  
INNER JOIN `iter-data-storage-pv-uat.ofiplan_data.TTPUES_TRAB_raw` TTPUES_TRAB 
        ON TMTRAB_EMPR.CO_EMPR=TTPUES_TRAB.CO_EMPR 
       AND TMTRAB_EMPR.CO_PUES_TRAB = TTPUES_TRAB.CO_PUES_TRAB      
INNER JOIN `iter-data-storage-pv-uat.ofiplan_data.TTDEPA_raw` TTDEPA 
        ON TTDEPA.CO_EMPR=TMTRAB_EMPR.CO_EMPR 
       AND TTDEPA.CO_DEPA=TMTRAB_EMPR.CO_DEPA
INNER JOIN `iter-data-storage-pv-uat.ofiplan_data.TTAREA_raw` TTAREA 
        ON TTAREA.CO_EMPR=TMTRAB_EMPR.CO_EMPR 
       AND TMTRAB_EMPR.co_area=TTAREA.co_area
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TDCCOS_TRAB_raw` TDCOS
        ON TDCOS.CO_EMPR=TMTRAB_EMPR.CO_EMPR
       AND TDCOS.CO_TRAB=TMTRAB_EMPR.CO_TRAB
       AND TDCOS.TI_AUXI_EMPR = 'K'                
       AND TDCOS.ST_REPO = 'S'
LEFT JOIN  `iter-data-storage-pv-uat.ofiplan_data.TMAUXI_raw`  TMAUX
        ON TMTRAB_EMPR.CO_EMPR=TMAUX.CO_EMPR
       AND TDCOS.TI_AUXI_EMPR=TMAUX.TI_AUXI_EMPR
       AND TDCOS.CO_CENT_COST=TMAUX.CO_AUXI_EMPR
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTGRUP_OCUP_raw` GRUP
     ON GRUP.CO_GRUP_OCUP=TMTRAB_EMPR.CO_GRUP_OCUP
     AND GRUP.CO_EMPR=TMTRAB_EMPR.CO_EMPR
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTSEDE_raw` SED
     ON SED.CO_EMPR=TMTRAB_EMPR.CO_EMPR
     AND SED.CO_SEDE=TMTRAB_EMPR.CO_SEDE
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTTIPO_INF1_raw` INF
     ON INF.CO_EMPR=TMTRAB_EMPR.CO_EMPR
     AND SUBSTRING(TMTRAB_EMPR.CO_UNID,1,3)=SUBSTRING(INF.TI_INF1,3,4)
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TMTRAB_PERS_raw` PERSL
     ON PERSL.CO_TRAB=TMTRAB_EMPR.CO_TRAB_LIDE
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTMOTI_SEPA_raw` MOT
     ON MOT.CO_MOTI_SEPA=TMTRAB_EMPR.CO_MOTI_SEPA
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTTIPO_INST_raw` IST
     ON TMTRAB_PERS.CO_TIPO_INST=IST.CO_TIPO_INST
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTCATE_TRAB_raw`  TCA
     ON TCA.CO_EMPR = TMTRAB_EMPR.CO_EMPR
    AND TCA.CO_CATE_TRAB = TMTRAB_EMPR.CO_CATE_TRAB
    AND TCA.CO_GRUP_OCUP = TMTRAB_EMPR.CO_GRUP_OCUP
--AGERGADO BDU 2.0
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTPLAN_raw` PLA
     ON TMTRAB_EMPR.CO_PLAN = PLA.CO_PLAN                            
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTTIPO_CONT_raw` CONT
     ON TMTRAB_EMPR.CO_EMPR = CONT.CO_EMPR
     AND TMTRAB_EMPR.CO_TIPO_CONT = CONT.CO_TIPO_CONT
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTCALI_TRAB_raw` TRAB
     ON  TMTRAB_EMPR.CO_EMPR = TRAB.CO_EMPR
     AND TMTRAB_EMPR.CO_CALI_TRAB = TRAB.CO_CALI_TRAB
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTFORM_INGR_raw` INGR
     ON TMTRAB_EMPR.CO_FORM_INGR = INGR.CO_FORM_INGR
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTCOOP_raw` COO
     ON TMTRAB_EMPR.CO_COOP = COO.CO_COOP
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTBANC_raw` BAN
     ON TMTRAB_EMPR.CO_BANC_SUEL = BAN.CO_BANC
 LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTMONE_raw` MON
     ON TMTRAB_EMPR.CO_MONE_CTSS = MON.CO_MONE  
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTBANC_raw` BANCTS
       ON   BAN.CO_BANC = BANCTS.CO_BANC
      AND TMTRAB_EMPR.CO_BANC_CTSS = BAN.CO_BANC
--LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTSITU_raw` SITU
--     ON TMTRAB_EMPR.TI_SITU = SITU.TI_SITU
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTESTA_CIVI_raw` CIV
       ON TMTRAB_PERS.CO_ESTA_CIVI = CIV.CO_ESTA_CIVI
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTPAIS_raw` PAI
      ON TMTRAB_PERS.CO_PAIS_NACI = PAI.CO_PAIS
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTUBIC_GEOG_raw` LUG
       ON TMTRAB_PERS.CO_UBIC_GEOG = LUG.CO_UBIC_GEOG
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTPAIS_raw` PAIN
       ON TMTRAB_PERS.CO_PAIS_NCIO = PAIN.CO_PAIS
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTTIPO_VIAS_raw` VIA
       ON TMTRAB_PERS.CO_TIPO_VIAS = VIA.CO_TIPO_VIAS
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTTIPO_ZONA_raw` ZON
       ON TMTRAB_PERS.CO_TIPO_ZONA = ZON.CO_TIPO_ZONA
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTUBIC_GEOG_raw` UBIG
       ON TMTRAB_PERS.CO_UBIC_GEOG = UBIG.CO_UBIC_GEOG
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTPAIS_raw` RESI
       ON TMTRAB_PERS.CO_PAIS_RESI = RESI.CO_PAIS
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTAFPS_raw` AFP
       ON TMTRAB_PERS.CO_AFPS = AFP.CO_AFPS
LEFT JOIN TMP_NUMERO_HIJOS TRABA
       ON TRABA.CO_TRAB = TMTRAB_PERS.CO_TRAB
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTSECC_raw` TTSEC
      -- ON TMTRAB_EMPR.CO_SECC = TTSEC.CO_SECC 
       ON TMTRAB_EMPR.CO_DEPA = TTSEC.CO_DEPA
       AND TMTRAB_EMPR.CO_EMPR = TTSEC.CO_EMPR
       AND TMTRAB_EMPR.CO_AREA = TTSEC.CO_AREA
       AND TMTRAB_EMPR.CO_SECC = TTSEC.CO_SECC
LEFT JOIN `iter-data-storage-pv-uat.ofiplan_data.TTSITU_raw` SITU
     ON TMTRAB_EMPR.TI_SITU = SITU.TI_SITU
--
WHERE TMTRAB_EMPR.CO_EMPR in ('01') 
)
);
-- ----------------------------------------------------------------------
-- Paso 2: Diferencial con los registros nuevos y Modificados(algun campo no llave)
-- ----------------------------------------------------------------------
CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO_DIFF`
AS
-- Universo de Registros NUEVOS o que se Modificados
WITH TMP_LANDING AS 
(
SELECT 
 ID_PERSONA
,NOMBRES
,APELLIDO_PATERNO
,APELLIDO_MATERNO
,APELLIDOS
,PUESTO
,DESCRIPCION_PUESTO
,CODIGO_AREA
,DESCRIPCION_AREA
,TIPO_DOCUMENTO
,CODIGO_TIPO_DOCUMENTO
,DOCUMENTO_IDENTIDAD
,CODIGO_IS
,FECHA_INGRESO
,FECHA_CESE
,ESTADO
,CODIGO_VICEPRESIDENCIA
,VICEPRESIDENCIA
,FECHA_NACIMIENTO
,CELULAR
,CO_UBIC_GEOG
,CECO
,DESCRIPCION_CECO
,CODIGO_PLANILLA
,SITUACION
,GRUPO_OCUPACIONAL
,SEDE
,COD_UNIDAD
,UNIDAD
,GENERO
,NOMBRE_LIDER
,TIPO_INSTRUCCION
,MOT_SEPARACION
,CATEGORIA
,EMAIL
,EMAIL_LIDER
,CODIGO_IS_LIDER
--
,EMAIL_PERSONAL
,CUSPP
,FECHA_AFILIACION
,PLANILLA
,TIPO_CONTRATO
,CALIFICACION_TRABAJADOR
,FORMA_INGRESO
,COOPERATIVA
,BANCO_SUELDO
,MONEDA_CTS
,BANCO_CTS
,ESTADO_CIVIL
,PAIS_NACIMIENTO
,LUGAR_NACIMIENTO
,PAIS_NACIONALIDAD
,PAIS_RESIDENCIA
,TIPO_VIA
,TIPO_ZONA
,UBIGEO
,COD_TIPO_INSTRUCCION
,AFP
,FECHA_MATRIMONIO
,DIRECCION
,NUMERO_CASA                      
,NUMERO_INTERIOR
,REFERENCIA
,CELULAR_2
,CODIGO_SEDE
,NUMERO_HIJOS_DEPENDIENTES
,NUMERO_HIJOS_NODEPENDIENTES
,FECHA_INGRESO_PLANILLA	
,CODIGO_COOPERATIVA
,FECHA_INGRESO_COOPERATIVA
,NUMERO_CUENTA_SUELDO
,NUMERO_SUELDO
,NUMERO_CUENTA_CTS
,SECCION
,DESCRIPCION_SITUACION
,DESC_TIPO_ZONA
,MOTIVO_SEPARACION
--
,UPPER(TO_HEX(SHA256(CONCAT( COALESCE(ID_PERSONA,'')
,COALESCE(NOMBRES,'')
,COALESCE(APELLIDO_PATERNO,'')
,COALESCE(APELLIDO_MATERNO,'')
,COALESCE(APELLIDOS,'')
,COALESCE(PUESTO,'')
,COALESCE(DESCRIPCION_PUESTO,'')
,COALESCE(CODIGO_AREA,'')
,COALESCE(DESCRIPCION_AREA,'')
,COALESCE(TIPO_DOCUMENTO,'')
,COALESCE(CODIGO_TIPO_DOCUMENTO,'')
,COALESCE(DOCUMENTO_IDENTIDAD,'')
--,COALESCE(CODIGO_IS,'')
,COALESCE(FECHA_INGRESO,'1990-01-01')
,COALESCE(FECHA_CESE,'1990-01-01')
,COALESCE(ESTADO,'')
,COALESCE(CODIGO_VICEPRESIDENCIA,'')
,COALESCE(VICEPRESIDENCIA,'')
,COALESCE(FECHA_NACIMIENTO,'1990-01-01')
,COALESCE(CELULAR,'')
,COALESCE(CECO,'')
,COALESCE(DESCRIPCION_CECO,'')
,COALESCE(CODIGO_PLANILLA,'')
,COALESCE(SITUACION,'')
,COALESCE(GRUPO_OCUPACIONAL,'')
,COALESCE(SEDE,'')
,COALESCE(COD_UNIDAD,'')
,COALESCE(UNIDAD,'')
,COALESCE(GENERO,'')
,COALESCE(NOMBRE_LIDER,'')
,COALESCE(CO_UBIC_GEOG,'')
,COALESCE(MOT_SEPARACION,'')
,COALESCE(CATEGORIA,'')
,COALESCE(EMAIL,'')
,COALESCE(EMAIL_LIDER,'')
,COALESCE(TIPO_INSTRUCCION,'')
,COALESCE(CODIGO_IS_LIDER,'')
---------------------------------------
,COALESCE(EMAIL_PERSONAL,'')
,COALESCE(CUSPP,'')
,COALESCE(FECHA_AFILIACION,'1990-01-01')
,COALESCE(PLANILLA,'')
,COALESCE(TIPO_CONTRATO,'')
,COALESCE(CALIFICACION_TRABAJADOR,'')
,COALESCE(FORMA_INGRESO,'')
,COALESCE(COOPERATIVA,'')
,COALESCE(BANCO_SUELDO,'')
,COALESCE(MONEDA_CTS,'')
,COALESCE(BANCO_CTS,'')
,COALESCE(ESTADO_CIVIL,'')
,COALESCE(PAIS_NACIMIENTO,'')
,COALESCE(LUGAR_NACIMIENTO,'')
,COALESCE(PAIS_NACIONALIDAD,'')
,COALESCE(PAIS_RESIDENCIA,'')
,COALESCE(TIPO_VIA,'')
,COALESCE(TIPO_ZONA,'')
,COALESCE(UBIGEO,'')
,COALESCE(COD_TIPO_INSTRUCCION,'')
,COALESCE(AFP,'')
,COALESCE(FECHA_MATRIMONIO,'1990-01-01')
,COALESCE(DIRECCION,'')
,COALESCE(NUMERO_CASA,'')
,COALESCE(NUMERO_INTERIOR,'')
,COALESCE(REFERENCIA,'')
,COALESCE(CELULAR_2,'')
,COALESCE(CODIGO_SEDE,'')
,COALESCE(CAST(NUMERO_HIJOS_DEPENDIENTES AS STRING),'')
,COALESCE(CAST(NUMERO_HIJOS_NODEPENDIENTES AS STRING),'')
,COALESCE(FECHA_INGRESO_PLANILLA,'1990-01-01')	
,COALESCE(CODIGO_COOPERATIVA,'')
,COALESCE(FECHA_INGRESO_COOPERATIVA,'1990-01-01')
,COALESCE(NUMERO_CUENTA_SUELDO,'')
,COALESCE(CAST(NUMERO_SUELDO AS STRING),'')
,COALESCE(NUMERO_CUENTA_CTS,'')
,COALESCE(SECCION,'')
,COALESCE(DESCRIPCION_SITUACION,'')
,COALESCE(DESC_TIPO_ZONA,'')
,COALESCE(MOTIVO_SEPARACION,'')
---------------------------------------

)))) as hash_diff
FROM `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO`
)
SELECT LAN.*
      ,COALESCE(DIFF.FECHA_CREACION_REGISTRO,CURRENT_DATE('America/Lima')) AS FECHA_CREACION_REGISTRO
      ,CURRENT_DATE('America/Lima')   AS FECHA_MODIFICACION_REGISTRO
     FROM TMP_LANDING LAN
LEFT JOIN `iter-data-storage-pv-uat.goldenrecord_data.COLABORADOR` /*TMP_DIFF*/ DIFF -- Universo de Registros EXISTENTES en la tabla DESTINO
        ON LAN.CODIGO_IS   = DIFF.CODIGO_IS
     WHERE LAN.HASH_DIFF  <> DIFF.HASH_DIFF -- Registros Modificados
        OR DIFF.HASH_DIFF IS NULL  -- Registros Nuevos
;

-- ----------------------------------------------------------------------
-- Paso 3: 
-- ----------------------------------------------------------------------
DELETE FROM `iter-data-storage-pv-uat.goldenrecord_data.COLABORADOR`
WHERE CODIGO_IS IN (SELECT CODIGO_IS FROM `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO_DIFF` )
;
-- ----------------------------------------------------------------------
-- Paso 4: Insertar en la tabla FINAL los campos NUEVOS y MODIFICADOS
-- ----------------------------------------------------------------------
INSERT INTO `iter-data-storage-pv-uat.goldenrecord_data.COLABORADOR`
(
 ID_PERSONA
,NOMBRES
,APELLIDO_PATERNO
,APELLIDO_MATERNO
,APELLIDOS
,PUESTO
,DESCRIPCION_PUESTO
,CODIGO_AREA
,DESCRIPCION_AREA
,TIPO_DOCUMENTO
,CODIGO_TIPO_DOCUMENTO
,DOCUMENTO_IDENTIDAD
,CODIGO_IS
,FECHA_INGRESO
,FECHA_CESE
,ESTADO
,CODIGO_VICEPRESIDENCIA
,VICEPRESIDENCIA
,FECHA_NACIMIENTO
,CELULAR
,CO_UBIC_GEOG
,FECHA_CREACION_REGISTRO
,FECHA_MODIFICACION_REGISTRO
,HASH_DIFF
,CECO
,DESCRIPCION_CECO
,CODIGO_PLANILLA
,SITUACION
,GRUPO_OCUPACIONAL
,SEDE
,COD_UNIDAD
,UNIDAD
,GENERO
,NOMBRE_LIDER
,TIPO_INSTRUCCION
,MOT_SEPARACION
,CATEGORIA
,EMAIL
,EMAIL_LIDER
,CODIGO_IS_LIDER
---------------------------
,EMAIL_PERSONAL
,CUSPP
,FECHA_AFILIACION
,PLANILLA
,TIPO_CONTRATO
,CALIFICACION_TRABAJADOR
,FORMA_INGRESO
,COOPERATIVA
,BANCO_SUELDO
,MONEDA_CTS
,BANCO_CTS
,ESTADO_CIVIL
,PAIS_NACIMIENTO
,LUGAR_NACIMIENTO
,PAIS_NACIONALIDAD
,PAIS_RESIDENCIA
,TIPO_VIA
,TIPO_ZONA
,UBIGEO
,COD_TIPO_INSTRUCCION
,AFP
,FECHA_MATRIMONIO
,DIRECCION
,NUMERO_CASA                      
,NUMERO_INTERIOR
,REFERENCIA
,CELULAR_2
,CODIGO_SEDE
,NUMERO_HIJOS_DEPENDIENTES
,NUMERO_HIJOS_NODEPENDIENTES
,FECHA_INGRESO_PLANILLA	
,CODIGO_COOPERATIVA
,FECHA_INGRESO_COOPERATIVA
,NUMERO_CUENTA_SUELDO
,NUMERO_SUELDO
,NUMERO_CUENTA_CTS
,SECCION
,DESCRIPCION_SITUACION
,DESC_TIPO_ZONA
,MOTIVO_SEPARACION
---------------------------
)
SELECT DISTINCT
 ID_PERSONA
,NOMBRES
,APELLIDO_PATERNO
,APELLIDO_MATERNO
,APELLIDOS
,PUESTO
,DESCRIPCION_PUESTO
,CODIGO_AREA
,DESCRIPCION_AREA
,TIPO_DOCUMENTO
,CODIGO_TIPO_DOCUMENTO
,DOCUMENTO_IDENTIDAD
,CODIGO_IS
,FECHA_INGRESO
,FECHA_CESE
,ESTADO
,CODIGO_VICEPRESIDENCIA
,VICEPRESIDENCIA
,FECHA_NACIMIENTO
,CELULAR
,CO_UBIC_GEOG
,FECHA_CREACION_REGISTRO
,FECHA_MODIFICACION_REGISTRO
,HASH_DIFF
,CECO
,DESCRIPCION_CECO
,CODIGO_PLANILLA
,SITUACION
,GRUPO_OCUPACIONAL
,SEDE
,COD_UNIDAD
,UNIDAD
,GENERO
,NOMBRE_LIDER
,TIPO_INSTRUCCION
,MOT_SEPARACION
,CATEGORIA
,EMAIL
,EMAIL_LIDER
,CODIGO_IS_LIDER
---------------------------
,EMAIL_PERSONAL
,CUSPP
,FECHA_AFILIACION
,PLANILLA
,TIPO_CONTRATO
,CALIFICACION_TRABAJADOR
,FORMA_INGRESO
,COOPERATIVA
,BANCO_SUELDO
,MONEDA_CTS
,BANCO_CTS
,ESTADO_CIVIL
,PAIS_NACIMIENTO
,LUGAR_NACIMIENTO
,PAIS_NACIONALIDAD
,PAIS_RESIDENCIA
,TIPO_VIA
,TIPO_ZONA
,UBIGEO
,COD_TIPO_INSTRUCCION
,AFP
,FECHA_MATRIMONIO
,DIRECCION
,NUMERO_CASA                      
,NUMERO_INTERIOR
,REFERENCIA
,CELULAR_2
,CODIGO_SEDE
,NUMERO_HIJOS_DEPENDIENTES
,NUMERO_HIJOS_NODEPENDIENTES
,FECHA_INGRESO_PLANILLA	
,CODIGO_COOPERATIVA
,FECHA_INGRESO_COOPERATIVA
,NUMERO_CUENTA_SUELDO
,NUMERO_SUELDO
,NUMERO_CUENTA_CTS
,SECCION
,DESCRIPCION_SITUACION
,DESC_TIPO_ZONA
,MOTIVO_SEPARACION
---------------------------
FROM `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO_DIFF` ;

-- ----------------------------------------------------------------------
-- Eliminar tablas temporales
-- ----------------------------------------------------------------------
DROP TABLE IF EXISTS `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO` ;
DROP TABLE IF EXISTS `iter-data-storage-pv-uat.temp.TMP_COLABORADOR_UNIVERSO_DIFF` ;

SELECT 'OK' AS EJECUCION;

END;