CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.sp_master_product_md_openitem_maestra()
BEGIN

CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.master_product.MD_OPENITEM_MAESTRA`
PARTITION BY DATE_TRUNC(FECHA_VENCIMIENTO,MONTH)
CLUSTER BY ESTADO_OPENITEM
AS
SELECT
 OPENITEMID
,ID_TIPO_OPENITEM	
,TIPO_OPENITEM	
,FECHA_INICIO_OPENITEM	
,FECHA_DOCUMENTO	
,FECHA_USO_RECIBIDO	
,FECHA_VENCIMIENTO	
,MONTO	
,MONTO_BALANCE	
,ESTADO_OPENITEM	
,MONEDA_ISO	
,ID_PRODUCTO
,PRODUCTO	
,CANTIDAD_OPENITEM
,CURRENT_DATE('America/Lima') AS FECHA_CARGA
 FROM `iter-data-storage-pv-uat.acsele_data.TD_OPENITEM_MAESTRA_raw`
;

SELECT 'OK' AS ESTADO;

END;