CREATE OR REPLACE PROCEDURE `iter-data-storage-pv-uat`.programs.sp_master_transaction_reporte_cobranza_bancaseguro()
BEGIN

CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.affinity_data.REPORTE_COBRANZA_BANCASEGURO_raw`
(
ASEGURADOR STRING,
IDPRODUCTO STRING,
NOMBRE STRING,
NUMEROPOLIZA STRING,
IDCERTIFICADO STRING,
NUMCERTIFICADOPOLIZA STRING,
NUMCERTIFICADO STRING,
FECHAVENTA STRING,
INICIOPERIODO STRING,
FINPERIODO STRING,
NOMBRE_1 STRING,
ULTIMOESTADO STRING,
IDMONEDA STRING,
PRIMACOBRAR STRING,
NUMEROCOBRO STRING,
FECHAGENERA STRING,
FECHAPROCESO STRING,
IDMEDIOPAGO STRING,
NOMBRE_2 STRING,
CODSUCURSAL STRING,
NOMBRE_3 STRING,
CODCONCESIONARIO STRING,
IDOPCION STRING,
IDREGISTROCOBRO STRING,
REFERENCIA STRING,
FECHA_PROCESO STRING
)
OPTIONS (
format =AVRO,
URIS=["gs://iter-data-storage-pv-uatlake-prd-landing/PRD/AFFINITY/REPORTE_COBRANZA_BANCASEGURO/AVRO/dat_*.avro"]
)
;
  
CREATE OR REPLACE TABLE `iter-data-storage-pv-uat.master_transaction.REPORTE_COBRANZA_BANCASEGURO`
AS
SELECT 
ASEGURADOR ,
IDPRODUCTO AS ID_PRODUCTO,
NOMBRE AS NOMBRE_PRODUCTO,
NUMEROPOLIZA AS NUMERO_POLIZA ,
IDCERTIFICADO AS ID_CERTIFICADO ,
NUMCERTIFICADOPOLIZA AS NUMERO_CERTIFICADO_POLIZA,
NUMCERTIFICADO AS NUMERO_CERTIFICADO,
TIMESTAMP(FECHAVENTA)  AS FECHA_VENTA,
TIMESTAMP(INICIOPERIODO) AS FECHA_INICIO_PERIODO,
TIMESTAMP(FINPERIODO) AS FECHA_FIN_PERIODO,
NOMBRE_1 AS ESTADO_COBRANZA,
ULTIMOESTADO AS ULTIMO_ESTADO,
IDMONEDA AS MONEDA,
SAFE_CAST(PRIMACOBRAR AS FLOAT64) AS PRIMA_COBRAR,
SAFE_CAST(NUMEROCOBRO AS INT64) AS NUMERO_COBRO,
TIMESTAMP(FECHAGENERA) AS FECHA_GENERADA,
TIMESTAMP(FECHAPROCESO) AS FECHA_PROCESO,
IDMEDIOPAGO AS ID_MEDIO_PAGO,
NOMBRE_2 AS SUCURSAL,
CODSUCURSAL AS COD_SUCURSAL,
NOMBRE_3  AS LUGAR,
IDOPCION ID_OPCION,
IDREGISTROCOBRO AS ID_REGISTRO_COBRO,
REFERENCIA
 FROM `iter-data-storage-pv-uat.affinity_data.REPORTE_COBRANZA_BANCASEGURO_raw`
;

DROP TABLE IF EXISTS `iter-data-storage-pv-uat.affinity_data.REPORTE_COBRANZA_BANCASEGURO_raw`;

END;