SELECT SUM(CASE WHEN TRIM(UPPER(PROD.description)) IS NULL AND TRIM(UPPER(UAT.description))="" THEN 1 ELSE 0 END) AS DIFF_description
,SUM(CASE WHEN TRIM(UPPER(PROD.reason)) IS NULL AND TRIM(UPPER(UAT.reason))="" THEN 1 ELSE 0 END) AS DIFF_reason
,SUM(CASE WHEN TRIM(UPPER(PROD.type)) IS NULL AND TRIM(UPPER(UAT.type))="" THEN 1 ELSE 0 END) AS DIFF_type
,SUM(CASE WHEN TRIM(UPPER(PROD.doneby)) IS NULL AND TRIM(UPPER(UAT.doneby))="" THEN 1 ELSE 0 END) AS DIFF_doneby
,SUM(CASE WHEN TRIM(UPPER(PROD.type_abbr)) IS NULL AND TRIM(UPPER(UAT.type_abbr))="" THEN 1 ELSE 0 END) AS DIFF_type_abbr
FROM iter-data-storage-pv-uat.acsele_data.CLAIMRESERVEADJUST_raw UAT 
INNER JOIN interseguro-data.acsele_data.CLAIMRESERVEADJUST_raw PROD 
ON UAT.CLAIMRESERVEADJUSTID = PROD.CLAIMRESERVEADJUSTID