SELECT SUM(CASE WHEN TRIM(UPPER(PROD.description)) IS NULL AND TRIM(UPPER(UAT.description))="" THEN 1 ELSE 0 END) AS DIFF_description
,SUM(CASE WHEN TRIM(UPPER(PROD.mandatory)) IS NULL AND TRIM(UPPER(UAT.mandatory))="" THEN 1 ELSE 0 END) AS DIFF_mandatory
FROM iter-data-storage-pv-uat.acsele_data.CONFIGURATEDCOVERAGE_raw UAT 
INNER JOIN interseguro-data.acsele_data.CONFIGURATEDCOVERAGE_raw PROD 
ON UAT.CONFIGURATEDCOVERAGEID = PROD.CONFIGURATEDCOVERAGEID