SELECT SUM(CASE WHEN TRIM(UPPER(PROD.description)) IS NULL AND TRIM(UPPER(UAT.description))="" THEN 1 ELSE 0 END) AS DIFF_description
,SUM(CASE WHEN TRIM(UPPER(PROD.state)) IS NULL AND TRIM(UPPER(UAT.state))="" THEN 1 ELSE 0 END) AS DIFF_state
FROM iter-data-storage-pv-uat.acsele_data.CONFIGURABLEOBJECTTYPE_raw UAT 
INNER JOIN interseguro-data.acsele_data.CONFIGURABLEOBJECTTYPE_raw PROD 
ON UAT.CONFIGURABLEOBJECTTYPEID = PROD.CONFIGURABLEOBJECTTYPEID