SELECT SUM(CASE WHEN TRIM(UPPER(PROD.RATE)) IS NULL AND TRIM(UPPER(UAT.RATE))="" THEN 1 ELSE 0 END) AS DIFF_RATE
FROM iter-data-storage-pv-uat.acsele_data.CURRENCYRATE_raw UAT 
INNER JOIN interseguro-data.acsele_data.CURRENCYRATE_raw PROD 
ON UAT.CURRENCYTARGETID = PROD.CURRENCYTARGETID 
AND UAT.DATERATE = PROD.DATERATE 
AND UAT.CURRENCYORIGINID = PROD.CURRENCYORIGINID