SELECT SUM(CASE WHEN TRIM(UPPER(PROD.PAYMENTSEQUENCE)) IS NULL AND TRIM(UPPER(UAT.PAYMENTSEQUENCE))="" THEN 1 ELSE 0 END) AS DIFF_PAYMENTSEQUENCE
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_POLICYNUMBER)) IS NULL AND TRIM(UPPER(UAT.OPR_POLICYNUMBER))="" THEN 1 ELSE 0 END) AS DIFF_OPR_POLICYNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_RISKUNITNUMBER)) IS NULL AND TRIM(UPPER(UAT.OPR_RISKUNITNUMBER))="" THEN 1 ELSE 0 END) AS DIFF_OPR_RISKUNITNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_CLAIMNUMBER)) IS NULL AND TRIM(UPPER(UAT.OPR_CLAIMNUMBER))="" THEN 1 ELSE 0 END) AS DIFF_OPR_CLAIMNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_RECOVERYNUMBER)) IS NULL AND TRIM(UPPER(UAT.OPR_RECOVERYNUMBER))="" THEN 1 ELSE 0 END) AS DIFF_OPR_RECOVERYNUMBER
,SUM(CASE WHEN TRIM(UPPER(PROD.PGC_CATEGORY)) IS NULL AND TRIM(UPPER(UAT.PGC_CATEGORY))="" THEN 1 ELSE 0 END) AS DIFF_PGC_CATEGORY
,SUM(CASE WHEN TRIM(UPPER(PROD.OPR_PRODUCTPK)) IS NULL AND TRIM(UPPER(UAT.OPR_PRODUCTPK))="" THEN 1 ELSE 0 END) AS DIFF_OPR_PRODUCTPK
FROM iter-data-storage-pv-uat.acsele_data.OPENITEMREFERENCE_raw UAT 
INNER JOIN interseguro-data.acsele_data.OPENITEMREFERENCE_raw PROD 
ON UAT.OPENITEMREFERENCEID = PROD.OPENITEMREFERENCEID