SELECT SUM(CASE WHEN TRIM(UPPER(PROD.BENEFICIARY)) IS NULL AND TRIM(UPPER(UAT.BENEFICIARY))="" THEN 1 ELSE 0 END) AS DIFF_BENEFICIARY
,SUM(CASE WHEN TRIM(UPPER(PROD.REASON)) IS NULL AND TRIM(UPPER(UAT.REASON))="" THEN 1 ELSE 0 END) AS DIFF_REASON
,SUM(CASE WHEN TRIM(UPPER(PROD.AMOUNT)) IS NULL AND TRIM(UPPER(UAT.AMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_AMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.DONEBY)) IS NULL AND TRIM(UPPER(UAT.DONEBY))="" THEN 1 ELSE 0 END) AS DIFF_DONEBY
,SUM(CASE WHEN TRIM(UPPER(PROD.PARTICIPATIONPERCENTAGE)) IS NULL AND TRIM(UPPER(UAT.PARTICIPATIONPERCENTAGE))="" THEN 1 ELSE 0 END) AS DIFF_PARTICIPATIONPERCENTAGE
,SUM(CASE WHEN TRIM(UPPER(PROD.DEDUCTIBLEPERCENTAGE)) IS NULL AND TRIM(UPPER(UAT.DEDUCTIBLEPERCENTAGE))="" THEN 1 ELSE 0 END) AS DIFF_DEDUCTIBLEPERCENTAGE
,SUM(CASE WHEN TRIM(UPPER(PROD.DEDUCTIBLEREFERENCE)) IS NULL AND TRIM(UPPER(UAT.DEDUCTIBLEREFERENCE))="" THEN 1 ELSE 0 END) AS DIFF_DEDUCTIBLEREFERENCE
,SUM(CASE WHEN TRIM(UPPER(PROD.DEDUCTIBLEAMOUNT)) IS NULL AND TRIM(UPPER(UAT.DEDUCTIBLEAMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_DEDUCTIBLEAMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.PENALTYPERCENTAGE)) IS NULL AND TRIM(UPPER(UAT.PENALTYPERCENTAGE))="" THEN 1 ELSE 0 END) AS DIFF_PENALTYPERCENTAGE
,SUM(CASE WHEN TRIM(UPPER(PROD.REFUNDPERCENTAGE)) IS NULL AND TRIM(UPPER(UAT.REFUNDPERCENTAGE))="" THEN 1 ELSE 0 END) AS DIFF_REFUNDPERCENTAGE
,SUM(CASE WHEN TRIM(UPPER(PROD.DISTRIBUTIONAMOUNT)) IS NULL AND TRIM(UPPER(UAT.DISTRIBUTIONAMOUNT))="" THEN 1 ELSE 0 END) AS DIFF_DISTRIBUTIONAMOUNT
,SUM(CASE WHEN TRIM(UPPER(PROD.COVERAGEDESC)) IS NULL AND TRIM(UPPER(UAT.COVERAGEDESC))="" THEN 1 ELSE 0 END) AS DIFF_COVERAGEDESC
,SUM(CASE WHEN TRIM(UPPER(PROD.POR_ADDITIONALINFORMATION)) IS NULL AND TRIM(UPPER(UAT.POR_ADDITIONALINFORMATION))="" THEN 1 ELSE 0 END) AS DIFF_POR_ADDITIONALINFORMATION
FROM iter-data-storage-pv-uat.acsele_data.PAYMENTORDER_raw UAT 
INNER JOIN interseguro-data.acsele_data.PAYMENTORDER_raw PROD 
ON UAT.PAYMENTORDERID = PROD.PAYMENTORDERID