SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGINPUT)) IS NULL AND TRIM(UPPER(UAT.NIVELAGRUPREASEGINPUT))="" THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGVALUE)) IS NULL AND TRIM(UPPER(UAT.NIVELAGRUPREASEGVALUE))="" THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAINPUT)) IS NULL AND TRIM(UPPER(UAT.FECHAVENTAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAVALUE)) IS NULL AND TRIM(UPPER(UAT.FECHAVENTAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CODVENDEDORINPUT)) IS NULL AND TRIM(UPPER(UAT.CODVENDEDORINPUT))="" THEN 1 ELSE 0 END) AS DIFF_CODVENDEDORINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CODVENDEDORVALUE)) IS NULL AND TRIM(UPPER(UAT.CODVENDEDORVALUE))="" THEN 1 ELSE 0 END) AS DIFF_CODVENDEDORVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAINPUT)) IS NULL AND TRIM(UPPER(UAT.PRIMACALCULADAINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAVALUE)) IS NULL AND TRIM(UPPER(UAT.PRIMACALCULADAVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FRECUENCIAPAGOAUXINPUT)) IS NULL AND TRIM(UPPER(UAT.FRECUENCIAPAGOAUXINPUT))="" THEN 1 ELSE 0 END) AS DIFF_FRECUENCIAPAGOAUXINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FRECUENCIAPAGOAUXVALUE)) IS NULL AND TRIM(UPPER(UAT.FRECUENCIAPAGOAUXVALUE))="" THEN 1 ELSE 0 END) AS DIFF_FRECUENCIAPAGOAUXVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTOASEGURADOINPUT)) IS NULL AND TRIM(UPPER(UAT.MONTOASEGURADOINPUT))="" THEN 1 ELSE 0 END) AS DIFF_MONTOASEGURADOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTOASEGURADOVALUE)) IS NULL AND TRIM(UPPER(UAT.MONTOASEGURADOVALUE))="" THEN 1 ELSE 0 END) AS DIFF_MONTOASEGURADOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASININPUT)) IS NULL AND TRIM(UPPER(UAT.SIMBOLOMONEDASININPUT))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASININPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASINVALUE)) IS NULL AND TRIM(UPPER(UAT.SIMBOLOMONEDASINVALUE))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASINVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.RUCCONTRATANTEINPUT)) IS NULL AND TRIM(UPPER(UAT.RUCCONTRATANTEINPUT))="" THEN 1 ELSE 0 END) AS DIFF_RUCCONTRATANTEINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.RUCCONTRATANTEVALUE)) IS NULL AND TRIM(UPPER(UAT.RUCCONTRATANTEVALUE))="" THEN 1 ELSE 0 END) AS DIFF_RUCCONTRATANTEVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTOPRESTAMOINPUT)) IS NULL AND TRIM(UPPER(UAT.MONTOPRESTAMOINPUT))="" THEN 1 ELSE 0 END) AS DIFF_MONTOPRESTAMOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.MONTOPRESTAMOVALUE)) IS NULL AND TRIM(UPPER(UAT.MONTOPRESTAMOVALUE))="" THEN 1 ELSE 0 END) AS DIFF_MONTOPRESTAMOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROCUOTASINPUT)) IS NULL AND TRIM(UPPER(UAT.NUMEROCUOTASINPUT))="" THEN 1 ELSE 0 END) AS DIFF_NUMEROCUOTASINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROCUOTASVALUE)) IS NULL AND TRIM(UPPER(UAT.NUMEROCUOTASVALUE))="" THEN 1 ELSE 0 END) AS DIFF_NUMEROCUOTASVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANPROTECCIONCREDITOSINPUT)) IS NULL AND TRIM(UPPER(UAT.PLANPROTECCIONCREDITOSINPUT))="" THEN 1 ELSE 0 END) AS DIFF_PLANPROTECCIONCREDITOSINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANPROTECCIONCREDITOSVALUE)) IS NULL AND TRIM(UPPER(UAT.PLANPROTECCIONCREDITOSVALUE))="" THEN 1 ELSE 0 END) AS DIFF_PLANPROTECCIONCREDITOSVALUE
FROM iter-data-storage-pv-uat.acsele_data.POLPROTECCIONCREDITOSSCC_raw UAT 
INNER JOIN interseguro-data.acsele_data.POLPROTECCIONCREDITOSSCC_raw PROD 
ON UAT.PK = PROD.PK