SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.NUMERO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.ID_POLIZA)) IS NULL AND TRIM(UPPER(UAT.ID_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_ID_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBRE_PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.NOMBRE_PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_NOMBRE_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.EVENT)) IS NULL AND TRIM(UPPER(UAT.EVENT))="" THEN 1 ELSE 0 END) AS DIFF_EVENT
,SUM(CASE WHEN TRIM(UPPER(PROD.MOTIVO_MOVIMIENTO)) IS NULL AND TRIM(UPPER(UAT.MOTIVO_MOVIMIENTO))="" THEN 1 ELSE 0 END) AS DIFF_MOTIVO_MOVIMIENTO
,SUM(CASE WHEN TRIM(UPPER(PROD.MOVIMIENTO)) IS NULL AND TRIM(UPPER(UAT.MOVIMIENTO))="" THEN 1 ELSE 0 END) AS DIFF_MOVIMIENTO
FROM iter-data-storage-pv-uat.acsele_data.TD_ESTADO_ANULAR_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_ESTADO_ANULAR_raw PROD 
ON UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA 
AND UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION