SELECT SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_OPENITEM)) IS NULL AND TRIM(UPPER(UAT.TIPO_OPENITEM))="" THEN 1 ELSE 0 END) AS DIFF_TIPO_OPENITEM
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_OPENITEM)) IS NULL AND TRIM(UPPER(UAT.ESTADO_OPENITEM))="" THEN 1 ELSE 0 END) AS DIFF_ESTADO_OPENITEM
,SUM(CASE WHEN TRIM(UPPER(PROD.MONEDA_ISO)) IS NULL AND TRIM(UPPER(UAT.MONEDA_ISO))="" THEN 1 ELSE 0 END) AS DIFF_MONEDA_ISO
,SUM(CASE WHEN TRIM(UPPER(PROD.ID_PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.ID_PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_ID_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_PRODUCTO
FROM iter-data-storage-pv-uat.acsele_data.TD_OPENITEM_MAESTRA_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_OPENITEM_MAESTRA_raw PROD 
ON UAT.OPENITEMID = PROD.OPENITEMID