SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.NUMERO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.AUDITDATE_SYSTEM_DATE)) IS NULL AND TRIM(UPPER(UAT.AUDITDATE_SYSTEM_DATE))="" THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_SYSTEM_DATE
,SUM(CASE WHEN TRIM(UPPER(PROD.OPERATION_DATETIME)) IS NULL AND TRIM(UPPER(UAT.OPERATION_DATETIME))="" THEN 1 ELSE 0 END) AS DIFF_OPERATION_DATETIME
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBRE_PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.NOMBRE_PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_NOMBRE_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS_OPERATION)) IS NULL AND TRIM(UPPER(UAT.STATUS_OPERATION))="" THEN 1 ELSE 0 END) AS DIFF_STATUS_OPERATION
,SUM(CASE WHEN TRIM(UPPER(PROD.DESCRIPTION)) IS NULL AND TRIM(UPPER(UAT.DESCRIPTION))="" THEN 1 ELSE 0 END) AS DIFF_DESCRIPTION
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.ESTADO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_ESTADO_POLIZA
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_ASEGURADO_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_ASEGURADO_raw PROD 
ON UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION 
AND UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA