SELECT SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_POLIZA)) IS NULL AND TRIM(UPPER(UAT.NUMERO_POLIZA))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_POLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHA_EMISION)) IS NULL AND TRIM(UPPER(UAT.FECHA_EMISION))="" THEN 1 ELSE 0 END) AS DIFF_FECHA_EMISION
,SUM(CASE WHEN TRIM(UPPER(PROD.AUDITDATE_SYSTEM_DATE)) IS NULL AND TRIM(UPPER(UAT.AUDITDATE_SYSTEM_DATE))="" THEN 1 ELSE 0 END) AS DIFF_AUDITDATE_SYSTEM_DATE
,SUM(CASE WHEN TRIM(UPPER(PROD.PRODUCTO)) IS NULL AND TRIM(UPPER(UAT.PRODUCTO))="" THEN 1 ELSE 0 END) AS DIFF_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERO_SOLICITUD)) IS NULL AND TRIM(UPPER(UAT.NUMERO_SOLICITUD))="" THEN 1 ELSE 0 END) AS DIFF_NUMERO_SOLICITUD
,SUM(CASE WHEN TRIM(UPPER(PROD.USUARIO_SOLICITUD)) IS NULL AND TRIM(UPPER(UAT.USUARIO_SOLICITUD))="" THEN 1 ELSE 0 END) AS DIFF_USUARIO_SOLICITUD
,SUM(CASE WHEN TRIM(UPPER(PROD.USUARIO_APROBACION)) IS NULL AND TRIM(UPPER(UAT.USUARIO_APROBACION))="" THEN 1 ELSE 0 END) AS DIFF_USUARIO_APROBACION
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHA_EFECTIVA)) IS NULL AND TRIM(UPPER(UAT.FECHA_EFECTIVA))="" THEN 1 ELSE 0 END) AS DIFF_FECHA_EFECTIVA
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_ENDOSO)) IS NULL AND TRIM(UPPER(UAT.TIPO_ENDOSO))="" THEN 1 ELSE 0 END) AS DIFF_TIPO_ENDOSO
,SUM(CASE WHEN TRIM(UPPER(PROD.MOTIVO_ENDOSO)) IS NULL AND TRIM(UPPER(UAT.MOTIVO_ENDOSO))="" THEN 1 ELSE 0 END) AS DIFF_MOTIVO_ENDOSO
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_ENDOSO)) IS NULL AND TRIM(UPPER(UAT.ESTADO_ENDOSO))="" THEN 1 ELSE 0 END) AS DIFF_ESTADO_ENDOSO
,SUM(CASE WHEN TRIM(UPPER(PROD.EVENTO)) IS NULL AND TRIM(UPPER(UAT.EVENTO))="" THEN 1 ELSE 0 END) AS DIFF_EVENTO
,SUM(CASE WHEN TRIM(UPPER(PROD.MESES_DIFERIDOS)) IS NULL AND TRIM(UPPER(UAT.MESES_DIFERIDOS))="" THEN 1 ELSE 0 END) AS DIFF_MESES_DIFERIDOS
,SUM(CASE WHEN TRIM(UPPER(PROD.USUARIO_EVENTO)) IS NULL AND TRIM(UPPER(UAT.USUARIO_EVENTO))="" THEN 1 ELSE 0 END) AS DIFF_USUARIO_EVENTO
,SUM(CASE WHEN TRIM(UPPER(PROD.FRECUENCIA_PAGO)) IS NULL AND TRIM(UPPER(UAT.FRECUENCIA_PAGO))="" THEN 1 ELSE 0 END) AS DIFF_FRECUENCIA_PAGO
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMA_NETA)) IS NULL AND TRIM(UPPER(UAT.PRIMA_NETA))="" THEN 1 ELSE 0 END) AS DIFF_PRIMA_NETA
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMA_TOTAL)) IS NULL AND TRIM(UPPER(UAT.PRIMA_TOTAL))="" THEN 1 ELSE 0 END) AS DIFF_PRIMA_TOTAL
,SUM(CASE WHEN TRIM(UPPER(PROD.CONTRATANTE)) IS NULL AND TRIM(UPPER(UAT.CONTRATANTE))="" THEN 1 ELSE 0 END) AS DIFF_CONTRATANTE
,SUM(CASE WHEN TRIM(UPPER(PROD.IDPOLIZA)) IS NULL AND TRIM(UPPER(UAT.IDPOLIZA))="" THEN 1 ELSE 0 END) AS DIFF_IDPOLIZA
,SUM(CASE WHEN TRIM(UPPER(PROD.IDOPERACION)) IS NULL AND TRIM(UPPER(UAT.IDOPERACION))="" THEN 1 ELSE 0 END) AS DIFF_IDOPERACION
,SUM(CASE WHEN TRIM(UPPER(PROD.RN)) IS NULL AND TRIM(UPPER(UAT.RN))="" THEN 1 ELSE 0 END) AS DIFF_RN
FROM iter-data-storage-pv-uat.acsele_data.TD_POLIZA_ENDOSO_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_POLIZA_ENDOSO_raw PROD 
ON UAT.NUMERO_OPERACION = PROD.NUMERO_OPERACION 
AND UAT.NUMERO_POLIZA = PROD.NUMERO_POLIZA