SELECT SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLO_PADRE)) IS NULL AND TRIM(UPPER(UAT.SIMBOLO_PADRE))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLO_PADRE
,SUM(CASE WHEN TRIM(UPPER(PROD.TRDESC_PADRE)) IS NULL AND TRIM(UPPER(UAT.TRDESC_PADRE))="" THEN 1 ELSE 0 END) AS DIFF_TRDESC_PADRE
,SUM(CASE WHEN TRIM(UPPER(PROD.TR_DISPLAY_PADRE)) IS NULL AND TRIM(UPPER(UAT.TR_DISPLAY_PADRE))="" THEN 1 ELSE 0 END) AS DIFF_TR_DISPLAY_PADRE
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLO_HIJO)) IS NULL AND TRIM(UPPER(UAT.SIMBOLO_HIJO))="" THEN 1 ELSE 0 END) AS DIFF_SIMBOLO_HIJO
,SUM(CASE WHEN TRIM(UPPER(PROD.TRDESC_HIJO)) IS NULL AND TRIM(UPPER(UAT.TRDESC_HIJO))="" THEN 1 ELSE 0 END) AS DIFF_TRDESC_HIJO
,SUM(CASE WHEN TRIM(UPPER(PROD.TR_DISPLAY_HIJO)) IS NULL AND TRIM(UPPER(UAT.TR_DISPLAY_HIJO))="" THEN 1 ELSE 0 END) AS DIFF_TR_DISPLAY_HIJO