CREATE OR REPLACE TABLE `interseguro-data.temp.TMP_POLIZA_AGENTE_GCP_PRUEBA`
AS
WITH  TMP_AGENTE AS (
SELECT
COD_AGENTE
,CODIGO_SUPERVISOR
,CATEGORIA AS CATEGORIA_AGENTE
,DATE(FECHA_CREACION_REGISTRO) AS FECHA_OPERACION_INICIO
,COALESCE(LEAD(DATE_SUB(DATE(FECHA_CREACION_REGISTRO), INTERVAL 1 DAY))OVER(PARTITION BY COD_AGENTE ORDER BY FECHA_CREACION_REGISTRO ASC),CURRENT_DATE("America/Lima")) AS FECHA_OPERACION_FIN
FROM `interseguro-data.goldenrecord_data.HD_ESTRUCTURA_COMERCIAL`
)
,TMP_OPERACION_AGENTE AS (
SELECT
NUMERO_POLIZA
,COD_AGENTE_INICIAL
,DATE(FECHA_OPERACION) AS FECHA_OPERACION_INICIO
,COALESCE(LEAD(DATE_SUB(DATE(FECHA_OPERACION), INTERVAL 1 DAY))OVER(PARTITION BY NUMERO_POLIZA ORDER BY FECHA_OPERACION ASC),CURRENT_DATE("America/Lima")) AS FECHA_OPERACION_FIN
--,COALESCE(B.CODIGO_SUPERVISOR,ECC.CODIGO_SUPERVISOR) AS COD_SUPERVISOR_AGENTE_FINAL
--,COALESCE(B.CATEGORIA_AGENTE,ECC.CATEGORIA) AS CATEGORIA_AGENTE_INICIAL
,B.CODIGO_SUPERVISOR AS COD_SUPERVISOR_AGENTE_FINAL
,B.CATEGORIA_AGENTE AS CATEGORIA_AGENTE_INICIAL
FROM (SELECT * FROM `interseguro-data.goldenrecord_data.POLIZA_OPERACION_AGENTE`
      WHERE STATUS_OPERATION='Applied operation'
      QUALIFY(ROW_NUMBER()OVER(PARTITION BY NUMERO_POLIZA ORDER BY FECHA_OPERACION DESC))=1
     ) A --> ACSEL -E ,VIDA, HISTORIA DE RENTA NO HAY
LEFT JOIN TMP_AGENTE B
       ON A.COD_AGENTE_INICIAL=CAST(B.COD_AGENTE AS STRING)
      AND DATE(FECHA_OPERACION) BETWEEN FECHA_OPERACION_INICIO AND FECHA_OPERACION_FIN
--LEFT JOIN `interseguro-data.goldenrecord_data.ESTRUCTURA_COMERCIAL` ECC
--       ON CAST(ECC.COD_AGENTE AS STRING)=A.COD_AGENTE_INICIAL
--WHERE --NUMERO_POLIZA='06100025848'AND
--STATUS_OPERATION='Applied operation'
ORDER BY NUMERO_POLIZA DESC
)
,TMP_CARGOS_AGENTES AS (
SELECT
A.CODMES
,A.CODIGO_AGENTE
,COALESCE(B.CARGO,A.CARGO) AS CARGO_INICIAL
,A.CARGO                   AS CARGO_FINAL
,A.CODIGO_SUPERVISOR
,A.NOMBRE_SUPERVISOR
,A.CODIGO_JEFE
,A.NOMBRE_JEFE
--,A.FECHA_ULTIMO_ASCENSO
,A.FECHA_ULTIMO_ASCENSO
,A.FECHA_CAMBIO_AGENCIA
--,DATE_SUB(PARSE_DATE("%Y%m",CAST(A.CODMES AS STRING)), INTERVAL 1 MONTH) AS FECHA_INICIO_MES_ANTERIOR
--,PERIODO_RECAUDACION_DIA_FIN
--,A.CODMES
--,B.CODMES AS CODMESANTERIOR
FROM  `interseguro-data.goldenrecord_data.MM_ESTRUCTURA_COMERCIAL` A --> 202305
LEFT JOIN `interseguro-data.goldenrecord_data.MM_ESTRUCTURA_COMERCIAL` B -->
       ON CAST(A.CODMES AS STRING) = FORMAT_DATE("%Y%m",DATE_ADD(PARSE_DATE("%Y%m",CAST(B.CODMES AS STRING)),INTERVAL 1 MONTH))
      AND A.CODIGO_AGENTE=B.CODIGO_AGENTE
WHERE A.CODMES = CAST(FORMAT_DATE("%Y%m",DATE_SUB(CURRENT_DATE,INTERVAL 1 DAY)) AS INT64)
--WHERE A.CODMES IN (202306,202305) and
--where   A.CODIGO_AGENTE=17881
ORDER BY CODIGO_AGENTE DESC
)
SELECT DISTINCT
 A.numero_poliza
,A.cod_agente_inicial
,cod_agencia_inicial
,nombre_agente_inicial
,cod_agente_final
,correo_agente_final
,NOMBRE_AGENTE_FINAL
,B.CODIGO_SUPERVISOR AS COD_SUPERVISOR_INICIAL --,COD_SUPERVISOR_INICIAL --> traer EC
,B.NOMBRE_SUPERVISOR AS NOMBRE_SUPERVISOR_INICIAL  --,NOMBRE_SUPERVISOR_INICIAL --> traer EC
,A.COD_SUPERVISOR_AGENTE_FINAL
,SUPERVISOR_AGENTE_FINAL AS NOMBRE_SUPERVISOR_FINAL
,B.CODIGO_JEFE      AS COD_JEFE_INICIAL    --,COD_JEFE_INICIAL --> traer EC
,B.NOMBRE_JEFE      AS NOMBRE_JEFE_INICIAL --,NOMBRE_JEFE_INICIAL
,COD_JEFE_AGENTE_FINAL AS COD_JEFE_FINAL
,JEFE_AGENTE_FINAL     AS NOMBRE_JEFE_FINAL
,B.CARGO_INICIAL AS CARGO_INICIAL_AGENTE_INICIAL --,CARGO_INICIAL_AGENTE
,B.CARGO_FINAL   AS CARGO_FINAL_AGENTE_INICIAL
,D.CARGO_INICIAL AS CARGO_INICIAL_AGENTE_FINAL    --,CARGO_INICIAL_AGENTE
,D.CARGO_FINAL   AS CARGO_FINAL_AGENTE_FINAL
,B.FECHA_ULTIMO_ASCENSO AS FECHA_ULTIMO_ASCENSO_INICIAL
,D.FECHA_ULTIMO_ASCENSO AS FECHA_ULTIMO_ASCENSO_FINAL
,B.FECHA_CAMBIO_AGENCIA AS FECHA_CAMBIO_AGENCIA_INICIAL
,D.FECHA_CAMBIO_AGENCIA AS FECHA_CAMBIO_AGENCIA_FINAL
,K.CATEGORIA_AGENTE_INICIAL
FROM `interseguro-data.goldenrecord_data.POLIZA_AGENTE` A
LEFT JOIN TMP_CARGOS_AGENTES B --> AGENTE INICIAL
       ON A.COD_AGENTE_INICIAL = CAST( B.CODIGO_AGENTE AS STRING)
LEFT JOIN TMP_CARGOS_AGENTES D --> AGENTE FINAL
       ON A.COD_AGENTE_FINAL = CAST( D.CODIGO_AGENTE AS STRING)
LEFT JOIN TMP_OPERACION_AGENTE K
       ON A.NUMERO_POLIZA = K.NUMERO_POLIZA
       AND A.COD_AGENTE_INICIAL = K.COD_AGENTE_INICIAL;
--WHERE A.COD_AGENTE_FINAL='16651'
--LIMIT 10

-- ------------------------------------------------------------------------------------
-- Paso 4: Exportar los archivos que sufrieron un cambio o son nuevos
-- ------------------------------------------------------------------------------------
EXPORT DATA OPTIONS(
URI='gs://interseguro-datalake-prd-landing/PRD/ODS/POLIZA_AGENTE/POLIZA_AGENTE-*.csv.gz',
FORMAT='CSV',
COMPRESSION='GZIP',
overwrite=true,
header=false,
field_delimiter='~'
)
AS
SELECT DISTINCT
numero_poliza
,cod_agente_inicial
,cod_agencia_inicial
,nombre_agente_inicial
,cod_agente_final
,correo_agente_final
,NOMBRE_AGENTE_FINAL
,COD_SUPERVISOR_INICIAL
,NOMBRE_SUPERVISOR_INICIAL
,COD_SUPERVISOR_AGENTE_FINAL
,NOMBRE_SUPERVISOR_FINAL
,COD_JEFE_INICIAL
,NOMBRE_JEFE_INICIAL
,COD_JEFE_FINAL
,NOMBRE_JEFE_FINAL
,CARGO_INICIAL_AGENTE_INICIAL
,CARGO_FINAL_AGENTE_INICIAL
,CARGO_INICIAL_AGENTE_FINAL
,CARGO_FINAL_AGENTE_FINAL
,FECHA_ULTIMO_ASCENSO_INICIAL
,FECHA_ULTIMO_ASCENSO_FINAL
,FECHA_CAMBIO_AGENCIA_INICIAL
,FECHA_CAMBIO_AGENCIA_FINAL
,CATEGORIA_AGENTE_INICIAL
FROM `interseguro-data.temp.TMP_POLIZA_AGENTE_GCP_PRUEBA`;

-- ------------------------------------------------------------------------------------
-- Paso 4: Delete a temporales usadas
-- ------------------------------------------------------------------------------------
DROP TABLE IF EXISTS`interseguro-data.temp.TMP_POLIZA_AGENTE_GCP_PRUEBA` ;

