SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.AGREGATEDINSURANCEOBJECTID!=UAT.AGREGATEDINSURANCEOBJECTID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDINSURANCEOBJECTID
,SUM(CASE WHEN PROD.AGREGATEDRISKUNITID!=UAT.AGREGATEDRISKUNITID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDRISKUNITID
,SUM(CASE WHEN PROD.TYPEID!=UAT.TYPEID THEN 1 ELSE 0 END) AS DIFF_TYPEID
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.TIME_STAMP!=UAT.TIME_STAMP THEN 1 ELSE 0 END) AS DIFF_TIME_STAMP
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.AGREGATEDINSURANCEOBJECT_raw UAT 
INNER JOIN interseguro-data.acsele_data.AGREGATEDINSURANCEOBJECT_raw PROD 
ON UAT.AGREGATEDINSURANCEOBJECTID = PROD.AGREGATEDINSURANCEOBJECTID