SELECT SUM(CASE WHEN PROD.PRODUCTID!=UAT.PRODUCTID THEN 1 ELSE 0 END) AS DIFF_PRODUCTID
,SUM(CASE WHEN PROD.AGREGATEDPOLICYID!=UAT.AGREGATEDPOLICYID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDPOLICYID
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.ESTADO_CARGA!=UAT.ESTADO_CARGA THEN 1 ELSE 0 END) AS DIFF_ESTADO_CARGA
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.AGREGATEDPOLICY_raw UAT 
INNER JOIN interseguro-data.acsele_data.AGREGATEDPOLICY_raw PROD 
ON UAT.AGREGATEDPOLICYID = PROD.AGREGATEDPOLICYID