SELECT SUM(CASE WHEN PROD.CLAIMRISKUNITID!=UAT.CLAIMRISKUNITID THEN 1 ELSE 0 END) AS DIFF_CLAIMRISKUNITID
,SUM(CASE WHEN PROD.CLAIMID!=UAT.CLAIMID THEN 1 ELSE 0 END) AS DIFF_CLAIMID
,SUM(CASE WHEN PROD.AGREGATEDRISKUNITID!=UAT.AGREGATEDRISKUNITID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDRISKUNITID
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.CLAIMRISKUNIT_raw UAT 
INNER JOIN interseguro-data.acsele_data.CLAIMRISKUNIT_raw PROD 
ON UAT.CLAIMRISKUNITID = PROD.CLAIMRISKUNITID