SELECT SUM(CASE WHEN PROD.ID!=UAT.ID THEN 1 ELSE 0 END) AS DIFF_ID
,SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.ESTADO_CARGA!=UAT.ESTADO_CARGA THEN 1 ELSE 0 END) AS DIFF_ESTADO_CARGA
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
,SUM(CASE WHEN PROD.TIME_STAMP!=UAT.TIME_STAMP THEN 1 ELSE 0 END) AS DIFF_TIME_STAMP
FROM iter-data-storage-pv-uat.acsele_data.CONTEXTOPERATION_raw UAT 
INNER JOIN interseguro-data.acsele_data.CONTEXTOPERATION_raw PROD 
ON UAT.ID = PROD.ID