SELECT SUM(CASE WHEN PROD.COVERAGETITLEID!=UAT.COVERAGETITLEID THEN 1 ELSE 0 END) AS DIFF_COVERAGETITLEID
,SUM(CASE WHEN TRIM(UPPER(PROD.DESCRIPTION))!=TRIM(UPPER(UAT.DESCRIPTION)) THEN 1 ELSE 0 END) AS DIFF_DESCRIPTION
,SUM(CASE WHEN PROD.CVT_GENERATECUMULUS!=UAT.CVT_GENERATECUMULUS THEN 1 ELSE 0 END) AS DIFF_CVT_GENERATECUMULUS
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.COVERAGETITLE_raw UAT 
INNER JOIN interseguro-data.acsele_data.COVERAGETITLE_raw PROD 
ON UAT.COVERAGETITLEID = PROD.COVERAGETITLEID