SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADINPUT))!=TRIM(UPPER(UAT.EDADINPUT)) THEN 1 ELSE 0 END) AS DIFF_EDADINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADVALUE))!=TRIM(UPPER(UAT.EDADVALUE)) THEN 1 ELSE 0 END) AS DIFF_EDADVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADMINIMAASEGMASIVOINPUT))!=TRIM(UPPER(UAT.EDADMINIMAASEGMASIVOINPUT)) THEN 1 ELSE 0 END) AS DIFF_EDADMINIMAASEGMASIVOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADMINIMAASEGMASIVOVALUE))!=TRIM(UPPER(UAT.EDADMINIMAASEGMASIVOVALUE)) THEN 1 ELSE 0 END) AS DIFF_EDADMINIMAASEGMASIVOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADMAXIMAASEGMASIVOINPUT))!=TRIM(UPPER(UAT.EDADMAXIMAASEGMASIVOINPUT)) THEN 1 ELSE 0 END) AS DIFF_EDADMAXIMAASEGMASIVOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADMAXIMAASEGMASIVOVALUE))!=TRIM(UPPER(UAT.EDADMAXIMAASEGMASIVOVALUE)) THEN 1 ELSE 0 END) AS DIFF_EDADMAXIMAASEGMASIVOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADPERMANASEGMASIVOINPUT))!=TRIM(UPPER(UAT.EDADPERMANASEGMASIVOINPUT)) THEN 1 ELSE 0 END) AS DIFF_EDADPERMANASEGMASIVOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADPERMANASEGMASIVOVALUE))!=TRIM(UPPER(UAT.EDADPERMANASEGMASIVOVALUE)) THEN 1 ELSE 0 END) AS DIFF_EDADPERMANASEGMASIVOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADALCAFINPOLMASIVOSINPUT))!=TRIM(UPPER(UAT.EDADALCAFINPOLMASIVOSINPUT)) THEN 1 ELSE 0 END) AS DIFF_EDADALCAFINPOLMASIVOSINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.EDADALCAFINPOLMASIVOSVALUE))!=TRIM(UPPER(UAT.EDADALCAFINPOLMASIVOSVALUE)) THEN 1 ELSE 0 END) AS DIFF_EDADALCAFINPOLMASIVOSVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.OAPTINDIVIDUALOH_raw UAT 
INNER JOIN interseguro-data.acsele_data.OAPTINDIVIDUALOH_raw PROD 
ON UAT.PK = PROD.PK