SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPOCLIENTEINPUT))!=TRIM(UPPER(UAT.TIPOCLIENTEINPUT)) THEN 1 ELSE 0 END) AS DIFF_TIPOCLIENTEINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPOCLIENTEVALUE))!=TRIM(UPPER(UAT.TIPOCLIENTEVALUE)) THEN 1 ELSE 0 END) AS DIFF_TIPOCLIENTEVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.OASCTR_raw UAT 
INNER JOIN interseguro-data.acsele_data.OASCTR_raw PROD 
ON UAT.PK = PROD.PK