SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBREASEGURADOINPUT))!=TRIM(UPPER(UAT.NOMBREASEGURADOINPUT)) THEN 1 ELSE 0 END) AS DIFF_NOMBREASEGURADOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMBREASEGURADOVALUE))!=TRIM(UPPER(UAT.NOMBREASEGURADOVALUE)) THEN 1 ELSE 0 END) AS DIFF_NOMBREASEGURADOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTINPUT))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTVALUE))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAINPUT))!=TRIM(UPPER(UAT.FECHAVENTAINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAVENTAVALUE))!=TRIM(UPPER(UAT.FECHAVENTAVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHAVENTAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAACTIVACIONTCINPUT))!=TRIM(UPPER(UAT.FECHAACTIVACIONTCINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHAACTIVACIONTCINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAACTIVACIONTCVALUE))!=TRIM(UPPER(UAT.FECHAACTIVACIONTCVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHAACTIVACIONTCVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CODINTERMEDIARIOINPUT))!=TRIM(UPPER(UAT.CODINTERMEDIARIOINPUT)) THEN 1 ELSE 0 END) AS DIFF_CODINTERMEDIARIOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CODINTERMEDIARIOVALUE))!=TRIM(UPPER(UAT.CODINTERMEDIARIOVALUE)) THEN 1 ELSE 0 END) AS DIFF_CODINTERMEDIARIOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITINPUT))!=TRIM(UPPER(UAT.PROVEEDORDIGITINPUT)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITVALUE))!=TRIM(UPPER(UAT.PROVEEDORDIGITVALUE)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANCLONACIONOFRAUDEDINPUT))!=TRIM(UPPER(UAT.PLANCLONACIONOFRAUDEDINPUT)) THEN 1 ELSE 0 END) AS DIFF_PLANCLONACIONOFRAUDEDINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANCLONACIONOFRAUDEDVALUE))!=TRIM(UPPER(UAT.PLANCLONACIONOFRAUDEDVALUE)) THEN 1 ELSE 0 END) AS DIFF_PLANCLONACIONOFRAUDEDVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.MTOSINIESTROCLONACIONINPUT))!=TRIM(UPPER(UAT.MTOSINIESTROCLONACIONINPUT)) THEN 1 ELSE 0 END) AS DIFF_MTOSINIESTROCLONACIONINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.MTOSINIESTROCLONACIONVALUE))!=TRIM(UPPER(UAT.MTOSINIESTROCLONACIONVALUE)) THEN 1 ELSE 0 END) AS DIFF_MTOSINIESTROCLONACIONVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGINPUT))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGINPUT)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGVALUE))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGVALUE)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASININPUT))!=TRIM(UPPER(UAT.SIMBOLOMONEDASININPUT)) THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASININPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.SIMBOLOMONEDASINVALUE))!=TRIM(UPPER(UAT.SIMBOLOMONEDASINVALUE)) THEN 1 ELSE 0 END) AS DIFF_SIMBOLOMONEDASINVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.POLCLONACIONOFRAUDED_raw UAT 
INNER JOIN interseguro-data.acsele_data.POLCLONACIONOFRAUDED_raw PROD 
ON UAT.PK = PROD.PK