SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.PK!=UAT.PK THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN PROD.STATIC!=UAT.STATIC THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN PROD.STATUS!=UAT.STATUS THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANMUERTEACCVIAJESINPUT))!=TRIM(UPPER(UAT.PLANMUERTEACCVIAJESINPUT)) THEN 1 ELSE 0 END) AS DIFF_PLANMUERTEACCVIAJESINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PLANMUERTEACCVIAJESVALUE))!=TRIM(UPPER(UAT.PLANMUERTEACCVIAJESVALUE)) THEN 1 ELSE 0 END) AS DIFF_PLANMUERTEACCVIAJESVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.CARGOSINPUT))!=TRIM(UPPER(UAT.CARGOSINPUT)) THEN 1 ELSE 0 END) AS DIFF_CARGOSINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CARGOSVALUE))!=TRIM(UPPER(UAT.CARGOSVALUE)) THEN 1 ELSE 0 END) AS DIFF_CARGOSVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.DESTINOVIAJEINPUT))!=TRIM(UPPER(UAT.DESTINOVIAJEINPUT)) THEN 1 ELSE 0 END) AS DIFF_DESTINOVIAJEINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.DESTINOVIAJEVALUE))!=TRIM(UPPER(UAT.DESTINOVIAJEVALUE)) THEN 1 ELSE 0 END) AS DIFF_DESTINOVIAJEVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERODIASVIAJEMAVINPUT))!=TRIM(UPPER(UAT.NUMERODIASVIAJEMAVINPUT)) THEN 1 ELSE 0 END) AS DIFF_NUMERODIASVIAJEMAVINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMERODIASVIAJEMAVVALUE))!=TRIM(UPPER(UAT.NUMERODIASVIAJEMAVVALUE)) THEN 1 ELSE 0 END) AS DIFF_NUMERODIASVIAJEMAVVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPOVIAJEINPUT))!=TRIM(UPPER(UAT.TIPOVIAJEINPUT)) THEN 1 ELSE 0 END) AS DIFF_TIPOVIAJEINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPOVIAJEVALUE))!=TRIM(UPPER(UAT.TIPOVIAJEVALUE)) THEN 1 ELSE 0 END) AS DIFF_TIPOVIAJEVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITINPUT))!=TRIM(UPPER(UAT.PROVEEDORDIGITINPUT)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PROVEEDORDIGITVALUE))!=TRIM(UPPER(UAT.PROVEEDORDIGITVALUE)) THEN 1 ELSE 0 END) AS DIFF_PROVEEDORDIGITVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGINPUT))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGINPUT)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NIVELAGRUPREASEGVALUE))!=TRIM(UPPER(UAT.NIVELAGRUPREASEGVALUE)) THEN 1 ELSE 0 END) AS DIFF_NIVELAGRUPREASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTINPUT))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHANACIMIENTOASISTVALUE))!=TRIM(UPPER(UAT.FECHANACIMIENTOASISTVALUE)) THEN 1 ELSE 0 END) AS DIFF_FECHANACIMIENTOASISTVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAINPUT))!=TRIM(UPPER(UAT.PRIMACALCULADAINPUT)) THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.PRIMACALCULADAVALUE))!=TRIM(UPPER(UAT.PRIMACALCULADAVALUE)) THEN 1 ELSE 0 END) AS DIFF_PRIMACALCULADAVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.POLMUERTEACCVIAJES_raw UAT 
INNER JOIN interseguro-data.acsele_data.POLMUERTEACCVIAJES_raw PROD 
ON UAT.PK = PROD.PK