SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN TRIM(UPPER(PROD.PK))!=TRIM(UPPER(UAT.PK)) THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN TRIM(UPPER(PROD.STATIC))!=TRIM(UPPER(UAT.STATIC)) THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN TRIM(UPPER(PROD.STATUS))!=TRIM(UPPER(UAT.STATUS)) THEN 1 ELSE 0 END) AS DIFF_STATUS
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROOBJETOASEGINPUT))!=TRIM(UPPER(UAT.NUMEROOBJETOASEGINPUT)) THEN 1 ELSE 0 END) AS DIFF_NUMEROOBJETOASEGINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROOBJETOASEGVALUE))!=TRIM(UPPER(UAT.NUMEROOBJETOASEGVALUE)) THEN 1 ELSE 0 END) AS DIFF_NUMEROOBJETOASEGVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMCOMASEGURADOINPUT))!=TRIM(UPPER(UAT.NOMCOMASEGURADOINPUT)) THEN 1 ELSE 0 END) AS DIFF_NOMCOMASEGURADOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMCOMASEGURADOVALUE))!=TRIM(UPPER(UAT.NOMCOMASEGURADOVALUE)) THEN 1 ELSE 0 END) AS DIFF_NOMCOMASEGURADOVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMCOMBENEFICIARIOINPUT))!=TRIM(UPPER(UAT.NOMCOMBENEFICIARIOINPUT)) THEN 1 ELSE 0 END) AS DIFF_NOMCOMBENEFICIARIOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.NOMCOMBENEFICIARIOVALUE))!=TRIM(UPPER(UAT.NOMCOMBENEFICIARIOVALUE)) THEN 1 ELSE 0 END) AS DIFF_NOMCOMBENEFICIARIOVALUE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.PREINSUREDOBJECT_raw UAT 
INNER JOIN interseguro-data.acsele_data.PREINSUREDOBJECT_raw PROD 
ON UAT.PK = PROD.PK