SELECT SUM(CASE WHEN TRIM(UPPER(PROD.PK))!=TRIM(UPPER(UAT.PK)) THEN 1 ELSE 0 END) AS DIFF_PK
,SUM(CASE WHEN TRIM(UPPER(PROD.STATIC))!=TRIM(UPPER(UAT.STATIC)) THEN 1 ELSE 0 END) AS DIFF_STATIC
,SUM(CASE WHEN TRIM(UPPER(PROD.NUMEROPOLIZAINPUT))!=TRIM(UPPER(UAT.NUMEROPOLIZAINPUT)) THEN 1 ELSE 0 END) AS DIFF_NUMEROPOLIZAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHAEMISIONINPUT))!=TRIM(UPPER(UAT.FECHAEMISIONINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHAEMISIONINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.VIGENCIAINPUT))!=TRIM(UPPER(UAT.VIGENCIAINPUT)) THEN 1 ELSE 0 END) AS DIFF_VIGENCIAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.CANALVENTAINPUT))!=TRIM(UPPER(UAT.CANALVENTAINPUT)) THEN 1 ELSE 0 END) AS DIFF_CANALVENTAINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FRECUENCIAPAGOINPUT))!=TRIM(UPPER(UAT.FRECUENCIAPAGOINPUT)) THEN 1 ELSE 0 END) AS DIFF_FRECUENCIAPAGOINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.FECHASUSPCANCELINPUT))!=TRIM(UPPER(UAT.FECHASUSPCANCELINPUT)) THEN 1 ELSE 0 END) AS DIFF_FECHASUSPCANCELINPUT
,SUM(CASE WHEN TRIM(UPPER(PROD.MONEDAVALUE))!=TRIM(UPPER(UAT.MONEDAVALUE)) THEN 1 ELSE 0 END) AS DIFF_MONEDAVALUE
,SUM(CASE WHEN TRIM(UPPER(PROD.EMAILENVIOPOLIZAINPUT))!=TRIM(UPPER(UAT.EMAILENVIOPOLIZAINPUT)) THEN 1 ELSE 0 END) AS DIFF_EMAILENVIOPOLIZAINPUT
,SUM(CASE WHEN PROD.ESTADO_CARGA!=UAT.ESTADO_CARGA THEN 1 ELSE 0 END) AS DIFF_ESTADO_CARGA
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.PREPOLICY_raw UAT 
INNER JOIN interseguro-data.acsele_data.PREPOLICY_raw PROD 
ON UAT.PK = PROD.PK