SELECT SUM(CASE WHEN PROD.FMP_ID!=UAT.FMP_ID THEN 1 ELSE 0 END) AS DIFF_FMP_ID
,SUM(CASE WHEN PROD.APO_ID!=UAT.APO_ID THEN 1 ELSE 0 END) AS DIFF_APO_ID
,SUM(CASE WHEN PROD.COR_ID!=UAT.COR_ID THEN 1 ELSE 0 END) AS DIFF_COR_ID
,SUM(CASE WHEN PROD.LFA_ID!=UAT.LFA_ID THEN 1 ELSE 0 END) AS DIFF_LFA_ID
,SUM(CASE WHEN PROD.LFT_ID!=UAT.LFT_ID THEN 1 ELSE 0 END) AS DIFF_LFT_ID
,SUM(CASE WHEN TRIM(UPPER(PROD.FMP_DESCPROPERTY))!=TRIM(UPPER(UAT.FMP_DESCPROPERTY)) THEN 1 ELSE 0 END) AS DIFF_FMP_DESCPROPERTY
,SUM(CASE WHEN TRIM(UPPER(PROD.FMP_CONCEPT))!=TRIM(UPPER(UAT.FMP_CONCEPT)) THEN 1 ELSE 0 END) AS DIFF_FMP_CONCEPT
,SUM(CASE WHEN TRIM(UPPER(PROD.FMP_AMOUNT))!=TRIM(UPPER(UAT.FMP_AMOUNT)) THEN 1 ELSE 0 END) AS DIFF_FMP_AMOUNT
,SUM(CASE WHEN PROD.FMP_DATEOPERATION!=UAT.FMP_DATEOPERATION THEN 1 ELSE 0 END) AS DIFF_FMP_DATEOPERATION
,SUM(CASE WHEN PROD.FMP_DATEUSERECIPENT!=UAT.FMP_DATEUSERECIPENT THEN 1 ELSE 0 END) AS DIFF_FMP_DATEUSERECIPENT
,SUM(CASE WHEN PROD.FMP_DUEDATE!=UAT.FMP_DUEDATE THEN 1 ELSE 0 END) AS DIFF_FMP_DUEDATE
,SUM(CASE WHEN PROD.FMP_STATUS!=UAT.FMP_STATUS THEN 1 ELSE 0 END) AS DIFF_FMP_STATUS
,SUM(CASE WHEN PROD.FMP_PARENTID!=UAT.FMP_PARENTID THEN 1 ELSE 0 END) AS DIFF_FMP_PARENTID
,SUM(CASE WHEN PROD.OPM_ID!=UAT.OPM_ID THEN 1 ELSE 0 END) AS DIFF_OPM_ID
,SUM(CASE WHEN PROD.FMP_SOURCE!=UAT.FMP_SOURCE THEN 1 ELSE 0 END) AS DIFF_FMP_SOURCE
,SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.STLI_FUNDMOVEMENTPOLICY_raw UAT 
INNER JOIN interseguro-data.acsele_data.STLI_FUNDMOVEMENTPOLICY_raw PROD 
ON UAT.FMP_ID = PROD.FMP_ID