SELECT SUM(CASE WHEN PROD.AUDITDATE!=UAT.AUDITDATE THEN 1 ELSE 0 END) AS DIFF_AUDITDATE
,SUM(CASE WHEN PROD.AGREGATEDOBJECTID!=UAT.AGREGATEDOBJECTID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDOBJECTID
,SUM(CASE WHEN PROD.AGREGATEDPARENTID!=UAT.AGREGATEDPARENTID THEN 1 ELSE 0 END) AS DIFF_AGREGATEDPARENTID
,SUM(CASE WHEN PROD.OPERATIONPK!=UAT.OPERATIONPK THEN 1 ELSE 0 END) AS DIFF_OPERATIONPK
,SUM(CASE WHEN PROD.TYPEID!=UAT.TYPEID THEN 1 ELSE 0 END) AS DIFF_TYPEID
,SUM(CASE WHEN TRIM(UPPER(PROD.DESCRIPTION))!=TRIM(UPPER(UAT.DESCRIPTION)) THEN 1 ELSE 0 END) AS DIFF_DESCRIPTION
,SUM(CASE WHEN PROD.THIRDPARTYID!=UAT.THIRDPARTYID THEN 1 ELSE 0 END) AS DIFF_THIRDPARTYID
,SUM(CASE WHEN PROD.ROL_ID!=UAT.ROL_ID THEN 1 ELSE 0 END) AS DIFF_ROL_ID
,SUM(CASE WHEN PROD.TIME_STAMP!=UAT.TIME_STAMP THEN 1 ELSE 0 END) AS DIFF_TIME_STAMP
,SUM(CASE WHEN PROD.FECHA_PROCESO!=UAT.FECHA_PROCESO THEN 1 ELSE 0 END) AS DIFF_FECHA_PROCESO
FROM iter-data-storage-pv-uat.acsele_data.STPO_INSOBJPARTICIPATION_raw UAT 
INNER JOIN interseguro-data.acsele_data.STPO_INSOBJPARTICIPATION_raw PROD 
ON UAT.AGREGATEDOBJECTID = PROD.AGREGATEDOBJECTID