SELECT SUM(CASE WHEN PROD.OPENITEMID!=UAT.OPENITEMID THEN 1 ELSE 0 END) AS DIFF_OPENITEMID
,SUM(CASE WHEN PROD.ID_TIPO_OPENITEM!=UAT.ID_TIPO_OPENITEM THEN 1 ELSE 0 END) AS DIFF_ID_TIPO_OPENITEM
,SUM(CASE WHEN TRIM(UPPER(PROD.TIPO_OPENITEM))!=TRIM(UPPER(UAT.TIPO_OPENITEM)) THEN 1 ELSE 0 END) AS DIFF_TIPO_OPENITEM
,SUM(CASE WHEN PROD.FECHA_INICIO_OPENITEM!=UAT.FECHA_INICIO_OPENITEM THEN 1 ELSE 0 END) AS DIFF_FECHA_INICIO_OPENITEM
,SUM(CASE WHEN PROD.FECHA_DOCUMENTO!=UAT.FECHA_DOCUMENTO THEN 1 ELSE 0 END) AS DIFF_FECHA_DOCUMENTO
,SUM(CASE WHEN PROD.FECHA_USO_RECIBIDO!=UAT.FECHA_USO_RECIBIDO THEN 1 ELSE 0 END) AS DIFF_FECHA_USO_RECIBIDO
,SUM(CASE WHEN PROD.FECHA_VENCIMIENTO!=UAT.FECHA_VENCIMIENTO THEN 1 ELSE 0 END) AS DIFF_FECHA_VENCIMIENTO
,SUM(CASE WHEN PROD.MONTO!=UAT.MONTO THEN 1 ELSE 0 END) AS DIFF_MONTO
,SUM(CASE WHEN PROD.MONTO_BALANCE!=UAT.MONTO_BALANCE THEN 1 ELSE 0 END) AS DIFF_MONTO_BALANCE
,SUM(CASE WHEN TRIM(UPPER(PROD.ESTADO_OPENITEM))!=TRIM(UPPER(UAT.ESTADO_OPENITEM)) THEN 1 ELSE 0 END) AS DIFF_ESTADO_OPENITEM
,SUM(CASE WHEN TRIM(UPPER(PROD.MONEDA_ISO))!=TRIM(UPPER(UAT.MONEDA_ISO)) THEN 1 ELSE 0 END) AS DIFF_MONEDA_ISO
,SUM(CASE WHEN TRIM(UPPER(PROD.ID_PRODUCTO))!=TRIM(UPPER(UAT.ID_PRODUCTO)) THEN 1 ELSE 0 END) AS DIFF_ID_PRODUCTO
,SUM(CASE WHEN TRIM(UPPER(PROD.PRODUCTO))!=TRIM(UPPER(UAT.PRODUCTO)) THEN 1 ELSE 0 END) AS DIFF_PRODUCTO
,SUM(CASE WHEN PROD.CANTIDAD_OPENITEM!=UAT.CANTIDAD_OPENITEM THEN 1 ELSE 0 END) AS DIFF_CANTIDAD_OPENITEM
,SUM(CASE WHEN PROD.FECHA_CARGA!=UAT.FECHA_CARGA THEN 1 ELSE 0 END) AS DIFF_FECHA_CARGA
FROM iter-data-storage-pv-uat.acsele_data.TD_OPENITEM_MAESTRA_raw UAT 
INNER JOIN interseguro-data.acsele_data.TD_OPENITEM_MAESTRA_raw PROD 
ON UAT.OPENITEMID = PROD.OPENITEMID