CREATE OR REPLACE EXTERNAL TABLE `iter-data-storage-pv-uat.sampmed_temp.TARJETA_AFILIACION_raw`
(
  ID_TARJETA_AFILIACION NUMERIC,
  ID_TARJETA NUMERIC,
  ID_AFILIACION NUMERIC,
  ID_TIPO_ORIGEN NUMERIC,
  FECHA_CREACION STRING,
  FECHA_MODIFICACION STRING,
  FECHA_PROCESO STRING
)OPTIONS (format="PARQUET",URIS=["gs://interseguro-datalake-alloy-uat-new/sampmed_data/TARJETA_AFILIACION_raw/*.parquet"]);