WITH TMP_DATA AS (
SELECT 
'ENDOSAR' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,OBJETODELENDOSOINPUT
,OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,PRODUCTDESGINDINPUT
,PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,TIPOENDOSODESGINDINPUT
,TIPOENDOSODESGINDVALUE
,TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSAR
UNION ALL 
SELECT 
'ENDOSARACC' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,ENDOSOSIMPLEACCINPUT
,ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,INICIOVIGENCIAENDACCINPUT
,INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,TIPOVIGENCIAENDACCINPUT
,TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARACC
UNION ALL 
SELECT 
'ENDOSARAPLAZADO' AS ESTADO 
,APLAZARENDOSOINPUT
,APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,FECHAFINAPLAZOENDOSOINPUT
,FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,MESESAPLAZOPROPINPUT
,MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARAPLAZADO
UNION ALL 
SELECT 
'ENDOSARDESISTIDO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,DESISTIRENDOSOINPUT
,DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,MOTIVODESISTIRENDOSOINPUT
,MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARDESISTIDO
UNION ALL 
SELECT 
'ENDOSARFLEX' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,ENDOSOSCOMPLEJOSOPFLEXINPUT
,ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,ENDOSOSSIMPLESSACFLEXINPUT
,ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NUMEROPOLIZAFLEXINPUT
,NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NUMEROSOLICITUDINPUT
,NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,PLANVIDAINPUT
,PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARFLEX
UNION ALL 
SELECT 
'ENDOSARINSPECCIONVEH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARINSPECCIONVEH
UNION ALL 
SELECT 
'ENDOSARND' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,TIPOENDOSONDINPUT
,TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARND
UNION ALL 
SELECT 
'ENDOSARPROPRAPIDA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,TIPOENDOSOPROPRAPIDAINPUT
,TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPRAPIDA
UNION ALL 
SELECT 
'ENDOSARPROPUESTA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,TIPOENDOSOPROPUESTAINPUT
,TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARPROPUESTA
UNION ALL 
SELECT 
'ENDOSARRECHAZADO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,MOTIVORECHAZARENDOSOINPUT
,MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,RECHAZARENDOSOINPUT
,RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARRECHAZADO
UNION ALL 
SELECT 
'ENDOSARRH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,TIPOENDOSORHINPUT
,TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARRH
UNION ALL 
SELECT 
'ENDOSARSALPROSURA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,ENDOSOSSALPROSURAINPUT
,ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARSALPROSURA
UNION ALL 
SELECT 
'ENDOSARSURA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,ENDOSOSCOMPLEJOSOPSURAINPUT
,ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,ENDOSOSSIMPLESSACSURAINPUT
,ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARSURA
UNION ALL 
SELECT 
'ENDOSARVCASH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,ENDOSOSSIMPLESSACVCASHINPUT
,ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVCASH
UNION ALL 
SELECT 
'ENDOSARVEH' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,ENDOSOSVEHINPUT
,ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVEH
UNION ALL 
SELECT 
'ENDOSARVF' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,ENDOSOSCOMPLEJOSOPVFINPUT
,ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,ENDOSOSSIMPLESSACVFINPUT
,ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,FINDIFERIMIENTOINPUT
,FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,FRECUENCIAPAGOENDOSOINPUT
,FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PAGADOHASTAINPUT
,PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVF
UNION ALL 
SELECT 
'ENDOSARVIDA' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,ENDOSOSIMPLEDIFERIRINPUT
,ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,FECHAFINDIFERIMIENTOINPUT
,FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHAPGPVIDAINPUT
,FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,FRECUENCIAPAGOACTUALINPUT
,FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,INICIODIFERIMIENTOINPUT
,INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NROMESESDIFERIDOSTOTALINPUT
,NROMESESDIFERIDOSTOTALVALUE
,NROMESESULTIMOPERIODOINPUT
,NROMESESULTIMOPERIODOVALUE
,NROPERIODOSDIFERIDOSINPUT
,NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,PLANVIDAENDOSOINPUT
,PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,PRODUCTOSVIDAINPUT
,PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVIDA
UNION ALL 
SELECT 
'ENDOSARVLC' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,ENDOSOMODIFPRIMAINPUT
,ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,ENDOSOSSIMPLESSACVLCINPUT
,ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,LOGINUSUARIOINPUT
,LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NOMBREUSUARIOINPUT
,NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NUMEROPOLIZAENDOSOINPUT
,NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NUMEROSOLICITUDENDOSOINPUT
,NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,RESPONSABLEATENCIONINPUT
,RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVLC
UNION ALL 
SELECT 
'ENDOSARVP' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,CONTOIPENDINPUT
,CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,ENDOSOSCOMACCINPUT
,ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,ENDOSOSSIMPLEACCINPUT
,ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,FECHACLIENTEINPUT
,FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,FECHAFINPOLIZAINPUT
,FECHAFINPOLIZAVALUE
,FECHAMASANTIGUAOIINPUT
,FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,INICIOVIGENCIAENDOSOINPUT
,INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,TIPOENDOSOPOLINPUT
,TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSARVP
UNION ALL 
SELECT 
'ENDOSOCAMBIOFONDOFLEX' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,NULL AS FECHAEFECTIVAINPUT
,NULL AS FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,NULL AS FECHASOLICITUDINPUT
,NULL AS FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.ENDOSOCAMBIOFONDOFLEX
UNION ALL 
SELECT 
'EXCLUIRCOBENDOSO' AS ESTADO 
,NULL AS APLAZARENDOSOINPUT
,NULL AS APLAZARENDOSOVALUE
,NULL AS CONTOIPENDINPUT
,NULL AS CONTOIPENDVALUE
,NULL AS DESISTIRENDOSOINPUT
,NULL AS DESISTIRENDOSOVALUE
,NULL AS ENDOSOMODIFPRIMAINPUT
,NULL AS ENDOSOMODIFPRIMAVALUE
,NULL AS ENDOSOSCOMACCINPUT
,NULL AS ENDOSOSCOMACCVALUE
,NULL AS ENDOSOSCOMPLEJOSOPFLEXINPUT
,NULL AS ENDOSOSCOMPLEJOSOPFLEXVALUE
,NULL AS ENDOSOSCOMPLEJOSOPINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAINPUT
,NULL AS ENDOSOSCOMPLEJOSOPSURAVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVALUE
,NULL AS ENDOSOSCOMPLEJOSOPVFINPUT
,NULL AS ENDOSOSCOMPLEJOSOPVFVALUE
,NULL AS ENDOSOSIMPLEACCINPUT
,NULL AS ENDOSOSIMPLEACCVALUE
,NULL AS ENDOSOSIMPLEDIFERIRINPUT
,NULL AS ENDOSOSIMPLEDIFERIRVALUE
,NULL AS ENDOSOSSALPROSURAINPUT
,NULL AS ENDOSOSSALPROSURAVALUE
,NULL AS ENDOSOSSIMPLEACCINPUT
,NULL AS ENDOSOSSIMPLEACCVALUE
,NULL AS ENDOSOSSIMPLESSACFLEXINPUT
,NULL AS ENDOSOSSIMPLESSACFLEXVALUE
,NULL AS ENDOSOSSIMPLESSACINPUT
,NULL AS ENDOSOSSIMPLESSACSURAINPUT
,NULL AS ENDOSOSSIMPLESSACSURAVALUE
,NULL AS ENDOSOSSIMPLESSACVALUE
,NULL AS ENDOSOSSIMPLESSACVCASHINPUT
,NULL AS ENDOSOSSIMPLESSACVCASHVALUE
,NULL AS ENDOSOSSIMPLESSACVFINPUT
,NULL AS ENDOSOSSIMPLESSACVFVALUE
,NULL AS ENDOSOSSIMPLESSACVLCINPUT
,NULL AS ENDOSOSSIMPLESSACVLCVALUE
,NULL AS ENDOSOSVEHINPUT
,NULL AS ENDOSOSVEHVALUE
,NULL AS FECHACLIENTEINPUT
,NULL AS FECHACLIENTEVALUE
,FECHAEFECTIVAINPUT
,FECHAEFECTIVAVALUE
,NULL AS FECHAFINAPLAZOENDOSOINPUT
,NULL AS FECHAFINAPLAZOENDOSOVALUE
,NULL AS FECHAFINDIFERIMIENTOINPUT
,NULL AS FECHAFINDIFERIMIENTOVALUE
,NULL AS FECHAFINPOLIZAINPUT
,NULL AS FECHAFINPOLIZAVALUE
,NULL AS FECHAMASANTIGUAOIINPUT
,NULL AS FECHAMASANTIGUAOIVALUE
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHAPGPVIDAINPUT
,NULL AS FECHAPGPVIDAVALUE
,FECHASOLICITUDINPUT
,FECHASOLICITUDVALUE
,NULL AS FINDIFERIMIENTOINPUT
,NULL AS FINDIFERIMIENTOVALUE
,NULL AS FRECUENCIAPAGOACTUALINPUT
,NULL AS FRECUENCIAPAGOACTUALVALUE
,NULL AS FRECUENCIAPAGOENDOSOINPUT
,NULL AS FRECUENCIAPAGOENDOSOVALUE
,NULL AS INICIODIFERIMIENTOINPUT
,NULL AS INICIODIFERIMIENTOVALUE
,NULL AS INICIOVIGENCIAENDACCINPUT
,NULL AS INICIOVIGENCIAENDACCVALUE
,NULL AS INICIOVIGENCIAENDOSOINPUT
,NULL AS INICIOVIGENCIAENDOSOVALUE
,NULL AS LOGINUSUARIOINPUT
,NULL AS LOGINUSUARIOVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVODESISTIRENDOSOINPUT
,NULL AS MOTIVODESISTIRENDOSOVALUE
,NULL AS MOTIVORECHAZARENDOSOINPUT
,NULL AS MOTIVORECHAZARENDOSOVALUE
,NULL AS NOMBREUSUARIOINPUT
,NULL AS NOMBREUSUARIOVALUE
,NULL AS NROMESESDIFERIDOSTOTALINPUT
,NULL AS NROMESESDIFERIDOSTOTALVALUE
,NULL AS NROMESESULTIMOPERIODOINPUT
,NULL AS NROMESESULTIMOPERIODOVALUE
,NULL AS NROPERIODOSDIFERIDOSINPUT
,NULL AS NROPERIODOSDIFERIDOSVALUE
,NULL AS NUMEROPOLIZAENDOSOINPUT
,NULL AS NUMEROPOLIZAENDOSOVALUE
,NULL AS NUMEROPOLIZAFLEXINPUT
,NULL AS NUMEROPOLIZAFLEXVALUE
,NULL AS NUMEROSOLICITUDENDOSOINPUT
,NULL AS NUMEROSOLICITUDENDOSOVALUE
,NULL AS NUMEROSOLICITUDINPUT
,NULL AS NUMEROSOLICITUDVALUE
,NULL AS OBJETODELENDOSOINPUT
,NULL AS OBJETODELENDOSOVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,NULL AS PAGADOHASTAINPUT
,NULL AS PAGADOHASTAVALUE
,PK
,NULL AS PLANVIDAENDOSOINPUT
,NULL AS PLANVIDAENDOSOVALUE
,NULL AS PLANVIDAINPUT
,NULL AS PLANVIDAVALUE
,NULL AS PRODUCTDESGINDINPUT
,NULL AS PRODUCTDESGINDVALUE
,NULL AS PRODUCTOSVIDAINPUT
,NULL AS PRODUCTOSVIDAVALUE
,NULL AS RECHAZARENDOSOINPUT
,NULL AS RECHAZARENDOSOVALUE
,NULL AS RESPONSABLEATENCIONINPUT
,NULL AS RESPONSABLEATENCIONVALUE
,STATIC
,STATUS
,NULL AS TIPOENDOSODESGINDINPUT
,NULL AS TIPOENDOSODESGINDVALUE
,NULL AS TIPOENDOSOINPUT
,NULL AS TIPOENDOSONDINPUT
,NULL AS TIPOENDOSONDVALUE
,NULL AS TIPOENDOSOPOLINPUT
,NULL AS TIPOENDOSOPOLVALUE
,NULL AS TIPOENDOSOPROPRAPIDAINPUT
,NULL AS TIPOENDOSOPROPRAPIDAVALUE
,NULL AS TIPOENDOSOPROPUESTAINPUT
,NULL AS TIPOENDOSOPROPUESTAVALUE
,NULL AS TIPOENDOSORHINPUT
,NULL AS TIPOENDOSORHVALUE
,NULL AS TIPOENDOSOVALUE
,NULL AS TIPOVIGENCIAENDACCINPUT
,NULL AS TIPOVIGENCIAENDACCVALUE
,NULL AS TIPOVIGENCIAENDOSOINPUT
FROM INTERSEGURO.EXCLUIRCOBENDOSO
)
,ENDOSOS_VEHICULAR_VALUES AS (
SELECT DISTINCT P.Simbolo, F.Value, F.Description, X.TTL_VALUE as Display--, PlPr.Idproducto
,CASE WHEN SUBSTR(F.Description,0,3)='TES' THEN 'Simple' Else 'Complejo' END AS TipoEndoso
FROM Interseguro.Property P
INNER JOIN Interseguro.Transformadorfila F On F.Propertyid = P.Propertyid
LEFT JOIN Interseguro_Gu.Cdtr_Propertytranslation Pp ON P.Simbolo = Pp.Ptl_Name AND Pp.Ptl_Language IN ('es','(d)')
LEFT JOIN Interseguro_Gu.cdtr_propertytloptional ppp ON pp.ptl_name = ppp.ptlo_name AND pp.ptl_language = ppp.ptlo_language
LEFT JOIN Interseguro.Cdtr_Transformertranslation X ON F.Transformadorfilaid = X.Trf_Id AND F.Description = X.Ttl_Name AND X.Ttl_Language = Pp.Ptl_Language
WHERE X.TTL_VALUE IS NOT NULL AND LENGTH(X.TTL_VALUE) > 6
AND SUBSTR(F.Description,0,3) IN ('TEC', 'TES')
AND P.Simbolo = 'EndososVeh' 
)

SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    ,BAJ.FECHASOLICITUDINPUT AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
  --  ,BAJ.FECHASOLANULACIONINPUT AS FECHA_ANULACION
    ,BAJ.FECHAEFECTIVAINPUT AS FECHA_EFECTIVA
    ,CASE WHEN AGR.PRODUCTID IN (73989, 77849) THEN EVV.DISPLAY 
    ELSE BAJ.TIPOENDOSOPOLINPUT
    END AS TIPO_ENDOSO
    ,BAJ.LOGINUSUARIOINPUT AS USUARIO_SOLICITUD
    ,COALESCE(PRE.NUMEROSOLICITUDINPUT,BAJ.NUMEROSOLICITUDINPUT) AS NUMERO_SOLICITUD
    ,BAJ.NROMESESDIFERIDOSTOTALINPUT AS MESES_DIFERIDOS
  --  ,BAJ.FRECUENCIAPAGOENDOSOINPUT AS FRECUENCIA_PAGO_ENDOSO
  --  ,BAJ.PERIODODEVTOTALCANCINPUT AS PERIODO_TOTAL_CANCELACION
  --  ,BAJ.FECHARECEPCARTAINPUT AS FECHA_RECEPCION
   -- ,BAJ.OBSERVACIONANULACIONINPUT AS OBSERVACION
   -- ,BAJ.
    --,COALESCE(BAJ.MOTIVOANULACIONPTINPUT,BAJ.MOTIVOANULACIONVEHINPUT) AS  MOTIVO_MOVIMIENTO
  --  ,BAJ.GASTOSADMININPUT AS GASTOS_ADMINISTRATIVOS
 --   ,BAJ.CANCELREASONBANINPUT
    ,BAJ.ESTADO AS MOVIMIENTO
    ,BAJ.*
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEIDS
 --VEHICULAR
 LEFT JOIN ENDOSOS_VEHICULAR_VALUES EVV
    ON EVV.DESCRIPTION = BAJ.ENDOSOSVEHINPUT
 --INNER JOIN INTERSEGURO.STATE STAS
 --       ON STA.STATEID = PLO.STATEID
     WHERE PRE.NUMEROPOLIZAINPUT IS NOT NULL
     AND COT.STATUS <> 3
  --   AND COT.STATUS=2
     AND PRE.NUMEROPOLIZAINPUT='144632'
   --  AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');