WITH TMP_DATA AS (
SELECT 
'APLAZARPROPUESTA' AS ESTADO 
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,FECHARECEPCARTAINPUT
,FECHARECEPCARTAVALUE
,MESESAPLAZOPROPINPUT
,MESESAPLAZOPROPVALUE
,MOTIVOAPLAZARPROPINPUT
,MOTIVOAPLAZARPROPVALUE
,NULL AS MOTIVODERIVARPROPINPUT
,NULL AS MOTIVODERIVARPROPVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,PK
,STATIC
,STATUS
FROM INTERSEGURO.APLAZARPROPUESTA
UNION ALL 
SELECT 
'CAMBIARPROPUESTA' AS ESTADO 
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHARECEPCARTAINPUT
,NULL AS FECHARECEPCARTAVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVOAPLAZARPROPINPUT
,NULL AS MOTIVOAPLAZARPROPVALUE
,MOTIVODERIVARPROPINPUT
,MOTIVODERIVARPROPVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PK
,STATIC
,STATUS
FROM INTERSEGURO.CAMBIARPROPUESTA
UNION ALL 
SELECT 
'OBSERVARPROPUESTA' AS ESTADO 
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,NULL AS FECHARECEPCARTAINPUT
,NULL AS FECHARECEPCARTAVALUE
,NULL AS MESESAPLAZOPROPINPUT
,NULL AS MESESAPLAZOPROPVALUE
,NULL AS MOTIVOAPLAZARPROPINPUT
,NULL AS MOTIVOAPLAZARPROPVALUE
,NULL AS MOTIVODERIVARPROPINPUT
,NULL AS MOTIVODERIVARPROPVALUE
,NULL AS OBSERVACIONINPUT
,NULL AS OBSERVACIONVALUE
,PK
,STATIC
,STATUS
FROM INTERSEGURO.OBSERVARPROPUESTA
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
    --,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
    --,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
    --,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    --,BAJ.ESTADO AS TABLA_ORIGEN
    --,NULL AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    ,BAJ.ESTADO AS MOVIMIENTO
    ,COALESCE(BAJ.MOTIVODERIVARPROPINPUT,BAJ.MOTIVOAPLAZARPROPINPUT) AS  MOTIVO_MOVIMIENTO
    ,OBSERVACIONINPUT AS OBSERVACION
    ,MESESAPLAZOPROPINPUT AS MESES_APLAZADOS
    ,FECHARECEPCARTAINPUT AS FECHA_RECEPCION_CARTA
    ,BAJ.*
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 INNER JOIN INTERSEGURO.STATE STA
        ON STA.STATEID = PLO.STATEID
 WHERE COT.STATUS=2
    AND DATE_TRUNC('day', COT.AUDITDATE) BETWEEN TO_DATE('${v_FechaInicioYYYYMMDD}', 'YYYYMMDD') AND TO_DATE('${v_FechaFinYYYYMMDD}', 'YYYYMMDD');
  