WITH TMP_DATA AS (
SELECT 
'DERIVARCOMERCIAL' AS ESTADO
,PK
,STATIC
,STATUS
,FECHAMOVIMIENTOINPUT
,FECHAMOVIMIENTOVALUE
,OBSERVACIONINPUT
,OBSERVACIONVALUE
,MOTIVODERIVARPROPINPUT
FROM INTERSEGURO.DERIVARCOMERCIAL
UNION ALL
SELECT 
'RECIBIRDOCUMENTO' as ESTADO
,PK
,STATIC
,STATUS
,FECHAMOVIMIENTOINPUT
,NULL FECHAMOVIMIENTOVALUE
,NULL OBSERVACIONINPUT
,NULL OBSERVACIONVALUE
,NULL MOTIVODERIVARPROPINPUT
FROM INTERSEGURO.RECIBIRDOCUMENTO
)
SELECT   /*+ PARALLEL(2) */
       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA
      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION
      ,PRE.STATIC                       AS ID_POLIZA
      ,AGR.PRODUCTID
   --   ,TO_CHAR(TO_DATE(PRE.FECHAEMISIONINPUT,'YYYY-MM-DD'),'YYYY-MM-DD')    AS FECHA_EMISION
      ,UPPER(POR.DESCRIPTION )               AS NOMBRE_PRODUCTO
    --  ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS AM') AS AUDITDATE_SYSTEM_DATE
   --   ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD') AS OPERATION_DATE
    --  ,TO_CHAR(COT.TIME_STAMP ,'YYYY-MM-DD HH24:MI:SS') AS OPERATION_DATETIME
      ,EVE.DESCRIPTION AS EVENT
   -- ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
   -- ,BAJ.ESTADO AS TABLA_ORIGEN
    --,NULL AS FECHA_SOLICITUD
    ,BAJ.FECHAMOVIMIENTOINPUT AS FECHA_MOVIMIENTO
    ,BAJ.ESTADO AS MOVIMIENTO
    ,BAJ.OBSERVACIONINPUT AS OBSERVACION
    ,BAJ.MOTIVODERIVARPROPINPUT as MOTIVO_MOVIMIENTO
    FROM INTERSEGURO.PREPOLICY PRE
 INNER JOIN INTERSEGURO.POLICYDCO PLO
         ON PLO.DCOID = PRE.PK
 INNER JOIN INTERSEGURO.CONTEXTOPERATION COT
         ON COT.ID =PLO.OPERATIONPK
 INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR
         ON AGR.AGREGATEDPOLICYID = PLO.AGREGATEDOBJECTID
        -- AND AGR.OPERATIONPK = COT.ID
 INNER JOIN INTERSEGURO.PRODUCT POR
         ON POR.PRODUCTID = AGR.PRODUCTID
 INNER JOIN INTERSEGURO.EVENTDCO EVD
         ON EVD.OPERATIONPK = PLO.OPERATIONPK
 INNER JOIN TMP_DATA BAJ
         ON BAJ.PK = EVD.IDDCOEVENT
 LEFT JOIN INTERSEGURO.EVENTTYPE EVE
         ON EVE.EVENTTYPEID= EVD.EVENTTYPEID
 INNER JOIN INTERSEGURO.STATE STA
        ON STA.STATEID = PLO.STATEID
 WHERE COT.STATUS=2
