SELECT
TABLE_NAME
,CASE WHEN ROW_NUMBER()OVER(PARTITION BY TABLE_NAME ORDER BY COLUMN_ID) = 1 THEN CONCAT('SELECT \n',COLUMN_NAME)
     WHEN ROW_NUMBER()OVER(PARTITION BY TABLE_NAME ORDER BY COLUMN_ID) = MAX(COLUMN_ID)OVER(PARTITION BY TABLE_NAME) THEN CONCAT('FROM ',OWNER,'.',TABLE_NAME)
     ELSE CONCAT(',',COLUMN_NAME) END AS QUERY
FROM `interseguro-data.acsele_data.ALL_TAB_COLUMNS_raw`
WHERE TABLE_NAME IN ('APLAZARPROPUESTA', 'CAMBIARPROPUESTA','OBSERVARPROPUESTA')
ORDER BY TABLE_NAME,COLUMN_ID ASC