WITH TMP AS (
SELECT
COLUMN_NAME
,DATA_TYPE
,TABLE_NAME
,TABLE_CATALOG
,TABLE_SCHEMA
,CONCAT(TABLE_CATALOG,'.',TABLE_SCHEMA,'.',TABLE_NAME) AS ID_TABLE_UAT
,CONCAT('interseguro-data','.',TABLE_SCHEMA,'.',TABLE_NAME) AS ID_TABLE_PROD
,ROW_NUMBER()OVER(PARTITION BY TABLE_NAME) AS ORDEN
,CASE WHEN DATA_TYPE ='STRING' THEN CONCAT('TRIM(UPPER(PROD.',COLUMN_NAME,'))')
      ELSE CONCAT("PROD.",COLUMN_NAME) END AS VALOR_BUC
,CASE WHEN DATA_TYPE ='STRING' THEN CONCAT('TRIM(UPPER(UAT.',COLUMN_NAME,'))')
      ELSE CONCAT("UAT.",COLUMN_NAME) END AS VALOR_MIR
FROM  iter-data-storage-pv-uat.acsele_data.INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME IN ('TD_POLIZA_ASEGURADO_DESGTARJETASIND_raw')
--WHERE TABLE_NAME LIKE 'TD_%'
--AND TABLE_NAME NOT LIKE '%_landing%'
)
SELECT
ORDEN
,TABLE_NAME
,COLUMN_NAME
,ID_TABLE_UAT
,CASE WHEN ORDEN = 1 THEN CONCAT('SELECT SUM(CASE WHEN ',VALOR_BUC,'!=',VALOR_MIR,' THEN 1 ELSE 0 END) ','AS DIFF_',COLUMN_NAME)
    --  WHEN ORDEN = COUNT(*)OVER(PARTITION BY TABLE_NAME) THEN CONCAT (
    --  CONCAT(',SUM(CASE WHEN ',VALOR_BUC,'!=',VALOR_MIR,' THEN 1 ELSE 0 END) ','AS DIFF_',COLUMN_NAME)
    --  ,CONCAT (' FROM ',ID_TABLE_PROD,' PROD INNER JOIN ',
    --  ID_TABLE_UAT ,' UAT ON PROD.NUMERO_POLIZA = UAT.NUMERO_POLIZA AND PROD.NUMERO_OPERACION = UAT.NUMERO_OPERACION')
    --  )
      ELSE CONCAT(',SUM(CASE WHEN ',VALOR_BUC,'!=',VALOR_MIR,' THEN 1 ELSE 0 END) ','AS DIFF_',COLUMN_NAME) END AS QUERY
FROM TMP
ORDER BY TABLE_NAME, ORDEN ASC