WITH TMP AS (
SELECT
 COLUMN_NAME
,DATA_TYPE
,TABLE_NAME
,TABLE_CATALOG
,TABLE_SCHEMA
,CONCAT(TABLE_CATALOG,'.',TABLE_SCHEMA,'.',TABLE_NAME) AS ID_TABLE_UAT
,CONCAT('interseguro-data','.',TABLE_SCHEMA,'.',TABLE_NAME) AS ID_TABLE_PROD
,ROW_NUMBER()OVER(PARTITION BY TABLE_NAME) AS ORDEN
,CASE WHEN DATA_TYPE ='STRING' THEN CONCAT('TRIM(UPPER(PROD.',COLUMN_NAME,'))')
      ELSE CONCAT("PROD.",COLUMN_NAME) END AS VALOR_BUC
,CASE WHEN DATA_TYPE ='STRING' THEN CONCAT('TRIM(UPPER(UAT.',COLUMN_NAME,'))')
      ELSE CONCAT("UAT.",COLUMN_NAME) END AS VALOR_MIR
FROM  iter-data-storage-pv-uat.acsele_data.INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE ='STRING' -- TABLE_NAME IN ('TD_OPERACION_VIDA_AGENTE_raw')
)
SELECT
ORDEN
,TABLE_NAME
,COLUMN_NAME
,ID_TABLE_UAT
,IF(DATA_TYPE='STRING',(CASE WHEN ORDEN = 1 THEN CONCAT('SELECT SUM(CASE WHEN ',VALOR_BUC,' IS NULL AND ',VALOR_MIR,'="" THEN 1 ELSE 0 END) ','AS DIFF_',COLUMN_NAME)
                                  ELSE CONCAT(',SUM(CASE WHEN ',VALOR_BUC,' IS NULL AND ',VALOR_MIR,'="" THEN 1 ELSE 0 END) ','AS DIFF_',COLUMN_NAME)
                                  END ),NULL)  AS QUERY
FROM TMP
ORDER BY TABLE_NAME, ORDEN ASC